#!/usr/bin/env python3
"""Regenerate fds_density_split.f90 from the unmodified FDS Source/mass.f90 (line ranges copied verbatim; !$OMP lines dropped).
Usage: python3 gen_density_split.py [path/to/mass.f90]   (writes fds_density_split.f90 next to this script's parent directory)
The line ranges are those of the tree this driver was written against (mass.f90:365-768, 966-989); the script checks the anchor lines
and refuses to run on a mass.f90 whose anchors moved."""
import sys, os
here = os.path.dirname(os.path.abspath(__file__))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, '..', '..', 'mass.f90')
src = open(SRC).read().split('\n')
def L(a, b): return [l for l in src[a-1:b] if not l.lstrip().upper().startswith('!$OMP')]
def anchor(n, text):
    if text not in src[n-1]:
        sys.exit('gen_density_split: mass.f90 line %d does not contain %r (found %r): update the line ranges' % (n, text, src[n-1].strip()))
anchor(365, 'SUBROUTINE DENSITY(T,DT,NM)'); anchor(518, 'CALL CHECK_MASS_DENSITY'); anchor(700, 'CALL CHECK_MASS_DENSITY')
anchor(768, 'T_USED'); anchor(966, 'SUBROUTINE CLIP_PASSIVE_SCALARS'); anchor(989, 'END SUBROUTINE CLIP_PASSIVE_SCALARS')
HDR = '''!> Derived copy of the FDS subroutine DENSITY (mass.f90:365-768 and CLIP_PASSIVE_SCALARS 966-989), split at the CHECK_MASS_DENSITY call so that
!> the layout-independent gather clip (fds_clip_gather.f90, D-031) can run between the two halves. GENERATED by tools/gen_density_split.py;
!> the FDS file itself is NOT edited and stays the reference (the unmodified DENSITY is also callable from the shim for comparison).
!>  * DENSITY_PRE_CLIP  = mass.f90:365-513 (predictor, up to RHOS=SUM(ZZS)) + 584-695 (corrector, up to RHO=SUM(ZZ)).
!>  * DENSITY_POST_CLIP = mass.f90:365-397 (declarations, early returns, POINT_TO_MESH) + 522-582 + 704-764 + 768 + CLIP_PASSIVE_SCALARS.
!>  * the two CALL CHECK_MASS_DENSITY (mass.f90:518, 700) are removed; the driver runs the gather clip in between. !$OMP lines are dropped.
!>
!> Kernel-facing rules (M2a): (a) passive scalars (N_TOTAL_SCALARS beyond the tracked species) are handled by Fields.cpp (ZZ/ZZS carry
!> ncomp=N_TOTAL_SCALARS); the copied code loops over 1:N_TOTAL_SCALARS unchanged. (b) only uniform Cartesian metrics are used; R(I)/RRN(I)
!> stay as FDS set them (=1) and CYLINDRICAL or TRN* meshes are rejected at level-0 assembly.
MODULE FDS_DENSITY_SPLIT

USE PRECISION_PARAMETERS
USE GLOBAL_CONSTANTS
USE MESH_POINTERS
USE COMP_FUNCTIONS, ONLY: CURRENT_TIME
USE FDS_BOX_OBJ, ONLY: HAS_M_DOT_PPP

IMPLICIT NONE (TYPE,EXTERNAL)
PRIVATE
PUBLIC DENSITY_PRE_CLIP, DENSITY_POST_CLIP

CONTAINS

'''
pre = L(365, 513); pre[0] = 'SUBROUTINE DENSITY_PRE_CLIP(T,DT,NM)'
pre += ['   ! ---- mass.f90:515-520 CALL CHECK_MASS_DENSITY removed (gather clip in the driver); continues in DENSITY_POST_CLIP ----', '']
pre += L(584, 695)
pre += ['   ! ---- mass.f90:697-702 CALL CHECK_MASS_DENSITY removed; continues in DENSITY_POST_CLIP ----',
        'END SELECT PREDICTOR_STEP', '', 'END SUBROUTINE DENSITY_PRE_CLIP', '', '']
post = L(365, 397); post[0] = 'SUBROUTINE DENSITY_POST_CLIP(T,DT,NM)'
post += ['', 'PREDICTOR_STEP: SELECT CASE (PREDICTOR)', '', 'CASE(.TRUE.) PREDICTOR_STEP', '']
post += L(522, 582)
post += ['', 'CASE(.FALSE.) PREDICTOR_STEP  ! CORRECTOR step', '']
post += L(704, 768)
post += ['', 'CONTAINS', ''] + L(966, 989) + ['', 'END SUBROUTINE DENSITY_POST_CLIP', '', 'END MODULE FDS_DENSITY_SPLIT', '']
out = os.path.join(here, '..', 'fds_density_split.f90')
txt = HDR + '\n'.join(pre + post)
# D-056 option B: the copy finds its box through POINT_TO_BOX (level 0: same as POINT_TO_MESH) and reads M_DOT_PPP from the mesh object of the box (level 0 or fine level)
assert txt.count('CALL POINT_TO_MESH(NM)') == 2 and txt.count('ALLOCATED(MESHES(NM)%M_DOT_PPP)') == 2
txt = txt.replace('CALL POINT_TO_MESH(NM)', 'CALL POINT_TO_BOX(NM)').replace('ALLOCATED(MESHES(NM)%M_DOT_PPP)', 'HAS_M_DOT_PPP(NM)')
# Interface flux hooks (notes/flux-hooks-design.md, driver side only: mass.f90 is not edited). Before each of the two species updates the copy asks the hook module whether the box is in read-out
# or override mode; read-out stores the stage product FX*UU (FY*VV, FZ*WW) and returns without updating, override with a non-empty list runs a second copy of the update loop that reads
# the product arrays PRX,PRY,PRZ (the product with the listed faces replaced). The original loop is untouched and is what runs whenever no list is set (bitwise the unhooked code).
def hook_block(txt, rhs_anchor):
    i = txt.index(rhs_anchor)
    a = txt.rindex('   DO N=1,N_TOTAL_SCALARS', 0, i)
    b = txt.index('\n   ENDDO\n', i) + len('\n   ENDDO\n')
    blk = txt[a:b]
    alt = blk
    for o, n in (('FX(I,J,K,N)*UU(I,J,K)*R(I) - FX(I-1,J,K,N)*UU(I-1,J,K)*R(I-1)', 'PRX(I,J,K,N)*R(I) - PRX(I-1,J,K,N)*R(I-1)'),
                 ('FY(I,J,K,N)*VV(I,J,K)      - FY(I,J-1,K,N)*VV(I,J-1,K)       ', 'PRY(I,J,K,N)      - PRY(I,J-1,K,N)       '),
                 ('FZ(I,J,K,N)*WW(I,J,K)      - FZ(I,J,K-1,N)*WW(I,J,K-1)       ', 'PRZ(I,J,K,N)      - PRZ(I,J,K-1,N)       ')):
        assert alt.count(o) == 1, o
        alt = alt.replace(o, n)
    hook = ('   ! ---- interface flux hooks (fds_flux_hooks.f90): read-out of the stage product (the update is skipped) or the list of overridden faces ----\n'
            '   OVR_ADV = .FALSE.\n'
            '   IF (FDS_FLUX_ACTIVE(NM,0)) THEN\n'
            '      CALL FDS_HOOK_ADV(NM,LBOUND(FX,4),LBOUND(UU),LBOUND(VV),LBOUND(WW),UU,VV,WW,FX,FY,FZ,RO_ADV,OVR_ADV)\n'
            '      IF (RO_ADV) RETURN\n'
            '   ENDIF\n'
            '   IF (OVR_ADV) THEN\n' + alt + '   ELSE\n' + blk + '   ENDIF\n')
    return txt[:a] + hook + txt[b:]
txt = hook_block(txt, 'RHS = - DEL_RHO_D_DEL_Z__0(I,J,K,N)')
txt = hook_block(txt, 'RHS = - DEL_RHO_D_DEL_Z(I,J,K,N)')
assert txt.count('USE CC_SCALARS, ONLY : SET_EXIMADVFLX_3D,ROTATED_CUBE_RHS_ZZ\n') >= 1 and txt.count('REAL(EB) :: TNOW,RHS,Q_Z,XHAT,ZHAT\n') >= 1
txt = txt.replace('USE CC_SCALARS, ONLY : SET_EXIMADVFLX_3D,ROTATED_CUBE_RHS_ZZ\n', 'USE CC_SCALARS, ONLY : SET_EXIMADVFLX_3D,ROTATED_CUBE_RHS_ZZ\nUSE FDS_FLUX_HOOKS, ONLY: FDS_FLUX_ACTIVE,FDS_HOOK_ADV,PRX,PRY,PRZ\n', 1)
txt = txt.replace('REAL(EB) :: TNOW,RHS,Q_Z,XHAT,ZHAT\n', 'REAL(EB) :: TNOW,RHS,Q_Z,XHAT,ZHAT\nLOGICAL :: RO_ADV,OVR_ADV\n', 1)
open(out, 'w').write(txt)
print('wrote', os.path.normpath(out))
