!> \brief bind(C) wrappers that call the UNMODIFIED FDS kernels on one box (= one MESHES(NM) entry) and the data-transfer routines used by the
!> kernel check (M2a, S3). The kernels find their data through POINT_TO_MESH(NM), i.e. through MESHES(NM)%X: field arrays bound from AMReX FABs
!> by FDS_BOX_SHIM (native FAB, native bounds; no strided window) and the FDS-owned side data built by the FDS set-up.
!>
!> Kernel-facing file rules (M2a):
!> (a) Passive scalars (N_TOTAL_SCALARS beyond the tracked species) are handled by Fields.cpp: ZZ/ZZS carry ncomp=N_TOTAL_SCALARS as the last
!>     extent and the kernels loop over 1:N_TOTAL_SCALARS unchanged; nothing here depends on the count.
!> (b) Only uniform Cartesian metrics are used: R(I)/RRN(I) stay as the FDS set-up made them (=1); CYLINDRICAL and TRN* meshes are rejected at
!>     level-0 assembly, so VELOCITY_FLUX_CYLINDRICAL is never called.
!>
!> Kernels wrapped: COMPUTE_VISCOSITY, MASS_FINITE_DIFFERENCES+DENSITY (unmodified) and MASS_FINITE_DIFFERENCES+DENSITY_PRE_CLIP / DENSITY_POST_CLIP
!> (fds_density_split.f90, for the D-031 gather clip), VELOCITY_FLUX, DIVERGENCE_PART_1, DIVERGENCE_PART_2, VELOCITY_PREDICTOR, VELOCITY_CORRECTOR.
!> Boundary table: README.md, "Fortran/C++ boundary".
MODULE FDS_KERNELS

USE ISO_C_BINDING
USE PRECISION_PARAMETERS, ONLY: EB
USE GLOBAL_CONSTANTS
USE FDS_AMREX_HOOKS, ONLY: FDS_HOOK_FINE_GUARD
USE MESH_VARIABLES, ONLY: MESHES,MESH_TYPE
USE VELO, ONLY: COMPUTE_VISCOSITY,VELOCITY_FLUX,VELOCITY_PREDICTOR,VELOCITY_CORRECTOR
USE MASS, ONLY: MASS_FINITE_DIFFERENCES,DENSITY
USE DIVG, ONLY: DIVERGENCE_PART_1,DIVERGENCE_PART_2
USE FDS_DENSITY_SPLIT, ONLY: DENSITY_PRE_CLIP,DENSITY_POST_CLIP

IMPLICIT NONE (TYPE,EXTERNAL)
PRIVATE

REAL(EB), ALLOCATABLE, TARGET, SAVE :: DT_NEW_K(:)
TYPE MATCH_T
   INTEGER, ALLOCATABLE :: W(:),E(:)   !< box wall / edge index -> index in the dump arrays (0 = no counterpart)
   INTEGER :: NWD=0,NED=0
END TYPE MATCH_T
TYPE(MATCH_T), ALLOCATABLE, SAVE :: MT(:)

INTEGER, PARAMETER :: MODE_LOAD=0,MODE_CMP=1,MODE_READ=3   ! MODE_READ: copy the array region into DATA (diagnostic dumps, S8)
LOGICAL, SAVE :: VERBOSE_DIFF=.FALSE.   !< print the first differing element of every array (set by FDS_K_VERBOSE)

PUBLIC :: FDS_K_VERBOSE,FDS_K_STATE,FDS_K_VISC,FDS_K_DENS,FDS_K_DENS_PRE,FDS_K_DENS_POST,FDS_K_VFLUX,FDS_K_DIV1,FDS_K_DIV2,FDS_K_VPRED,FDS_K_VCORR, &
          FDS_K_CONSTS,FDS_K_FLAGS,FDS_K_SET_FLAGS,FDS_K_SET_RESTRICT,FDS_K_GET_RESTRICT,FDS_K_XFER,FDS_K_MATCH,FDS_K_NEUTRALIZE

CONTAINS

SUBROUTINE FDS_K_VERBOSE(V) BIND(C,NAME='fds_k_verbose')
INTEGER(C_INT), VALUE :: V
VERBOSE_DIFF = (V/=0)
END SUBROUTINE FDS_K_VERBOSE

!> Global FDS state that the main loop sets before the kernels (PREDICTOR/CORRECTOR/FIRST_PASS/ICYC, density limits).
SUBROUTINE FDS_K_STATE(PRED,FIRST,ICYC_IN,RMIN,RMAX) BIND(C,NAME='fds_k_state')
INTEGER(C_INT), VALUE :: PRED,FIRST,ICYC_IN
REAL(C_DOUBLE), VALUE :: RMIN,RMAX
PREDICTOR = (PRED/=0) ; CORRECTOR = .NOT.PREDICTOR ; FIRST_PASS = (FIRST/=0) ; ICYC = ICYC_IN
RHOMIN = RMIN ; RHOMAX = RMAX
IF (.NOT.ALLOCATED(DT_NEW_K)) ALLOCATE(DT_NEW_K(NMESHES))
END SUBROUTINE FDS_K_STATE

SUBROUTINE FDS_K_VISC(NM,EST) BIND(C,NAME='fds_k_visc')
INTEGER(C_INT), VALUE :: NM,EST
CALL FDS_HOOK_FINE_GUARD('fds_k_visc',NM,NMESHES)
CALL COMPUTE_VISCOSITY(NM,APPLY_TO_ESTIMATED_VARIABLES=(EST/=0))
END SUBROUTINE FDS_K_VISC

!> MASS_FINITE_DIFFERENCES + the unmodified DENSITY (FDS's own CHECK_MASS_DENSITY inside).
SUBROUTINE FDS_K_DENS(T,DT,NM) BIND(C,NAME='fds_k_dens')
REAL(C_DOUBLE), VALUE :: T,DT
INTEGER(C_INT), VALUE :: NM
CALL FDS_HOOK_FINE_GUARD('fds_k_dens',NM,NMESHES)
CALL MASS_FINITE_DIFFERENCES(NM)
CALL DENSITY(T,DT,NM)
END SUBROUTINE FDS_K_DENS

!> D-031 variant: first half (up to the clip) and second half (after the clip); the gather clip (fds_clip_gather.f90) runs in between.
SUBROUTINE FDS_K_DENS_PRE(T,DT,NM) BIND(C,NAME='fds_k_dens_pre')
REAL(C_DOUBLE), VALUE :: T,DT
INTEGER(C_INT), VALUE :: NM
CALL FDS_HOOK_FINE_GUARD('fds_k_dens_pre',NM,NMESHES)
CALL MASS_FINITE_DIFFERENCES(NM)
CALL DENSITY_PRE_CLIP(T,DT,NM)
END SUBROUTINE FDS_K_DENS_PRE

SUBROUTINE FDS_K_DENS_POST(T,DT,NM) BIND(C,NAME='fds_k_dens_post')
REAL(C_DOUBLE), VALUE :: T,DT
INTEGER(C_INT), VALUE :: NM
CALL FDS_HOOK_FINE_GUARD('fds_k_dens_post',NM,NMESHES)
CALL DENSITY_POST_CLIP(T,DT,NM)
END SUBROUTINE FDS_K_DENS_POST

SUBROUTINE FDS_K_VFLUX(T,DT,NM,EST) BIND(C,NAME='fds_k_vflux')
REAL(C_DOUBLE), VALUE :: T,DT
INTEGER(C_INT), VALUE :: NM,EST
CALL FDS_HOOK_FINE_GUARD('fds_k_vflux',NM,NMESHES)
CALL VELOCITY_FLUX(T,DT,NM,APPLY_TO_ESTIMATED_VARIABLES=(EST/=0))
END SUBROUTINE FDS_K_VFLUX

SUBROUTINE FDS_K_DIV1(T,DT,NM) BIND(C,NAME='fds_k_div1')
REAL(C_DOUBLE), VALUE :: T,DT
INTEGER(C_INT), VALUE :: NM
CALL FDS_HOOK_FINE_GUARD('fds_k_div1',NM,NMESHES)
CALL DIVERGENCE_PART_1(T,DT,NM)
END SUBROUTINE FDS_K_DIV1

SUBROUTINE FDS_K_DIV2(DT,NM) BIND(C,NAME='fds_k_div2')
REAL(C_DOUBLE), VALUE :: DT
INTEGER(C_INT), VALUE :: NM
CALL FDS_HOOK_FINE_GUARD('fds_k_div2',NM,NMESHES)
CALL DIVERGENCE_PART_2(DT,NM)
END SUBROUTINE FDS_K_DIV2

!> VELOCITY_PREDICTOR incl. its CHECK_STABILITY; returns this box's DT_NEW, CHANGE_TIME_STEP_INDEX, CFL and VN.
SUBROUTINE FDS_K_VPRED(T,DT,NM,DTNEW,ICHG,CFL,VN) BIND(C,NAME='fds_k_vpred')
REAL(C_DOUBLE), VALUE :: T,DT
INTEGER(C_INT), VALUE :: NM
REAL(C_DOUBLE), INTENT(OUT) :: DTNEW,CFL,VN
INTEGER(C_INT), INTENT(OUT) :: ICHG
CALL FDS_HOOK_FINE_GUARD('fds_k_vpred',NM,NMESHES)
DT_NEW_K = DT ; CHANGE_TIME_STEP_INDEX(NM) = 0
CALL VELOCITY_PREDICTOR(T,DT,DT_NEW_K,NM)
DTNEW = DT_NEW_K(NM) ; ICHG = CHANGE_TIME_STEP_INDEX(NM) ; CFL = MESHES(NM)%CFL ; VN = MESHES(NM)%VN
END SUBROUTINE FDS_K_VPRED

SUBROUTINE FDS_K_VCORR(T,DT,NM) BIND(C,NAME='fds_k_vcorr')
REAL(C_DOUBLE), VALUE :: T,DT
INTEGER(C_INT), VALUE :: NM
CALL FDS_HOOK_FINE_GUARD('fds_k_vcorr',NM,NMESHES)
CALL VELOCITY_CORRECTOR(T,DT,NM)
END SUBROUTINE FDS_K_VCORR

!> FDS constants used by the time-step replay hook (main.f90:763-767) and the zone count.
SUBROUTINE FDS_K_CONSTS(TEND,DTFILL,DTMIN,DT0,NZONE) BIND(C,NAME='fds_k_consts')
REAL(C_DOUBLE), INTENT(OUT) :: TEND,DTFILL,DTMIN,DT0
INTEGER(C_INT), INTENT(OUT) :: NZONE
TEND = T_END ; DTFILL = DT_END_FILL ; DTMIN = DT_END_MINIMUM ; DT0 = DT_INITIAL ; NZONE = N_ZONE
END SUBROUTINE FDS_K_CONSTS

!> Per-mesh density clip flags (bit0 CLIP_RHOMIN, bit1 CLIP_RHOMAX) as set by DENSITY.
FUNCTION FDS_K_FLAGS(NM) BIND(C,NAME='fds_k_flags') RESULT(F)
INTEGER(C_INT), VALUE :: NM
INTEGER(C_INT) :: F
CALL FDS_HOOK_FINE_GUARD('fds_k_flags',NM,NMESHES)
F = 0
IF (MESHES(NM)%CLIP_RHOMIN) F = F+1
IF (MESHES(NM)%CLIP_RHOMAX) F = F+2
END FUNCTION FDS_K_FLAGS

SUBROUTINE FDS_K_SET_FLAGS(NM,F) BIND(C,NAME='fds_k_set_flags')
INTEGER(C_INT), VALUE :: NM,F
CALL FDS_HOOK_FINE_GUARD('fds_k_set_flags',NM,NMESHES)
MESHES(NM)%CLIP_RHOMIN = (IAND(F,1)/=0)
MESHES(NM)%CLIP_RHOMAX = (IAND(F,2)/=0)
END SUBROUTINE FDS_K_SET_FLAGS

SUBROUTINE FDS_K_SET_RESTRICT(NM,N) BIND(C,NAME='fds_k_set_restrict')
INTEGER(C_INT), VALUE :: NM,N
CALL FDS_HOOK_FINE_GUARD('fds_k_set_restrict',NM,NMESHES)
MESHES(NM)%DT_RESTRICT_COUNT = N
END SUBROUTINE FDS_K_SET_RESTRICT


FUNCTION FDS_K_GET_RESTRICT(NM) BIND(C,NAME='fds_k_get_restrict') RESULT(N)
INTEGER(C_INT), VALUE :: NM
INTEGER(C_INT) :: N
CALL FDS_HOOK_FINE_GUARD('fds_k_get_restrict',NM,NMESHES)
N = MESHES(NM)%DT_RESTRICT_COUNT
END FUNCTION FDS_K_GET_RESTRICT


!> Build the wall/edge correspondence between box NM and the dump arrays (the dump is one mesh; the box origin is OFF cells inside it).
!> A box wall corresponds to the dump wall with the same IOR and (IIG,JJG,KKG)+OFF; a box edge to the dump edge with (I,J,K)+OFF and AXIS.
!> Walls/edges of the box without counterpart (mesh-to-mesh interfaces of a split) get a zero match.
SUBROUTINE FDS_K_MATCH(NM,OFF,NW,IOR,IIG,JJG,KKG,NE,IJKA) BIND(C,NAME='fds_k_match')
INTEGER(C_INT), VALUE :: NM,NW,NE
INTEGER(C_INT), INTENT(IN) :: OFF(3)
REAL(C_DOUBLE), INTENT(IN) :: IOR(NW),IIG(NW),JJG(NW),KKG(NW),IJKA(NE,4)
TYPE(MESH_TYPE), POINTER :: M
INTEGER :: IW,IE,K,NBW,NBE
CALL FDS_HOOK_FINE_GUARD('fds_k_match',NM,NMESHES)
M => MESHES(NM)
NBW = M%N_EXTERNAL_WALL_CELLS+M%N_INTERNAL_WALL_CELLS
NBE = SIZE(M%EDGE)
IF (.NOT.ALLOCATED(MT)) ALLOCATE(MT(NMESHES))
IF (ALLOCATED(MT(NM)%W)) DEALLOCATE(MT(NM)%W)
IF (ALLOCATED(MT(NM)%E)) DEALLOCATE(MT(NM)%E)
ALLOCATE(MT(NM)%W(NBW),MT(NM)%E(NBE))
MT(NM)%W = 0 ; MT(NM)%E = 0 ; MT(NM)%NWD = NW ; MT(NM)%NED = NE
DO IW=1,NBW
   ASSOCIATE (BC=>M%BOUNDARY_COORD(M%WALL(IW)%BC_INDEX))
   IF (IW<=NW) THEN   ! fast path: same order (box = whole dump mesh)
      IF (NINT(IOR(IW))==BC%IOR .AND. NINT(IIG(IW))==BC%IIG+OFF(1) .AND. NINT(JJG(IW))==BC%JJG+OFF(2) .AND. NINT(KKG(IW))==BC%KKG+OFF(3)) THEN
         MT(NM)%W(IW) = IW ; CYCLE
      ENDIF
   ENDIF
   DO K=1,NW
      IF (NINT(IOR(K))==BC%IOR .AND. NINT(IIG(K))==BC%IIG+OFF(1) .AND. NINT(JJG(K))==BC%JJG+OFF(2) .AND. NINT(KKG(K))==BC%KKG+OFF(3)) THEN
         MT(NM)%W(IW) = K ; EXIT
      ENDIF
   ENDDO
   END ASSOCIATE
ENDDO
DO IE=1,NBE
   IF (IE<=NE) THEN
      IF (NINT(IJKA(IE,1))==M%EDGE(IE)%I+OFF(1) .AND. NINT(IJKA(IE,2))==M%EDGE(IE)%J+OFF(2) .AND. NINT(IJKA(IE,3))==M%EDGE(IE)%K+OFF(3) &
          .AND. NINT(IJKA(IE,4))==M%EDGE(IE)%AXIS) THEN
         MT(NM)%E(IE) = IE ; CYCLE
      ENDIF
   ENDIF
   DO K=1,NE
      IF (NINT(IJKA(K,1))==M%EDGE(IE)%I+OFF(1) .AND. NINT(IJKA(K,2))==M%EDGE(IE)%J+OFF(2) .AND. NINT(IJKA(K,3))==M%EDGE(IE)%K+OFF(3) &
          .AND. NINT(IJKA(K,4))==M%EDGE(IE)%AXIS) THEN
         MT(NM)%E(IE) = K ; EXIT
      ENDIF
   ENDDO
ENDDO
END SUBROUTINE FDS_K_MATCH


!> Interface walls of a split (WMATCH=0): make their boundary data neutral, so that the wall-correction terms of the kernels vanish (the
!> single-mesh run has no wall there): UVW_SAVE = own face velocity, RHO_F/TMP_F/ZZ_F = the adjacent cell values, U_NORMAL(_S) from the face.
!> Returns the number of walls treated.
FUNCTION FDS_K_NEUTRALIZE(NM) BIND(C,NAME='fds_k_neutralize') RESULT(NN)
INTEGER(C_INT), VALUE :: NM
INTEGER(C_INT) :: NN
TYPE(MESH_TYPE), POINTER :: M
INTEGER :: IW
REAL(EB) :: UN
CALL FDS_HOOK_FINE_GUARD('fds_k_neutralize',NM,NMESHES)
M => MESHES(NM)
NN = 0
IF (.NOT.ALLOCATED(MT)) RETURN
IF (.NOT.ALLOCATED(MT(NM)%W)) RETURN
DO IW=1,M%N_EXTERNAL_WALL_CELLS
   IF (MT(NM)%W(IW)/=0) CYCLE
   NN = NN+1
   ASSOCIATE (BC=>M%BOUNDARY_COORD(M%WALL(IW)%BC_INDEX),B1=>M%BOUNDARY_PROP1(M%WALL(IW)%B1_INDEX))
   IF (PREDICTOR) THEN   ! DENSITY restores the face velocity U (predictor) or US (corrector) from UVW_SAVE (mass.f90:426, 598)
      SELECT CASE(BC%IOR)
         CASE( 1) ; UN = M%U(BC%IIG-1,BC%JJG,BC%KKG)
         CASE(-1) ; UN = M%U(BC%IIG  ,BC%JJG,BC%KKG)
         CASE( 2) ; UN = M%V(BC%IIG,BC%JJG-1,BC%KKG)
         CASE(-2) ; UN = M%V(BC%IIG,BC%JJG  ,BC%KKG)
         CASE( 3) ; UN = M%W(BC%IIG,BC%JJG,BC%KKG-1)
         CASE(-3) ; UN = M%W(BC%IIG,BC%JJG,BC%KKG  )
      END SELECT
   ELSE
      SELECT CASE(BC%IOR)
         CASE( 1) ; UN = M%US(BC%IIG-1,BC%JJG,BC%KKG)
         CASE(-1) ; UN = M%US(BC%IIG  ,BC%JJG,BC%KKG)
         CASE( 2) ; UN = M%VS(BC%IIG,BC%JJG-1,BC%KKG)
         CASE(-2) ; UN = M%VS(BC%IIG,BC%JJG  ,BC%KKG)
         CASE( 3) ; UN = M%WS(BC%IIG,BC%JJG,BC%KKG-1)
         CASE(-3) ; UN = M%WS(BC%IIG,BC%JJG,BC%KKG  )
      END SELECT
   ENDIF
   M%WALL(IW)%BOUNDARY_TYPE = NULL_BOUNDARY   ! in the single mesh this face is interior: no wall, so the kernels must skip it (they all CYCLE on NULL_BOUNDARY)
   M%CELL(M%CELL_INDEX(BC%IIG,BC%JJG,BC%KKG))%WALL_INDEX(-BC%IOR) = 0   ! and the cell face is not a wall face (DIVERGENCE_PART_1 tests CELL%WALL_INDEX==0)
   M%UVW_SAVE(IW) = UN
   B1%RHO_F = M%RHO(BC%IIG,BC%JJG,BC%KKG)
   B1%TMP_F = M%TMP(BC%IIG,BC%JJG,BC%KKG)
   B1%ZZ_F(1:N_TOTAL_SCALARS) = M%ZZ(BC%IIG,BC%JJG,BC%KKG,1:N_TOTAL_SCALARS)
   END ASSOCIATE
ENDDO
END FUNCTION FDS_K_NEUTRALIZE


!> Load (MODE=0), compare bitwise (MODE=1) or query the allocation bounds into LB/UB (MODE=2) of array NAME of box NM. DATA holds the dump array with bounds LB:UB (dump index space shifted by
!> OFF: box index I corresponds to dump index I+OFF in the dimensions with a cell/face index; the shift is applied by the caller for
!> the 3-D/4-D field arrays through LB/UB already given in BOX indices). Walls/edges (W_*, E_*) use the WMATCH/EMATCH tables.
!> Region: the box indices LB:UB (or their intersection with the allocated bounds). Returns the number of elements loaded/compared, and
!> NBAD = number of bitwise-different elements (MODE=1); IERR/=0: name unknown or array not allocated.
!> The elements of the region OMIT(1:3) (lower/upper cut, see the caller) are the caller's business: this routine treats LB:UB only.
SUBROUTINE FDS_K_XFER(NM,NAME,RNK,LB,UB,DATA,MODE,NCNT,NBAD,IERR) BIND(C,NAME='fds_k_xfer')
INTEGER(C_INT), VALUE :: NM,RNK,MODE
CHARACTER(KIND=C_CHAR), INTENT(IN) :: NAME(*)
INTEGER(C_INT), INTENT(INOUT) :: LB(4),UB(4)
REAL(C_DOUBLE), INTENT(INOUT) :: DATA(*)
INTEGER(C_LONG), INTENT(OUT) :: NCNT,NBAD
INTEGER(C_INT), INTENT(OUT) :: IERR
TYPE(MESH_TYPE), POINTER :: M
REAL(EB), POINTER :: P1(:),P2(:,:),P3(:,:,:),P4(:,:,:,:)
CHARACTER(LEN=32) :: NM_
INTEGER :: I
CALL FDS_HOOK_FINE_GUARD('fds_k_xfer',NM,NMESHES)
NCNT = 0 ; NBAD = 0 ; IERR = 0
M => MESHES(NM)
NM_ = ' '
DO I=1,32
   IF (NAME(I)==C_NULL_CHAR) EXIT
   NM_(I:I) = NAME(I)
ENDDO
NULLIFY(P1,P2,P3,P4)
SELECT CASE(TRIM(NM_))
   CASE('RHO') ; IF (ALLOCATED(M%RHO)) P3=>M%RHO
   CASE('RHOS') ; IF (ALLOCATED(M%RHOS)) P3=>M%RHOS
   CASE('TMP') ; IF (ALLOCATED(M%TMP)) P3=>M%TMP
   CASE('U') ; IF (ALLOCATED(M%U)) P3=>M%U
   CASE('V') ; IF (ALLOCATED(M%V)) P3=>M%V
   CASE('W') ; IF (ALLOCATED(M%W)) P3=>M%W
   CASE('US') ; IF (ALLOCATED(M%US)) P3=>M%US
   CASE('VS') ; IF (ALLOCATED(M%VS)) P3=>M%VS
   CASE('WS') ; IF (ALLOCATED(M%WS)) P3=>M%WS
   CASE('H') ; IF (ALLOCATED(M%H)) P3=>M%H
   CASE('HS') ; IF (ALLOCATED(M%HS)) P3=>M%HS
   CASE('KRES') ; IF (ALLOCATED(M%KRES)) P3=>M%KRES
   CASE('D') ; IF (ALLOCATED(M%D)) P3=>M%D
   CASE('DS') ; IF (ALLOCATED(M%DS)) P3=>M%DS
   CASE('DDDT') ; IF (ALLOCATED(M%DDDT)) P3=>M%DDDT
   CASE('MU') ; IF (ALLOCATED(M%MU)) P3=>M%MU
   CASE('MU_DNS') ; IF (ALLOCATED(M%MU_DNS)) P3=>M%MU_DNS
   CASE('RSUM') ; IF (ALLOCATED(M%RSUM)) P3=>M%RSUM
   CASE('FVX') ; IF (ALLOCATED(M%FVX)) P3=>M%FVX
   CASE('FVY') ; IF (ALLOCATED(M%FVY)) P3=>M%FVY
   CASE('FVZ') ; IF (ALLOCATED(M%FVZ)) P3=>M%FVZ
   CASE('STRAIN_RATE') ; IF (ALLOCATED(M%STRAIN_RATE)) P3=>M%STRAIN_RATE
   CASE('D_Z_MAX') ; IF (ALLOCATED(M%D_Z_MAX)) P3=>M%D_Z_MAX
   CASE('WORK1') ; IF (ALLOCATED(M%WORK1)) P3=>M%WORK1
   CASE('WORK2') ; IF (ALLOCATED(M%WORK2)) P3=>M%WORK2
   CASE('WORK3') ; IF (ALLOCATED(M%WORK3)) P3=>M%WORK3
   CASE('WORK4') ; IF (ALLOCATED(M%WORK4)) P3=>M%WORK4
   CASE('WORK5') ; IF (ALLOCATED(M%WORK5)) P3=>M%WORK5
   CASE('WORK6') ; IF (ALLOCATED(M%WORK6)) P3=>M%WORK6
   CASE('WORK7') ; IF (ALLOCATED(M%WORK7)) P3=>M%WORK7
   CASE('WORK8') ; IF (ALLOCATED(M%WORK8)) P3=>M%WORK8
   CASE('WORK9') ; IF (ALLOCATED(M%WORK9)) P3=>M%WORK9
   CASE('SWORK1') ; IF (ALLOCATED(M%SWORK1)) P4=>M%SWORK1
   CASE('SWORK2') ; IF (ALLOCATED(M%SWORK2)) P4=>M%SWORK2
   CASE('SWORK3') ; IF (ALLOCATED(M%SWORK3)) P4=>M%SWORK3
   CASE('RDX') ; IF (ALLOCATED(M%RDX)) P1=>M%RDX
   CASE('RDY') ; IF (ALLOCATED(M%RDY)) P1=>M%RDY
   CASE('RDZ') ; IF (ALLOCATED(M%RDZ)) P1=>M%RDZ
   CASE('RDXN') ; IF (ALLOCATED(M%RDXN)) P1=>M%RDXN
   CASE('RDYN') ; IF (ALLOCATED(M%RDYN)) P1=>M%RDYN
   CASE('RDZN') ; IF (ALLOCATED(M%RDZN)) P1=>M%RDZN
   CASE('R') ; IF (ALLOCATED(M%R)) P1=>M%R
   CASE('RRN') ; IF (ALLOCATED(M%RRN)) P1=>M%RRN
   CASE('MU_RSQMW_Z') ; IF (ALLOCATED(MU_RSQMW_Z)) CALL XT2(MU_RSQMW_Z) ; RETURN
   CASE('K_RSQMW_Z') ; IF (ALLOCATED(K_RSQMW_Z)) CALL XT2(K_RSQMW_Z) ; RETURN
   CASE('CP_Z') ; IF (ALLOCATED(CP_Z)) CALL XT2(CP_Z) ; RETURN
   CASE('H_SENS_Z') ; IF (ALLOCATED(H_SENS_Z)) CALL XT2(H_SENS_Z) ; RETURN
   CASE('RSQ_MW_Z') ; IF (ALLOCATED(RSQ_MW_Z)) CALL XT1(RSQ_MW_Z) ; RETURN
   CASE('MW') ; CALL XMW ; RETURN   ! SPECIES_MIXTURE(1:N_SPECIES)%MW (read or compare only)
   CASE('MWR_Z') ; IF (ALLOCATED(MWR_Z)) CALL XT1(MWR_Z) ; RETURN
   CASE('ZZ') ; IF (ALLOCATED(M%ZZ)) P4=>M%ZZ
   CASE('ZZS') ; IF (ALLOCATED(M%ZZS)) P4=>M%ZZS
   CASE('DEL_RHO_D_DEL_Z') ; IF (ALLOCATED(M%DEL_RHO_D_DEL_Z)) P4=>M%DEL_RHO_D_DEL_Z
   CASE('SWORK4') ; IF (ALLOCATED(M%SWORK4)) P4=>M%SWORK4
   CASE('FX') ; IF (ALLOCATED(M%FX)) P4=>M%FX
   CASE('FY') ; IF (ALLOCATED(M%FY)) P4=>M%FY
   CASE('FZ') ; IF (ALLOCATED(M%FZ)) P4=>M%FZ
   CASE('DSUM') ; IF (ALLOCATED(DSUM)) CALL XSUM(DSUM) ; RETURN
   CASE('USUM') ; IF (ALLOCATED(USUM)) CALL XSUM(USUM) ; RETURN
   CASE('PSUM') ; IF (ALLOCATED(PSUM)) CALL XSUM(PSUM) ; RETURN
   CASE('PBAR') ; IF (ALLOCATED(M%PBAR)) P2=>M%PBAR
   CASE('PBAR_S') ; IF (ALLOCATED(M%PBAR_S)) P2=>M%PBAR_S
   CASE('D_PBAR_DT') ; IF (ALLOCATED(M%D_PBAR_DT)) P1=>M%D_PBAR_DT
   CASE('D_PBAR_DT_S') ; IF (ALLOCATED(M%D_PBAR_DT_S)) P1=>M%D_PBAR_DT_S
   CASE DEFAULT
      IF (NM_(1:2)=='W_') THEN ; CALL XFER_WALL(TRIM(NM_),MODE,DATA,NCNT,NBAD,IERR) ; RETURN ; ENDIF
      IF (NM_(1:2)=='E_') THEN ; CALL XFER_EDGE(TRIM(NM_),MODE,DATA,NCNT,NBAD,IERR) ; RETURN ; ENDIF
      IERR = 1 ; RETURN
END SELECT
IF (MODE==2) THEN   ! query: bounds of the allocation in LB/UB
   IERR = 2
   IF (ASSOCIATED(P3)) THEN ; LB(1:3)=LBOUND(P3) ; UB(1:3)=UBOUND(P3) ; IERR=0 ; ENDIF
   IF (ASSOCIATED(P4)) THEN ; LB(1:4)=LBOUND(P4) ; UB(1:4)=UBOUND(P4) ; IERR=0 ; ENDIF
   IF (ASSOCIATED(P2)) THEN ; LB(1:2)=LBOUND(P2) ; UB(1:2)=UBOUND(P2) ; IERR=0 ; ENDIF
   IF (ASSOCIATED(P1)) THEN ; LB(1:1)=LBOUND(P1) ; UB(1:1)=UBOUND(P1) ; IERR=0 ; ENDIF
   RETURN
ENDIF
IF (RNK==3 .AND. ASSOCIATED(P3)) THEN
   CALL X3(P3)
ELSEIF (RNK==4 .AND. ASSOCIATED(P4)) THEN
   CALL X4(P4)
ELSEIF (RNK==2 .AND. ASSOCIATED(P2)) THEN
   CALL X2(P2)
ELSEIF (RNK==1 .AND. ASSOCIATED(P1)) THEN
   CALL X1(P1)
ELSE
   IERR = 2   ! not allocated (or rank mismatch)
ENDIF

CONTAINS

SUBROUTINE XMW
USE TYPES, ONLY: SPECIES_MIXTURE
INTEGER :: I
IF (MODE==2) THEN ; LB(1)=1 ; UB(1)=SIZE(SPECIES_MIXTURE) ; IERR=0 ; RETURN ; ENDIF
DO I=LB(1),UB(1)
   IF (I<1 .OR. I>SIZE(SPECIES_MIXTURE)) THEN ; IERR = 3 ; RETURN ; ENDIF
   NCNT = NCNT+1
   IF (MODE==MODE_READ) THEN ; DATA(I-LB(1)+1) = SPECIES_MIXTURE(I)%MW ; ELSEIF (MODE==MODE_CMP) THEN ; IF (DIFF(SPECIES_MIXTURE(I)%MW,DATA(I-LB(1)+1))) NBAD = NBAD+1 ; ENDIF
ENDDO
END SUBROUTINE XMW

SUBROUTINE XT1(A)   !< 1-D species tables (module arrays)
REAL(EB), ALLOCATABLE, INTENT(INOUT) :: A(:)
INTEGER :: I
IF (MODE==2) THEN ; LB(1)=LBOUND(A,1) ; UB(1)=UBOUND(A,1) ; IERR=0 ; RETURN ; ENDIF
DO I=LB(1),UB(1)
   IF (I<LBOUND(A,1) .OR. I>UBOUND(A,1)) THEN ; IERR = 3 ; RETURN ; ENDIF
   NCNT = NCNT+1
   IF (MODE==MODE_LOAD) THEN ; A(I) = DATA(I-LB(1)+1) ; ELSEIF (MODE==MODE_READ) THEN ; DATA(I-LB(1)+1) = A(I) ; ELSE ; IF (DIFF(A(I),DATA(I-LB(1)+1))) NBAD = NBAD+1 ; ENDIF
ENDDO
END SUBROUTINE XT1

SUBROUTINE XT2(A)   !< species tables CP_Z(0:I_MAX_TEMP,N_SPECIES) etc. (module arrays; LB/UB in the table's own indices)
REAL(EB), ALLOCATABLE, INTENT(INOUT) :: A(:,:)
INTEGER :: I,J
INTEGER(C_LONG) :: IDX
IF (MODE==2) THEN ; LB(1:2)=LBOUND(A) ; UB(1:2)=UBOUND(A) ; IERR=0 ; RETURN ; ENDIF
DO J=LB(2),UB(2) ; DO I=LB(1),UB(1)
   IDX = (I-LB(1)) + INT(UB(1)-LB(1)+1,C_LONG)*(J-LB(2)) + 1
   IF (I<LBOUND(A,1) .OR. I>UBOUND(A,1) .OR. J<LBOUND(A,2) .OR. J>UBOUND(A,2)) THEN ; IERR = 3 ; RETURN ; ENDIF
   NCNT = NCNT+1
   IF (MODE==MODE_LOAD) THEN ; A(I,J) = DATA(IDX) ; ELSEIF (MODE==MODE_READ) THEN ; DATA(IDX) = A(I,J) ; ELSE ; IF (DIFF(A(I,J),DATA(IDX))) NBAD = NBAD+1 ; ENDIF
ENDDO ; ENDDO
END SUBROUTINE XT2

SUBROUTINE XSUM(A)   !< zone sums of the divergence (global arrays 1:N_ZONE)
REAL(EB), INTENT(INOUT) :: A(:)
INTEGER :: I
IF (MODE==2) THEN ; LB(1)=1 ; UB(1)=SIZE(A) ; IERR=0 ; RETURN ; ENDIF
DO I=LB(1),UB(1)
   IF (I<1 .OR. I>SIZE(A)) THEN ; IERR = 3 ; RETURN ; ENDIF
   NCNT = NCNT+1
   IF (MODE==MODE_LOAD) THEN ; A(I) = DATA(I-LB(1)+1) ; ELSEIF (MODE==MODE_READ) THEN ; DATA(I-LB(1)+1) = A(I) ; ELSE ; IF (DIFF(A(I),DATA(I-LB(1)+1))) NBAD = NBAD+1 ; ENDIF
ENDDO
END SUBROUTINE XSUM

LOGICAL FUNCTION DIFF(A,B)
REAL(EB), INTENT(IN) :: A,B
DIFF = TRANSFER(A,0_C_LONG)/=TRANSFER(B,0_C_LONG)
END FUNCTION DIFF

SUBROUTINE X3(P)
REAL(EB), POINTER, INTENT(IN) :: P(:,:,:)
INTEGER :: I,J,K
INTEGER(C_LONG) :: IDX
DO K=LB(3),UB(3) ; DO J=LB(2),UB(2) ; DO I=LB(1),UB(1)
   IDX = (I-LB(1)) + INT(UB(1)-LB(1)+1,C_LONG)*((J-LB(2)) + INT(UB(2)-LB(2)+1,C_LONG)*(K-LB(3))) + 1
   IF (I<LBOUND(P,1) .OR. I>UBOUND(P,1) .OR. J<LBOUND(P,2) .OR. J>UBOUND(P,2) .OR. K<LBOUND(P,3) .OR. K>UBOUND(P,3)) THEN ; IERR = 3 ; RETURN ; ENDIF
   NCNT = NCNT+1
   IF (MODE==MODE_LOAD) THEN ; P(I,J,K) = DATA(IDX) ; ELSEIF (MODE==MODE_READ) THEN ; DATA(IDX) = P(I,J,K) ; ELSE ; IF (DIFF(P(I,J,K),DATA(IDX))) THEN ; NBAD = NBAD+1 ; IF (NBAD<=8 .AND. VERBOSE_DIFF) WRITE(0,'(A,3I4,2ES24.16)') '   first difference at',I,J,K,P(I,J,K),DATA(IDX) ; ENDIF ; ENDIF
ENDDO ; ENDDO ; ENDDO
END SUBROUTINE X3

SUBROUTINE X4(P)
REAL(EB), POINTER, INTENT(IN) :: P(:,:,:,:)
INTEGER :: I,J,K,L
INTEGER(C_LONG) :: IDX,E1,E2,E3
E1 = UB(1)-LB(1)+1 ; E2 = UB(2)-LB(2)+1 ; E3 = UB(3)-LB(3)+1
DO L=LB(4),UB(4) ; DO K=LB(3),UB(3) ; DO J=LB(2),UB(2) ; DO I=LB(1),UB(1)
   IDX = (I-LB(1)) + E1*((J-LB(2)) + E2*((K-LB(3)) + E3*(L-LB(4)))) + 1
   IF (I<LBOUND(P,1) .OR. I>UBOUND(P,1) .OR. J<LBOUND(P,2) .OR. J>UBOUND(P,2) .OR. K<LBOUND(P,3) .OR. K>UBOUND(P,3) .OR. &
       L<LBOUND(P,4) .OR. L>UBOUND(P,4)) THEN ; IERR = 3 ; RETURN ; ENDIF
   NCNT = NCNT+1
   IF (MODE==MODE_LOAD) THEN ; P(I,J,K,L) = DATA(IDX) ; ELSEIF (MODE==MODE_READ) THEN ; DATA(IDX) = P(I,J,K,L) ; ELSE ; IF (DIFF(P(I,J,K,L),DATA(IDX))) THEN ; NBAD = NBAD+1 ; IF (NBAD<=8 .AND. VERBOSE_DIFF) WRITE(0,'(A,4I4,2ES24.16)') '   first difference at',I,J,K,L,P(I,J,K,L),DATA(IDX) ; ENDIF ; ENDIF
ENDDO ; ENDDO ; ENDDO ; ENDDO
END SUBROUTINE X4

SUBROUTINE X2(P)
REAL(EB), POINTER, INTENT(IN) :: P(:,:)
INTEGER :: I,J
INTEGER(C_LONG) :: IDX
DO J=LB(2),UB(2) ; DO I=LB(1),UB(1)
   IDX = (I-LB(1)) + INT(UB(1)-LB(1)+1,C_LONG)*(J-LB(2)) + 1
   IF (I<LBOUND(P,1) .OR. I>UBOUND(P,1) .OR. J<LBOUND(P,2) .OR. J>UBOUND(P,2)) THEN ; IERR = 3 ; RETURN ; ENDIF
   NCNT = NCNT+1
   IF (MODE==MODE_LOAD) THEN ; P(I,J) = DATA(IDX) ; ELSEIF (MODE==MODE_READ) THEN ; DATA(IDX) = P(I,J) ; ELSE ; IF (DIFF(P(I,J),DATA(IDX))) NBAD = NBAD+1 ; ENDIF
ENDDO ; ENDDO
END SUBROUTINE X2

SUBROUTINE X1(P)
REAL(EB), POINTER, INTENT(IN) :: P(:)
INTEGER :: I
DO I=LB(1),UB(1)
   IF (I<LBOUND(P,1) .OR. I>UBOUND(P,1)) THEN ; IERR = 3 ; RETURN ; ENDIF
   NCNT = NCNT+1
   IF (MODE==MODE_LOAD) THEN ; P(I) = DATA(I-LB(1)+1) ; ELSEIF (MODE==MODE_READ) THEN ; DATA(I-LB(1)+1) = P(I) ; ELSE ; IF (DIFF(P(I),DATA(I-LB(1)+1))) NBAD = NBAD+1 ; ENDIF
ENDDO
END SUBROUTINE X1

SUBROUTINE ONE(X,D)
REAL(EB), INTENT(INOUT) :: X
REAL(C_DOUBLE), INTENT(IN) :: D
NCNT = NCNT+1
IF (MODE==MODE_LOAD) THEN ; X = D ; ELSE ; IF (DIFF(X,D)) NBAD = NBAD+1 ; ENDIF
END SUBROUTINE ONE

SUBROUTINE CMPONLY(X,D)
REAL(EB), INTENT(IN) :: X
REAL(C_DOUBLE), INTENT(IN) :: D
NCNT = NCNT+1
IF (DIFF(X,D)) NBAD = NBAD+1
END SUBROUTINE CMPONLY

!> wall arrays: DATA is the dump array (length NWD, or NWD x NS for W_ZZ_F, W_RHO_D_F, W_RHO_D_DZDN_F); only walls with a counterpart
SUBROUTINE XFER_WALL(NAME_W,MODE_W,DATA_W,NC,NB,IE)
CHARACTER(*), INTENT(IN) :: NAME_W
INTEGER, INTENT(IN) :: MODE_W
REAL(C_DOUBLE), INTENT(INOUT) :: DATA_W(*)
INTEGER(C_LONG), INTENT(INOUT) :: NC,NB
INTEGER(C_INT), INTENT(INOUT) :: IE
INTEGER :: IW,KD,N,NSC
REAL(EB) :: V
LOGICAL :: PER_SCALAR
IF (.NOT.ALLOCATED(MT)) THEN ; IE = 4 ; RETURN ; ENDIF
IF (.NOT.ALLOCATED(MT(NM)%W)) THEN ; IE = 4 ; RETURN ; ENDIF
NSC = N_TOTAL_SCALARS
PER_SCALAR = (NAME_W=='W_ZZ_F' .OR. NAME_W=='W_RHO_D_F' .OR. NAME_W=='W_RHO_D_DZDN_F')
DO IW=1,SIZE(MT(NM)%W)
   KD = MT(NM)%W(IW)
   IF (KD==0) CYCLE
   ASSOCIATE (BC=>M%BOUNDARY_COORD(M%WALL(IW)%BC_INDEX),B1=>M%BOUNDARY_PROP1(M%WALL(IW)%B1_INDEX))
   IF (PER_SCALAR) THEN
      DO N=1,NSC
         SELECT CASE(NAME_W)
            CASE('W_ZZ_F') ; CALL ONE(B1%ZZ_F(N),DATA_W(KD+MT(NM)%NWD*(N-1)))
            CASE('W_RHO_D_F') ; CALL ONE(B1%RHO_D_F(N),DATA_W(KD+MT(NM)%NWD*(N-1)))
            CASE('W_RHO_D_DZDN_F') ; CALL ONE(B1%RHO_D_DZDN_F(N),DATA_W(KD+MT(NM)%NWD*(N-1)))
         END SELECT
      ENDDO
   ELSE
      SELECT CASE(NAME_W)
         CASE('W_UVW_SAVE') ; IF (IW<=M%N_EXTERNAL_WALL_CELLS) CALL ONE(M%UVW_SAVE(IW),DATA_W(KD))
         CASE('W_U_NORMAL') ; CALL ONE(B1%U_NORMAL,DATA_W(KD))
         CASE('W_U_NORMAL_S') ; CALL ONE(B1%U_NORMAL_S,DATA_W(KD))
         CASE('W_RHO_F') ; CALL ONE(B1%RHO_F,DATA_W(KD))
         CASE('W_TMP_F') ; CALL ONE(B1%TMP_F,DATA_W(KD))
         CASE('W_K_G') ; CALL ONE(B1%K_G,DATA_W(KD))
         CASE('W_Q_CON_F') ; CALL ONE(B1%Q_CON_F,DATA_W(KD))
         CASE('W_Q_LEAK') ; CALL ONE(B1%Q_LEAK,DATA_W(KD))
         CASE('W_U_GHOST') ; IF (IW<=M%N_EXTERNAL_WALL_CELLS) CALL ONE(M%U_GHOST(IW),DATA_W(KD))
         CASE('W_V_GHOST') ; IF (IW<=M%N_EXTERNAL_WALL_CELLS) CALL ONE(M%V_GHOST(IW),DATA_W(KD))
         CASE('W_W_GHOST') ; IF (IW<=M%N_EXTERNAL_WALL_CELLS) CALL ONE(M%W_GHOST(IW),DATA_W(KD))
         CASE('W_IOR') ; V = REAL(BC%IOR,EB) ; CALL CMPONLY(V,DATA_W(KD))
         CASE('W_IIG','W_JJG','W_KKG') ; CONTINUE   ! identification only (shifted by the box origin in a split)
         CASE DEFAULT ; IE = 5 ; RETURN
      END SELECT
   ENDIF
   END ASSOCIATE
ENDDO
END SUBROUTINE XFER_WALL

!> edge arrays: E_OMEGA, E_TAU (NED x 5, index -2..2 in columns 1..5)
SUBROUTINE XFER_EDGE(NAME_E,MODE_E,DATA_E,NC,NB,IE)
CHARACTER(*), INTENT(IN) :: NAME_E
INTEGER, INTENT(IN) :: MODE_E
REAL(C_DOUBLE), INTENT(INOUT) :: DATA_E(*)
INTEGER(C_LONG), INTENT(INOUT) :: NC,NB
INTEGER(C_INT), INTENT(INOUT) :: IE
INTEGER :: IED,KD,L
IF (.NOT.ALLOCATED(MT)) THEN ; IE = 4 ; RETURN ; ENDIF
IF (.NOT.ALLOCATED(MT(NM)%E)) THEN ; IE = 4 ; RETURN ; ENDIF
IF (NAME_E=='E_IJKA') RETURN
IF (NAME_E/='E_OMEGA' .AND. NAME_E/='E_TAU') THEN ; IE = 5 ; RETURN ; ENDIF
IF (MODE_E==MODE_LOAD) THEN   ! start from the FDS default (unset) so that edges without a counterpart stay "unset"
   DO IED=1,SIZE(MT(NM)%E)
      IF (NAME_E=='E_OMEGA') THEN ; M%EDGE(IED)%OMEGA = -1.E6_EB ; ELSE ; M%EDGE(IED)%TAU = -1.E6_EB ; ENDIF
   ENDDO
ENDIF
DO IED=1,SIZE(MT(NM)%E)
   KD = MT(NM)%E(IED)
   IF (KD==0) CYCLE
   DO L=-2,2
      NC = NC+1
      IF (NAME_E=='E_OMEGA') THEN
         IF (MODE_E==MODE_LOAD) THEN ; M%EDGE(IED)%OMEGA(L) = DATA_E(KD+MT(NM)%NED*(L+2)) ; ELSEIF (DIFF(M%EDGE(IED)%OMEGA(L),DATA_E(KD+MT(NM)%NED*(L+2)))) THEN ; NB = NB+1 ; ENDIF
      ELSE
         IF (MODE_E==MODE_LOAD) THEN ; M%EDGE(IED)%TAU(L) = DATA_E(KD+MT(NM)%NED*(L+2)) ; ELSEIF (DIFF(M%EDGE(IED)%TAU(L),DATA_E(KD+MT(NM)%NED*(L+2)))) THEN ; NB = NB+1 ; ENDIF
      ENDIF
   ENDDO
ENDDO
END SUBROUTINE XFER_EDGE

END SUBROUTINE FDS_K_XFER

END MODULE FDS_KERNELS
