!> \brief bind(C) wrappers of the S5 time loop (M2a): the pieces of PRESSURE_ITERATION_SCHEME / MAIN_LOOP that are Fortran-owned state or unmodified FDS routines,
!> and the state getters the C++ time loop needs. Nothing here changes FDS data except through the unmodified FDS routines it calls, the pressure step
!> (H ghost assignment copied from PRESSURE_SOLVER_FFT, the part that follows the Poisson solve) and the divergence integrals (DSUM, PSUM, USUM).
!>
!> Kernel-facing file rules (M2a):
!> (a) Passive scalars (N_TOTAL_SCALARS beyond the tracked species) are handled by Fields.cpp: ZZ/ZZS carry ncomp=N_TOTAL_SCALARS as the last extent; the copy-out
!>     here passes that extent through, whatever its size.
!> (b) Only uniform Cartesian metrics are used; R(I)/RRN(I) are not involved (CYLINDRICAL and TRN* meshes are rejected at level-0 assembly, IR-002, and the
!>     time loop rejects CYLINDRICAL).
!> Scope of the time loop that these wrappers serve (TimeLoop.cpp): gas phase only, FFT pressure flag, no complex geometry, HVAC, radiation, particles, reactions,
!> level set, tunnel preconditioner. FDS_P_PARAMS returns the flags so that the driver can refuse a case outside this scope.
!> Boundary table entries: README.md, "Fortran/C++ boundary".
MODULE FDS_STEP

USE ISO_C_BINDING
USE PRECISION_PARAMETERS, ONLY: EB
USE GLOBAL_CONSTANTS
USE MESH_VARIABLES, ONLY: MESHES,MESH_TYPE
USE TYPES, ONLY: P_ZONE
USE OUTPUT_CLOCKS, ONLY: MMS_TIMER
USE PRES, ONLY: PRESSURE_SOLVER_COMPUTE_RHS,PRESSURE_SOLVER_CHECK_RESIDUALS,COMPUTE_VELOCITY_ERROR
USE VELO, ONLY: NO_FLUX,BAROCLINIC_CORRECTION
USE MASS, ONLY: MASS_FINITE_DIFFERENCES,DENSITY
USE FDS_DENSITY_SPLIT, ONLY: DENSITY_PRE_CLIP

IMPLICIT NONE (TYPE,EXTERNAL)
PRIVATE

PUBLIC :: FDS_P_PARAMS,FDS_P_MESH_INFO,FDS_P_GET,FDS_P_MFD,FDS_P_DENS,FDS_P_DENS_PRE,FDS_P_INIT_DIV,FDS_P_ZONE_GET,FDS_P_ZONE_SET,FDS_P_ZONE_TERMS,&
          FDS_P_ZONE_VOLUME_TERMS,FDS_P_ZONE_VOLUME,FDS_P_ZONE_VOLUME_SET,FDS_P_VENT_COUNT,FDS_P_VENT_GET,FDS_P_ITER_INIT,FDS_P_ITER_INC,FDS_P_ITER_BARO,FDS_P_SET_ITER_BARO,&
          FDS_P_BAROCLINIC,FDS_P_NOFLUX,FDS_P_RHS,FDS_P_GET_PRHS,FDS_P_BMAX,FDS_P_H_GHOST,FDS_P_RESID,FDS_P_VELERR,FDS_P_GET_ERR,FDS_P_SET_WALL_COUNTER,&
          FDS_P_STOP_STATUS,FDS_P_CLEAR_ATTACHED,FDS_P_TOTAL_ITER,FDS_P_IFACE_WALLS,FDS_P_WALL_DUMP,FDS_P_SAVE_UVW,FDS_P_EDGE_DUMP

CONTAINS

!> Case flags and constants. IP(1:) integers, RP(1:) reals (layout documented in TimeLoop.cpp).
SUBROUTINE FDS_P_PARAMS(IP,RP) BIND(C,NAME='fds_p_params')
INTEGER(C_INT), INTENT(OUT) :: IP(32)
REAL(C_DOUBLE), INTENT(OUT) :: RP(8)
IP = 0
IP(1) = MERGE(1,0,ITERATE_PRESSURE)
IP(2) = MAX_PRESSURE_ITERATIONS
IP(3) = MAX_PREDICTOR_PRESSURE_ITERATIONS
IP(4) = MERGE(1,0,SUSPEND_PRESSURE_ITERATIONS)
IP(5) = MERGE(1,0,BAROCLINIC)
IP(6) = N_ZONE
IP(7) = PERIODIC_TEST
IP(8) = MERGE(1,0,CC_IBM)
IP(9) = MERGE(1,0,HVAC_SOLVE)
IP(10) = N_REACTIONS
IP(11) = MERGE(1,0,RADIATION)
IP(12) = LEVEL_SET_MODE
IP(13) = MERGE(1,0,TUNNEL_PRECONDITIONER)
IP(14) = MERGE(1,0,PRES_FLAG==FFT_FLAG)
IP(15) = MERGE(1,0,CYLINDRICAL)
IP(16) = MERGE(1,0,PARTICLE_DRAG)
IP(17) = MERGE(1,0,SOLID_HEAT_TRANSFER_3D)
IP(18) = N_LAGRANGIAN_CLASSES
IP(19) = MERGE(1,0,FREEZE_VELOCITY)
IP(20) = MERGE(1,0,SOLID_PHASE_ONLY)
IP(21) = MERGE(1,0,TWO_D)
IP(22) = WALL_INCREMENT
IP(23) = MERGE(1,0,MPI_PARTICLE_EXCHANGE)
IP(24) = MERGE(1,0,EXCHANGE_OBST_MASS)
IP(25) = N_AGGLOMERATION_SPECIES
IP(26) = MERGE(1,0,INIT_HRRPUV)
IP(27) = MERGE(1,0,TERRAIN_CASE)
IP(28) = MERGE(1,0,READ_EXTERNAL)
IP(29) = MERGE(1,0,SYNTHETIC_EDDY_METHOD)
IP(30) = N_TOTAL_SCALARS
IP(31) = N_TRACKED_SPECIES
IP(32) = N_VENT_TOTAL
RP(1) = PRESSURE_TOLERANCE
RP(2) = VELOCITY_TOLERANCE
RP(3) = MMS_TIMER
RP(4) = T_BEGIN
RP(5) = RHOMIN
RP(6) = RHOMAX
RP(7) = ITERATION_SUSPEND_FACTOR
RP(8) = T_END
END SUBROUTINE FDS_P_PARAMS

!> Per-mesh integers: 1-3 IBAR,JBAR,KBAR; 4-6 LBC,MBC,NBC; 7 IPS; 8 N_EXTERNAL+N_INTERNAL walls; 9 N_EXTERNAL walls; 10 N_VENT; 11-13 ITRN,JTRN,KTRN; RP 1-3 DX(1),DY(1),DZ(1)
SUBROUTINE FDS_P_MESH_INFO(NM,IP,RP) BIND(C,NAME='fds_p_mesh_info')
INTEGER(C_INT), VALUE :: NM
INTEGER(C_INT), INTENT(OUT) :: IP(16)
REAL(C_DOUBLE), INTENT(OUT) :: RP(4)
TYPE(MESH_TYPE), POINTER :: M
M => MESHES(NM)
IP = 0
IP(1) = M%IBAR ; IP(2) = M%JBAR ; IP(3) = M%KBAR
IP(4) = M%LBC ; IP(5) = M%MBC ; IP(6) = M%NBC ; IP(7) = M%IPS
IP(8) = M%N_EXTERNAL_WALL_CELLS+M%N_INTERNAL_WALL_CELLS ; IP(9) = M%N_EXTERNAL_WALL_CELLS ; IP(10) = M%N_VENT
IP(11) = M%ITRN ; IP(12) = M%JTRN ; IP(13) = M%KTRN
RP = 0._EB
RP(1) = M%DX(1) ; RP(2) = M%DY(1) ; RP(3) = M%DZ(1)
END SUBROUTINE FDS_P_MESH_INFO

!> Copy array NAME of mesh NM out, column-major with its own (FDS) bounds. NTOT = expected element count. IERR 1 unknown, 2 not allocated, 3 size mismatch.
SUBROUTINE FDS_P_GET(NM,NAME,BUF,NTOT,IERR) BIND(C,NAME='fds_p_get')
INTEGER(C_INT), VALUE :: NM
CHARACTER(KIND=C_CHAR), INTENT(IN) :: NAME(*)
REAL(C_DOUBLE), INTENT(OUT) :: BUF(*)
INTEGER(C_LONG), VALUE :: NTOT
INTEGER(C_INT), INTENT(OUT) :: IERR
TYPE(MESH_TYPE), POINTER :: M
CHARACTER(LEN=32) :: NM_
INTEGER :: I
M => MESHES(NM)
NM_ = ' '
DO I=1,32
   IF (NAME(I)==C_NULL_CHAR) EXIT
   NM_(I:I) = NAME(I)
ENDDO
IERR = 0
SELECT CASE(TRIM(NM_))
   CASE('RHO')  ; CALL C3(M%RHO)
   CASE('RHOS') ; CALL C3(M%RHOS)
   CASE('TMP')  ; CALL C3(M%TMP)
   CASE('U')    ; CALL C3(M%U)
   CASE('V')    ; CALL C3(M%V)
   CASE('W')    ; CALL C3(M%W)
   CASE('US')   ; CALL C3(M%US)
   CASE('VS')   ; CALL C3(M%VS)
   CASE('WS')   ; CALL C3(M%WS)
   CASE('H')    ; CALL C3(M%H)
   CASE('HS')   ; CALL C3(M%HS)
   CASE('KRES') ; CALL C3(M%KRES)
   CASE('D')    ; CALL C3(M%D)
   CASE('DS')   ; CALL C3(M%DS)
   CASE('DDDT') ; CALL C3(M%DDDT)
   CASE('MU')   ; CALL C3(M%MU)
   CASE('RSUM') ; CALL C3(M%RSUM)
   CASE('FVX')  ; CALL C3(M%FVX)
   CASE('FVY')  ; CALL C3(M%FVY)
   CASE('FVZ')  ; CALL C3(M%FVZ)
   CASE('ZZ')   ; CALL C4(M%ZZ)
   CASE('ZZS')  ; CALL C4(M%ZZS)
   CASE DEFAULT ; IERR = 1
END SELECT
CONTAINS
SUBROUTINE C3(A)
REAL(EB), ALLOCATABLE, INTENT(IN) :: A(:,:,:)
IF (.NOT.ALLOCATED(A)) THEN ; IERR = 2 ; RETURN ; ENDIF
IF (SIZE(A,KIND=C_LONG)/=NTOT) THEN ; IERR = 3 ; RETURN ; ENDIF
BUF(1:NTOT) = RESHAPE(A,(/NTOT/))
END SUBROUTINE C3
SUBROUTINE C4(A)
REAL(EB), ALLOCATABLE, INTENT(IN) :: A(:,:,:,:)
IF (.NOT.ALLOCATED(A)) THEN ; IERR = 2 ; RETURN ; ENDIF
IF (SIZE(A,KIND=C_LONG)/=NTOT) THEN ; IERR = 3 ; RETURN ; ENDIF
BUF(1:NTOT) = RESHAPE(A,(/NTOT/))
END SUBROUTINE C4
END SUBROUTINE FDS_P_GET

!> MASS_FINITE_DIFFERENCES(NM) alone (main.f90 COMPUTE_FINITE_DIFFERENCES_1/2). The FDS_K_DENS wrapper of S3 bundles it with DENSITY; the time loop
!> needs them apart because the CHANGE_TIME_STEP loop repeats DENSITY without repeating MASS_FINITE_DIFFERENCES.
SUBROUTINE FDS_P_MFD(NM) BIND(C,NAME='fds_p_mfd')
INTEGER(C_INT), VALUE :: NM
CALL MASS_FINITE_DIFFERENCES(NM)
END SUBROUTINE FDS_P_MFD

!> DENSITY(T,DT,NM) alone (unmodified; one box = the FDS per-mesh clip).
SUBROUTINE FDS_P_DENS(T,DT,NM) BIND(C,NAME='fds_p_dens')
REAL(C_DOUBLE), VALUE :: T,DT
INTEGER(C_INT), VALUE :: NM
CALL DENSITY(T,DT,NM)
END SUBROUTINE FDS_P_DENS

!> First half of the D-031 split DENSITY (up to the clip) alone; the second half is FDS_K_DENS_POST.
SUBROUTINE FDS_P_DENS_PRE(T,DT,NM) BIND(C,NAME='fds_p_dens_pre')
REAL(C_DOUBLE), VALUE :: T,DT
INTEGER(C_INT), VALUE :: NM
CALL DENSITY_PRE_CLIP(T,DT,NM)
END SUBROUTINE FDS_P_DENS_PRE

!> INITIALIZE_DIVERGENCE_INTEGRALS (main.f90:2055) without the obstruction-connection part (OBST_CREATED_OR_REMOVED is refused by the driver).
SUBROUTINE FDS_P_INIT_DIV() BIND(C,NAME='fds_p_init_div')
IF (ALLOCATED(USUM)) USUM = 0._EB
IF (ALLOCATED(PSUM)) PSUM = 0._EB
IF (ALLOCATED(DSUM)) DSUM = 0._EB
END SUBROUTINE FDS_P_INIT_DIV

SUBROUTINE FDS_P_ZONE_GET(N,D,P,U) BIND(C,NAME='fds_p_zone_get')
INTEGER(C_INT), VALUE :: N
REAL(C_DOUBLE), INTENT(OUT) :: D(*),P(*),U(*)
D(1:N) = DSUM(1:N) ; P(1:N) = PSUM(1:N) ; U(1:N) = USUM(1:N)
END SUBROUTINE FDS_P_ZONE_GET

SUBROUTINE FDS_P_ZONE_SET(N,D,P,U) BIND(C,NAME='fds_p_zone_set')
INTEGER(C_INT), VALUE :: N
REAL(C_DOUBLE), INTENT(IN) :: D(*),P(*),U(*)
DSUM(1:N) = D(1:N) ; PSUM(1:N) = P(1:N) ; USUM(1:N) = U(1:N)
END SUBROUTINE FDS_P_ZONE_SET

!> The per-cell and per-wall terms that DIVERGENCE_PART_1 adds to DSUM, PSUM, USUM (divg.f90, "IF_PRESSURE_ZONES"), with the same expressions and the same skip rules,
!> WITHOUT accumulating them: the driver sums them in fixed point (D-028, decomposition independent). Call right after DIVERGENCE_PART_1 of mesh NM (R_PBAR and WORK1=RTRM
!> are the ones that kernel left). CZONE(1:IBAR*JBAR*KBAR) (I fastest) is 0 for skipped cells; WZONE(1:NW) likewise for walls.
SUBROUTINE FDS_P_ZONE_TERMS(NM,CZONE,DTERM,PTERM,WZONE,WTERM) BIND(C,NAME='fds_p_zone_terms')
INTEGER(C_INT), VALUE :: NM
INTEGER(C_INT), INTENT(OUT) :: CZONE(*),WZONE(*)
REAL(C_DOUBLE), INTENT(OUT) :: DTERM(*),PTERM(*),WTERM(*)
TYPE(MESH_TYPE), POINTER :: M
REAL(EB), POINTER, DIMENSION(:,:,:) :: DP
REAL(EB) :: VC,VC1
INTEGER :: I,J,K,IPZ,IW,L
M => MESHES(NM)
IF (PREDICTOR) THEN ; DP => M%DS ; ELSE ; DP => M%D ; ENDIF
L = 0
DO K=1,M%KBAR
   DO J=1,M%JBAR
      VC1 = M%DY(J)*M%DZ(K)
      DO I=1,M%IBAR
         L = L+1
         CZONE(L) = 0 ; DTERM(L) = 0._EB ; PTERM(L) = 0._EB
         IF (M%INTERPOLATED_MESH(I,J,K)>0) CYCLE
         IPZ = M%PRESSURE_ZONE(I,J,K)
         IF (IPZ<1) CYCLE
         IF (M%CELL(M%CELL_INDEX(I,J,K))%SOLID) CYCLE
         VC = M%DX(I)*M%RC(I)*VC1
         CZONE(L) = IPZ
         DTERM(L) = VC*DP(I,J,K)
         PTERM(L) = VC*(M%R_PBAR(K,IPZ)*1._EB-M%WORK1(I,J,K))
      ENDDO
   ENDDO
ENDDO
DO IW=1,M%N_EXTERNAL_WALL_CELLS+M%N_INTERNAL_WALL_CELLS
   WZONE(IW) = 0 ; WTERM(IW) = 0._EB
   ASSOCIATE (WC=>M%WALL(IW),BC=>M%BOUNDARY_COORD(M%WALL(IW)%BC_INDEX),B1=>M%BOUNDARY_PROP1(M%WALL(IW)%B1_INDEX))
   IF (M%INTERPOLATED_MESH(BC%IIG,BC%JJG,BC%KKG)>0) CYCLE
   IPZ = B1%PRESSURE_ZONE
   IF (IPZ<1) CYCLE
   IF (WC%BOUNDARY_TYPE/=SOLID_BOUNDARY) CYCLE
   WZONE(IW) = IPZ
   IF (PREDICTOR) WTERM(IW) = B1%U_NORMAL_S*B1%AREA
   IF (CORRECTOR) WTERM(IW) = B1%U_NORMAL  *B1%AREA
   END ASSOCIATE
ENDDO
END SUBROUTINE FDS_P_ZONE_TERMS

!> Cell volume terms of the pressure-zone volume (main.f90, P_ZONE(IZ)%VOLUME): zone index (0 = not counted) and DX*RC*DY*DZ with the same expression.
SUBROUTINE FDS_P_ZONE_VOLUME_TERMS(NM,CZONE,VTERM) BIND(C,NAME='fds_p_zone_volume_terms')
INTEGER(C_INT), VALUE :: NM
INTEGER(C_INT), INTENT(OUT) :: CZONE(*)
REAL(C_DOUBLE), INTENT(OUT) :: VTERM(*)
TYPE(MESH_TYPE), POINTER :: M
INTEGER :: I,J,K,L,IZ
M => MESHES(NM)
L = 0
DO K=1,M%KBAR
   DO J=1,M%JBAR
      DO I=1,M%IBAR
         L = L+1
         CZONE(L) = 0 ; VTERM(L) = 0._EB
         IZ = M%PRESSURE_ZONE(I,J,K)
         IF (IZ==0) CYCLE
         IF (M%CELL(M%CELL_INDEX(I,J,K))%SOLID) CYCLE
         CZONE(L) = IZ
         VTERM(L) = M%DX(I)*M%RC(I)*M%DY(J)*M%DZ(K)
      ENDDO
   ENDDO
ENDDO
END SUBROUTINE FDS_P_ZONE_VOLUME_TERMS

SUBROUTINE FDS_P_ZONE_VOLUME_SET(IZ,V) BIND(C,NAME='fds_p_zone_volume_set')
INTEGER(C_INT), VALUE :: IZ
REAL(C_DOUBLE), VALUE :: V
P_ZONE(IZ)%VOLUME = V
END SUBROUTINE FDS_P_ZONE_VOLUME_SET

FUNCTION FDS_P_ZONE_VOLUME(IZ) BIND(C,NAME='fds_p_zone_volume') RESULT(V)
INTEGER(C_INT), VALUE :: IZ
REAL(C_DOUBLE) :: V
V = P_ZONE(IZ)%VOLUME
END FUNCTION FDS_P_ZONE_VOLUME

FUNCTION FDS_P_VENT_COUNT(NM) BIND(C,NAME='fds_p_vent_count') RESULT(N)
INTEGER(C_INT), VALUE :: NM
INTEGER(C_INT) :: N
N = MESHES(NM)%N_VENT
END FUNCTION FDS_P_VENT_COUNT

!> Vent NV of mesh NM: IP = I1,I2,J1,J2,K1,K2,IOR,TOTAL_INDEX,circular(1/0); RP = FDS_AREA, TOTAL_FDS_AREA (after EXCHANGE_VENT_AREA)
SUBROUTINE FDS_P_VENT_GET(NM,NV,IP,RP) BIND(C,NAME='fds_p_vent_get')
INTEGER(C_INT), VALUE :: NM,NV
INTEGER(C_INT), INTENT(OUT) :: IP(9)
REAL(C_DOUBLE), INTENT(OUT) :: RP(2)
ASSOCIATE (VT=>MESHES(NM)%VENTS(NV))
IP = (/VT%I1,VT%I2,VT%J1,VT%J2,VT%K1,VT%K2,VT%IOR,VT%TOTAL_INDEX,MERGE(1,0,VT%RADIUS>0._EB)/)
RP = (/VT%FDS_AREA,VT%TOTAL_FDS_AREA/)
END ASSOCIATE
END SUBROUTINE FDS_P_VENT_GET

!> Start of PRESSURE_ITERATION_SCHEME: counters and the baroclinic-iteration flag.
SUBROUTINE FDS_P_ITER_INIT() BIND(C,NAME='fds_p_iter_init')
PRESSURE_ITERATIONS = 0
ITERATE_BAROCLINIC_TERM = BAROCLINIC
END SUBROUTINE FDS_P_ITER_INIT

SUBROUTINE FDS_P_ITER_INC() BIND(C,NAME='fds_p_iter_inc')
PRESSURE_ITERATIONS = PRESSURE_ITERATIONS+1
TOTAL_PRESSURE_ITERATIONS = TOTAL_PRESSURE_ITERATIONS+1
END SUBROUTINE FDS_P_ITER_INC

FUNCTION FDS_P_TOTAL_ITER() BIND(C,NAME='fds_p_total_iter') RESULT(N)
INTEGER(C_INT) :: N
N = TOTAL_PRESSURE_ITERATIONS
END FUNCTION FDS_P_TOTAL_ITER

FUNCTION FDS_P_ITER_BARO() BIND(C,NAME='fds_p_iter_baro') RESULT(F)
INTEGER(C_INT) :: F
F = MERGE(1,0,ITERATE_BAROCLINIC_TERM)
END FUNCTION FDS_P_ITER_BARO

SUBROUTINE FDS_P_SET_ITER_BARO(F) BIND(C,NAME='fds_p_set_iter_baro')
INTEGER(C_INT), VALUE :: F
ITERATE_BAROCLINIC_TERM = (F/=0)
END SUBROUTINE FDS_P_SET_ITER_BARO

SUBROUTINE FDS_P_CLEAR_ATTACHED(NM) BIND(C,NAME='fds_p_clear_attached')
INTEGER(C_INT), VALUE :: NM
MESHES(NM)%BAROCLINIC_TERMS_ATTACHED = .FALSE.
END SUBROUTINE FDS_P_CLEAR_ATTACHED

SUBROUTINE FDS_P_BAROCLINIC(T,NM) BIND(C,NAME='fds_p_baroclinic')
REAL(C_DOUBLE), VALUE :: T
INTEGER(C_INT), VALUE :: NM
CALL BAROCLINIC_CORRECTION(T,NM)
END SUBROUTINE FDS_P_BAROCLINIC

!> NO_FLUX(DT,NM); ZERO/=0 also zeroes WALL_WORK1 (first pressure iteration, main.f90:1704).
SUBROUTINE FDS_P_NOFLUX(DT,NM,ZERO) BIND(C,NAME='fds_p_noflux')
REAL(C_DOUBLE), VALUE :: DT
INTEGER(C_INT), VALUE :: NM,ZERO
CALL NO_FLUX(DT,NM)
IF (ZERO/=0) MESHES(NM)%WALL_WORK1 = 0._EB
END SUBROUTINE FDS_P_NOFLUX

SUBROUTINE FDS_P_RHS(T,DT,NM) BIND(C,NAME='fds_p_rhs')
REAL(C_DOUBLE), VALUE :: T,DT
INTEGER(C_INT), VALUE :: NM
CALL PRESSURE_SOLVER_COMPUTE_RHS(T,DT,NM)
END SUBROUTINE FDS_P_RHS

!> PRHS(1:IBAR,1:JBAR,1:KBAR) (IPS=0 layout) packed I fastest. The Poisson right-hand side that the replaced PRESSURE_SOLVER_FFT would have solved.
SUBROUTINE FDS_P_GET_PRHS(NM,BUF) BIND(C,NAME='fds_p_get_prhs')
INTEGER(C_INT), VALUE :: NM
REAL(C_DOUBLE), INTENT(OUT) :: BUF(*)
TYPE(MESH_TYPE), POINTER :: M
M => MESHES(NM)
BUF(1:M%IBAR*M%JBAR*M%KBAR) = RESHAPE(M%PRHS(1:M%IBAR,1:M%JBAR,1:M%KBAR),(/M%IBAR*M%JBAR*M%KBAR/))
END SUBROUTINE FDS_P_GET_PRHS

!> max|BXS|, max|BXF|, max|BYS|, max|BYF|, max|BZS|, max|BZF| of mesh NM over the faces with FLAGS(f)/=0 (inhomogeneous boundary data of the Poisson problem;
!> the driver flags the physical, non-periodic faces of the directions the solver uses)
SUBROUTINE FDS_P_BMAX(NM,FLAGS,V) BIND(C,NAME='fds_p_bmax')
INTEGER(C_INT), VALUE :: NM
INTEGER(C_INT), INTENT(IN) :: FLAGS(6)
REAL(C_DOUBLE), INTENT(OUT) :: V(6)
TYPE(MESH_TYPE), POINTER :: M
M => MESHES(NM)
V = 0._EB
IF (FLAGS(1)/=0) V(1) = MAXVAL(ABS(M%BXS))
IF (FLAGS(2)/=0) V(2) = MAXVAL(ABS(M%BXF))
IF (FLAGS(3)/=0) V(3) = MAXVAL(ABS(M%BYS))
IF (FLAGS(4)/=0) V(4) = MAXVAL(ABS(M%BYF))
IF (FLAGS(5)/=0) V(5) = MAXVAL(ABS(M%BZS))
IF (FLAGS(6)/=0) V(6) = MAXVAL(ABS(M%BZF))
END SUBROUTINE FDS_P_BMAX

!> The boundary-value block that follows the Poisson solve in PRESSURE_SOLVER_FFT (pres.f90, "Apply boundary conditions to H"), for the PHYSICAL faces only:
!> FLAGS(1:6) = x-low, x-high, y-low, y-high, z-low, z-high. Faces between boxes and periodic images are filled by the AMReX ghost fill instead. HP = H (predictor) or HS.
SUBROUTINE FDS_P_H_GHOST(NM,PRED,FLAGS) BIND(C,NAME='fds_p_h_ghost')
INTEGER(C_INT), VALUE :: NM,PRED
INTEGER(C_INT), INTENT(IN) :: FLAGS(6)
TYPE(MESH_TYPE), POINTER :: M
REAL(EB), POINTER, DIMENSION(:,:,:) :: HP
INTEGER :: I,J,K,IBAR,JBAR,KBAR,IBP1,JBP1,KBP1,LBC,MBC,NBC
M => MESHES(NM)
IF (PRED/=0) THEN ; HP => M%H ; ELSE ; HP => M%HS ; ENDIF
IBAR=M%IBAR ; JBAR=M%JBAR ; KBAR=M%KBAR ; IBP1=IBAR+1 ; JBP1=JBAR+1 ; KBP1=KBAR+1
LBC=M%LBC ; MBC=M%MBC ; NBC=M%NBC
DO K=1,KBAR
   DO J=1,JBAR
      IF (FLAGS(1)/=0) THEN
         IF (LBC==3 .OR. LBC==4)             HP(0,J,K)    = HP(1,J,K)    - M%DXI*M%BXS(J,K)
         IF (LBC==1 .OR. LBC==2)             HP(0,J,K)    =-HP(1,J,K)    + 2._EB*M%BXS(J,K)
         IF (LBC==5 .OR. LBC==6)             HP(0,J,K)    = HP(1,J,K)
         IF (LBC==0)                         HP(0,J,K)    = HP(IBAR,J,K)
      ENDIF
      IF (FLAGS(2)/=0) THEN
         IF (LBC==3 .OR. LBC==2 .OR. LBC==6) HP(IBP1,J,K) = HP(IBAR,J,K) + M%DXI*M%BXF(J,K)
         IF (LBC==1 .OR. LBC==4 .OR. LBC==5) HP(IBP1,J,K) =-HP(IBAR,J,K) + 2._EB*M%BXF(J,K)
         IF (LBC==0)                         HP(IBP1,J,K) = HP(1,J,K)
      ENDIF
   ENDDO
ENDDO
DO K=1,KBAR
   DO I=1,IBAR
      IF (FLAGS(3)/=0) THEN
         IF (MBC==3 .OR. MBC==4) HP(I,0,K)    = HP(I,1,K)    - M%DETA*M%BYS(I,K)
         IF (MBC==1 .OR. MBC==2) HP(I,0,K)    =-HP(I,1,K)    + 2._EB*M%BYS(I,K)
         IF (MBC==0)             HP(I,0,K)    = HP(I,JBAR,K)
      ENDIF
      IF (FLAGS(4)/=0) THEN
         IF (MBC==3 .OR. MBC==2) HP(I,JBP1,K) = HP(I,JBAR,K) + M%DETA*M%BYF(I,K)
         IF (MBC==1 .OR. MBC==4) HP(I,JBP1,K) =-HP(I,JBAR,K) + 2._EB*M%BYF(I,K)
         IF (MBC==0)             HP(I,JBP1,K) = HP(I,1,K)
      ENDIF
   ENDDO
ENDDO
DO J=1,JBAR
   DO I=1,IBAR
      IF (FLAGS(5)/=0) THEN
         IF (NBC==3 .OR. NBC==4) HP(I,J,0)    = HP(I,J,1)    - M%DZETA*M%BZS(I,J)
         IF (NBC==1 .OR. NBC==2) HP(I,J,0)    =-HP(I,J,1)    + 2._EB*M%BZS(I,J)
         IF (NBC==0)             HP(I,J,0)    = HP(I,J,KBAR)
      ENDIF
      IF (FLAGS(6)/=0) THEN
         IF (NBC==3 .OR. NBC==2) HP(I,J,KBP1) = HP(I,J,KBAR) + M%DZETA*M%BZF(I,J)
         IF (NBC==1 .OR. NBC==4) HP(I,J,KBP1) =-HP(I,J,KBAR) + 2._EB*M%BZF(I,J)
         IF (NBC==0)             HP(I,J,KBP1) = HP(I,J,1)
      ENDIF
   ENDDO
ENDDO
END SUBROUTINE FDS_P_H_GHOST

SUBROUTINE FDS_P_RESID(NM) BIND(C,NAME='fds_p_resid')
INTEGER(C_INT), VALUE :: NM
CALL PRESSURE_SOLVER_CHECK_RESIDUALS(NM)
END SUBROUTINE FDS_P_RESID

SUBROUTINE FDS_P_VELERR(DT,NM) BIND(C,NAME='fds_p_velerr')
REAL(C_DOUBLE), VALUE :: DT
INTEGER(C_INT), VALUE :: NM
CALL COMPUTE_VELOCITY_ERROR(DT,NM)
END SUBROUTINE FDS_P_VELERR

!> PRESSURE_ERROR_MAX(NM), VELOCITY_ERROR_MAX(NM), POIS_ERR(NM) as FDS holds them (PRESSURE_ERROR_MAX keeps its old value when ITERATE_BAROCLINIC_TERM is false)
SUBROUTINE FDS_P_GET_ERR(NM,PE,VE,PTB) BIND(C,NAME='fds_p_get_err')
INTEGER(C_INT), VALUE :: NM
REAL(C_DOUBLE), INTENT(OUT) :: PE,VE,PTB
PE = PRESSURE_ERROR_MAX(NM) ; VE = VELOCITY_ERROR_MAX(NM) ; PTB = MESHES(NM)%POIS_ERR
END SUBROUTINE FDS_P_GET_ERR

SUBROUTINE FDS_P_SET_WALL_COUNTER(N) BIND(C,NAME='fds_p_set_wall_counter')
INTEGER(C_INT), VALUE :: N
WALL_COUNTER = N
END SUBROUTINE FDS_P_SET_WALL_COUNTER

FUNCTION FDS_P_STOP_STATUS() BIND(C,NAME='fds_p_stop_status') RESULT(S)
INTEGER(C_INT) :: S
S = STOP_STATUS
END FUNCTION FDS_P_STOP_STATUS

!> Interface walls as no-wall faces around a kernel (S6, decomposition independence). A box-to-box interface is an interior face of the level: in the single mesh the
!> same face has no wall cell, so DIVERGENCE_PART_1/2 treat it as a regular face, whereas an INTERPOLATED wall adds wall-face terms from its wall arrays (RHO_F, TMP_F,
!> ZZ_F, UVW_SAVE) that belong to the multi-mesh coupling. MODE=1: external walls of box NM with BOUNDARY_TYPE=INTERPOLATED_BOUNDARY and NOM>0 become NULL_BOUNDARY with
!> CELL%WALL_INDEX=0; MODE=0 puts them back (the list is remembered per box). EDGE(1:6): 1 when the box face in the direction IOR=1,-1,2,-2,3,-3 lies on the level's
!> domain boundary: ALL_EDGES=0 leaves those walls alone (a periodic image at the domain edge is a wall of the single mesh too), ALL_EDGES=1 converts them as well.
SUBROUTINE FDS_P_IFACE_WALLS(NM,MODE,EDGE,ALL_EDGES) BIND(C,NAME='fds_p_iface_walls')
INTEGER(C_INT), VALUE :: NM,MODE,ALL_EDGES
INTEGER(C_INT), INTENT(IN) :: EDGE(6)
TYPE(MESH_TYPE), POINTER :: M
TYPE :: SAVED_T
   INTEGER, ALLOCATABLE :: IW(:)
END TYPE SAVED_T
TYPE(SAVED_T), ALLOCATABLE, SAVE :: SV(:)
INTEGER :: IW,K,KF
IF (.NOT.ALLOCATED(SV)) ALLOCATE(SV(NMESHES))
M => MESHES(NM)
IF (MODE==1) THEN
   IF (ALLOCATED(SV(NM)%IW)) RETURN
   ALLOCATE(SV(NM)%IW(M%N_EXTERNAL_WALL_CELLS)) ; SV(NM)%IW = 0
   K = 0
   DO IW=1,M%N_EXTERNAL_WALL_CELLS
      IF (M%WALL(IW)%BOUNDARY_TYPE/=INTERPOLATED_BOUNDARY .OR. M%EXTERNAL_WALL(IW)%NOM<=0) CYCLE
      ASSOCIATE (BC=>M%BOUNDARY_COORD(M%WALL(IW)%BC_INDEX))
      SELECT CASE(BC%IOR)
         CASE( 1) ; KF=1
         CASE(-1) ; KF=2
         CASE( 2) ; KF=3
         CASE(-2) ; KF=4
         CASE( 3) ; KF=5
         CASE(-3) ; KF=6
      END SELECT
      IF (EDGE(KF)/=0 .AND. ALL_EDGES==0) CYCLE
      K = K+1 ; SV(NM)%IW(K) = IW
      M%WALL(IW)%BOUNDARY_TYPE = NULL_BOUNDARY
      M%CELL(M%CELL_INDEX(BC%IIG,BC%JJG,BC%KKG))%WALL_INDEX(-BC%IOR) = 0
      END ASSOCIATE
   ENDDO
ELSE
   IF (.NOT.ALLOCATED(SV(NM)%IW)) RETURN
   DO K=1,SIZE(SV(NM)%IW)
      IW = SV(NM)%IW(K)
      IF (IW==0) EXIT
      ASSOCIATE (BC=>M%BOUNDARY_COORD(M%WALL(IW)%BC_INDEX))
      M%WALL(IW)%BOUNDARY_TYPE = INTERPOLATED_BOUNDARY
      M%CELL(M%CELL_INDEX(BC%IIG,BC%JJG,BC%KKG))%WALL_INDEX(-BC%IOR) = IW
      END ASSOCIATE
   ENDDO
   DEALLOCATE(SV(NM)%IW)
ENDIF
END SUBROUTINE FDS_P_IFACE_WALLS

!> What MATCH_VELOCITY leaves behind for the rest of the step when EXTERNAL_GHOSTS_FILLED is set and it returns at once: UVW_SAVE(IW) = the normal velocity of the
!> face (the value DENSITY restores) and BOUNDARY_TYPE_PREVIOUS. The average with the neighbouring box is not formed: the faces of two boxes are the same face of
!> the level (same data after the driver's exchange), so the average is the face value itself.
SUBROUTINE FDS_P_SAVE_UVW(NM,PRED) BIND(C,NAME='fds_p_save_uvw')
INTEGER(C_INT), VALUE :: NM,PRED
TYPE(MESH_TYPE), POINTER :: M
REAL(EB), POINTER, DIMENSION(:,:,:) :: UU,VV,WW
INTEGER :: IW
M => MESHES(NM)
IF (PRED/=0) THEN ; UU => M%US ; VV => M%VS ; WW => M%WS ; ELSE ; UU => M%U ; VV => M%V ; WW => M%W ; ENDIF
DO IW=1,M%N_EXTERNAL_WALL_CELLS
   M%EXTERNAL_WALL(IW)%BOUNDARY_TYPE_PREVIOUS = M%WALL(IW)%BOUNDARY_TYPE
   IF (M%WALL(IW)%BOUNDARY_TYPE/=INTERPOLATED_BOUNDARY) CYCLE
   ASSOCIATE (BC=>M%BOUNDARY_COORD(M%WALL(IW)%BC_INDEX))
   SELECT CASE(BC%IOR)
      CASE( 1) ; M%UVW_SAVE(IW) = UU(0,BC%JJ,BC%KK)
      CASE(-1) ; M%UVW_SAVE(IW) = UU(M%IBAR,BC%JJ,BC%KK)
      CASE( 2) ; M%UVW_SAVE(IW) = VV(BC%II,0,BC%KK)
      CASE(-2) ; M%UVW_SAVE(IW) = VV(BC%II,M%JBAR,BC%KK)
      CASE( 3) ; M%UVW_SAVE(IW) = WW(BC%II,BC%JJ,0)
      CASE(-3) ; M%UVW_SAVE(IW) = WW(BC%II,BC%JJ,M%KBAR)
   END SELECT
   END ASSOCIATE
ENDDO
END SUBROUTINE FDS_P_SAVE_UVW

!> Diagnostic (env FDSTL_EDGES): write EDGE(:)%OMEGA(-2:2) then EDGE(:)%TAU(-2:2) of box NM (NE x 5 each, column-major like the reference dump E_OMEGA/E_TAU) to the file FN.
SUBROUTINE FDS_P_EDGE_DUMP(NM,FN,NC) BIND(C,NAME='fds_p_edge_dump')
INTEGER(C_INT), VALUE :: NM,NC
CHARACTER(KIND=C_CHAR), INTENT(IN) :: FN(*)
CHARACTER(LEN=512) :: NAME
REAL(EB), ALLOCATABLE :: T(:,:)
INTEGER :: I,K,NE,LU
NAME = ' '
DO I=1,MIN(NC,512) ; NAME(I:I) = FN(I) ; ENDDO
NE = SIZE(MESHES(NM)%EDGE)
ALLOCATE(T(NE,10))
DO I=1,5 ; DO K=1,NE ; T(K,I) = MESHES(NM)%EDGE(K)%OMEGA(I-3) ; T(K,5+I) = MESHES(NM)%EDGE(K)%TAU(I-3) ; ENDDO ; ENDDO
OPEN(NEWUNIT=LU,FILE=TRIM(NAME),FORM='UNFORMATTED',ACCESS='STREAM',STATUS='REPLACE')
WRITE(LU) T
CLOSE(LU)
DEALLOCATE(T)
END SUBROUTINE FDS_P_EDGE_DUMP

!> Diagnostic: print the wall-cell data of the external walls of box NM whose ghost-side cell lies in the plane (KG0 or any when KG0<0), for decomposition comparisons
!> (env FDSTL_WALLS). One line per wall: global cell (IIG+OFX,JJG,KKG+OFZ), IOR, type, NOM, RHO_F, TMP_F, UVW_SAVE, ZZ_F(1), U_NORMAL_S, U_NORMAL, K_G.
SUBROUTINE FDS_P_WALL_DUMP(NM,OFX,OFZ,KG0) BIND(C,NAME='fds_p_wall_dump')
INTEGER(C_INT), VALUE :: NM,OFX,OFZ,KG0
TYPE(MESH_TYPE), POINTER :: M
INTEGER :: IW
M => MESHES(NM)
DO IW=1,M%N_EXTERNAL_WALL_CELLS
   ASSOCIATE (BC=>M%BOUNDARY_COORD(M%WALL(IW)%BC_INDEX),B1=>M%BOUNDARY_PROP1(M%WALL(IW)%B1_INDEX))
   IF (KG0>=0 .AND. BC%KKG+OFZ/=KG0) CYCLE
   WRITE(0,'(A,6(I4,1X),ES23.15,1X,ES23.15,1X,ES23.15,1X,ES23.15,1X,ES23.15,1X,ES23.15,1X,ES23.15)') 'WALLDUMP ',BC%IIG+OFX,BC%JJG,BC%KKG+OFZ,BC%IOR,M%WALL(IW)%BOUNDARY_TYPE,M%EXTERNAL_WALL(IW)%NOM, &
      B1%RHO_F,B1%TMP_F,M%UVW_SAVE(IW),B1%ZZ_F(1),B1%U_NORMAL_S,B1%U_NORMAL,B1%K_G
   END ASSOCIATE
ENDDO
END SUBROUTINE FDS_P_WALL_DUMP

END MODULE FDS_STEP
