!> \brief Fine-level mesh objects of the AMR driver (D-056 option B, needs patch 0007 in Source/mesh.f90; compiled when FDS_FINE_B is defined, see CMakeLists.txt).
!> BUILD_FINE_BOX makes the mesh object of one axis-aligned uniform Cartesian fine box (moved here unchanged from draft/fds_fine_box_b.f90, which now uses it).
!> FDS_FINE_LEVEL_CREATE / FDS_FINE_LEVEL_DESTROY are the C entry points of TimeLoop::bind_level: they make and drop FINE_LEVEL(LEV) for the boxes of this rank.
!> The data views of the boxes are bound by FDS_FINE_B_SET_VIEW (fds_box_obj.f90). Not validated with the oneAPI compilers; DRAFT with patches 0007 to 0009.
MODULE FDS_FINE_LEVEL

USE ISO_C_BINDING
USE PRECISION_PARAMETERS, ONLY: EB
USE GLOBAL_CONSTANTS, ONLY: N_TOTAL_SCALARS,FLUX_LIMITER_MW_CORRECTION,N_TRACKED_SPECIES,TMPA,RHOA,RSUM0,U0,V0,W0,PARTICLE_DRAG,CHECK_VN,REAC_SOURCE_CHECK, &
   STORE_SPECIES_FLUX,N_ZONE,STRATIFICATION,I_RAMP_TMP0_Z,I_RAMP_P0_Z,P_INF,STORE_PRESSURE_POISSON_RESIDUAL,STORE_CUTCELL_DIVERGENCE,STORE_CARTESIAN_DIVERGENCE,N_LP_ARRAY_INDICES,N_REACTIONS,RADIATION,N_LAGRANGIAN_CLASSES,NULL_BOUNDARY,DEFAULT_SURF_INDEX
USE MESH_VARIABLES, ONLY: MESHES,MESH_TYPE
USE GLOBAL_CONSTANTS, ONLY: TURB_MODEL,C_SMAGORINSKY,CONSMAG,DYNSMAG
USE PHYSICAL_FUNCTIONS, ONLY: LES_FILTER_WIDTH_FUNCTION
USE MATH_FUNCTIONS, ONLY: EVALUATE_RAMP
USE MESH_POINTERS, ONLY: FINE_LEVEL,FINE_LEVEL_TYPE
USE FDS_AMREX_HOOKS, ONLY: FDS_HOOK_SET_FINE_READY
USE FDS_KERNELS, ONLY: FDS_K_RESERVE_BOXES

IMPLICIT NONE (TYPE,EXTERNAL)
PRIVATE
PUBLIC :: BUILD_FINE_BOX,FDS_FINE_LEVEL_CREATE,FDS_FINE_LEVEL_DESTROY

CONTAINS

!> Make FINE_LEVEL(LEV) with NBOX boxes (LEV = the next level above the existing ones, or the top level again after FDS_FINE_LEVEL_DESTROY). Box IB has IJK(:,IB) cells
!> on [XB(1,IB),XB(2,IB)] x [XB(3,IB),XB(4,IB)] x [XB(5,IB),XB(6,IB)]; its mesh object is built only when LOCAL(IB)/=0 (the boxes of this rank). NM0 returns the offset of the
!> mesh numbers (box IB is mesh NM0+IB). Per-mesh-number kernel arrays are made large enough and the kernel wrappers are declared fine-ready.
!> IERR: 0 ok, 1 bad level (not the top level), 2 no fine-level support in this tree, 3 the level-0 meshes of this rank have more than one pressure zone (a fine box gets the single zone of level 0).
FUNCTION FDS_FINE_LEVEL_CREATE(LEV,NBOX,IJK,XB,LOCAL,NM0) BIND(C,NAME='fds_fine_level_create') RESULT(IERR)

INTEGER(C_INT), VALUE :: LEV,NBOX
INTEGER(C_INT), INTENT(IN) :: IJK(3,NBOX),LOCAL(NBOX)
REAL(C_DOUBLE), INTENT(IN) :: XB(6,NBOX)
INTEGER(C_INT), INTENT(OUT) :: NM0
INTEGER(C_INT) :: IERR
TYPE(FINE_LEVEL_TYPE), ALLOCATABLE :: TMP(:)
INTEGER :: L,IB,N0,NM,Z0,NMREF,K
LOGICAL :: Z0_SET

IERR = 0 ; NM0 = 0
IF (LEV<1) THEN ; IERR = 1 ; RETURN ; ENDIF
IF (.NOT.ALLOCATED(FINE_LEVEL)) ALLOCATE(FINE_LEVEL(0))
IF (LEV<SIZE(FINE_LEVEL)) THEN ; IERR = 1 ; RETURN ; ENDIF           ! only the top level may be (re)made: the mesh numbers of the levels above would move
IF (LEV>SIZE(FINE_LEVEL)+1) THEN ; IERR = 1 ; RETURN ; ENDIF
IF (LEV==SIZE(FINE_LEVEL)+1) THEN
   ALLOCATE(TMP(LEV))
   DO L=1,SIZE(FINE_LEVEL)
      CALL MOVE_ALLOC(FINE_LEVEL(L)%BOX,TMP(L)%BOX) ; CALL MOVE_ALLOC(FINE_LEVEL(L)%VIEW,TMP(L)%VIEW)
      TMP(L)%NM0 = FINE_LEVEL(L)%NM0 ; TMP(L)%N_BOXES = FINE_LEVEL(L)%N_BOXES
   ENDDO
   CALL MOVE_ALLOC(TMP,FINE_LEVEL)
ENDIF
N0 = SIZE(MESHES)
DO L=1,LEV-1
   N0 = N0 + FINE_LEVEL(L)%N_BOXES
ENDDO
! pressure zone of the fine boxes: the one zone that all cells of the level-0 meshes of this rank have (a case with several zones is refused)
Z0 = 0 ; Z0_SET = .FALSE. ; NMREF = 0
DO NM=1,SIZE(MESHES)
   IF (.NOT.ALLOCATED(MESHES(NM)%PRESSURE_ZONE)) CYCLE
   IF (NMREF==0 .AND. ALLOCATED(MESHES(NM)%PBAR)) NMREF = NM
   IF (.NOT.Z0_SET) THEN ; Z0 = MESHES(NM)%PRESSURE_ZONE(1,1,1) ; Z0_SET = .TRUE. ; ENDIF
   IF (ANY(MESHES(NM)%PRESSURE_ZONE(1:MESHES(NM)%IBAR,1:MESHES(NM)%JBAR,1:MESHES(NM)%KBAR)/=Z0)) THEN ; IERR = 3 ; RETURN ; ENDIF
ENDDO
FINE_LEVEL(LEV)%NM0 = N0 ; FINE_LEVEL(LEV)%N_BOXES = NBOX
IF (ALLOCATED(FINE_LEVEL(LEV)%BOX)) DEALLOCATE(FINE_LEVEL(LEV)%BOX)
IF (ALLOCATED(FINE_LEVEL(LEV)%VIEW)) DEALLOCATE(FINE_LEVEL(LEV)%VIEW)
ALLOCATE(FINE_LEVEL(LEV)%BOX(NBOX),FINE_LEVEL(LEV)%VIEW(NBOX))
DO IB=1,NBOX
   IF (LOCAL(IB)/=0) CALL BUILD_FINE_BOX(FINE_LEVEL(LEV)%BOX(IB),IJK(1,IB),IJK(2,IB),IJK(3,IB),XB(1,IB),XB(2,IB),XB(3,IB),XB(4,IB),XB(5,IB),XB(6,IB))
   IF (LOCAL(IB)/=0) THEN
      FINE_LEVEL(LEV)%BOX(IB)%PRESSURE_ZONE = Z0
      ! zone-wide background pressure state (PBAR, PBAR_S, D_PBAR_DT, D_PBAR_DT_S, U_LEAK, R_PBAR) of a new box = the one of the level-0 mesh (without STRATIFICATION PBAR is uniform in K;
      ! with STRATIFICATION the box keeps its own P_0 profile and takes only the zone rates)
      IF (NMREF>0) THEN
         ASSOCIATE(M=>FINE_LEVEL(LEV)%BOX(IB),R=>MESHES(NMREF))
            M%D_PBAR_DT = R%D_PBAR_DT ; M%D_PBAR_DT_S = R%D_PBAR_DT_S ; M%U_LEAK = R%U_LEAK
            IF (.NOT.STRATIFICATION) THEN
               DO K=0,M%KBP1
                  M%PBAR(K,:) = R%PBAR(1,:) ; M%PBAR_S(K,:) = R%PBAR_S(1,:) ; M%R_PBAR(K,:) = R%R_PBAR(1,:)
               ENDDO
            ENDIF
         END ASSOCIATE
      ENDIF
   ENDIF
ENDDO
CALL FDS_K_RESERVE_BOXES(INT(N0+NBOX,C_INT))
CALL FDS_HOOK_SET_FINE_READY(1_C_INT)
NM0 = INT(N0,C_INT)

END FUNCTION FDS_FINE_LEVEL_CREATE

!> Drop the boxes and views of the top level LEV (before it is made again after a regrid, or when it is cleared). IERR 1 when LEV is not the top level.
FUNCTION FDS_FINE_LEVEL_DESTROY(LEV) BIND(C,NAME='fds_fine_level_destroy') RESULT(IERR)

INTEGER(C_INT), VALUE :: LEV
INTEGER(C_INT) :: IERR

IERR = 0
IF (.NOT.ALLOCATED(FINE_LEVEL)) THEN ; IERR = 1 ; RETURN ; ENDIF
IF (LEV/=SIZE(FINE_LEVEL) .OR. LEV<1) THEN ; IERR = 1 ; RETURN ; ENDIF
IF (ALLOCATED(FINE_LEVEL(LEV)%BOX)) DEALLOCATE(FINE_LEVEL(LEV)%BOX)
IF (ALLOCATED(FINE_LEVEL(LEV)%VIEW)) DEALLOCATE(FINE_LEVEL(LEV)%VIEW)
FINE_LEVEL(LEV)%N_BOXES = 0

END FUNCTION FDS_FINE_LEVEL_DESTROY

!> Allocate the arrays of a fine-level mesh object of NI x NJ x NK cells on [XS,XF]x[YS,YF]x[ZS,ZF] (axis-aligned, uniform, Cartesian, no obstructions) with the contents the kernels read
!> (level-interface.md section 3): metrics (the arithmetic of READ_MESH for an untransformed grid), cell tables (ghost ring SOLID/EXTERIOR as READ_OBST sets it), empty edge and wall tables
!> (a fine box has no WALL cells: its non-domain faces are interface faces whose ghost values the driver fills, and there is no OMESH neighbour), and the state, field and work arrays of
!> INITIALIZE_MESH_VARIABLES_1 (initial values as there). Models with particles or radiation are not supported on fine levels yet.
SUBROUTINE BUILD_FINE_BOX(M,NI,NJ,NK,XS,XF,YS,YF,ZS,ZF)

TYPE(MESH_TYPE), INTENT(INOUT) :: M
INTEGER, INTENT(IN) :: NI,NJ,NK
REAL(EB), INTENT(IN) :: XS,XF,YS,YF,ZS,ZF
INTEGER :: I,J,K,IC,NC,IBP1,JBP1,KBP1,N_LOWER_SCALARS

IF (RADIATION .OR. N_LAGRANGIAN_CLASSES>0 .OR. N_LP_ARRAY_INDICES>0) THEN
   WRITE(0,'(A)') 'fds_amr ERROR in BUILD_FINE_BOX: fine-level boxes do not support particles or radiation yet.' ; ERROR STOP 1
ENDIF
N_LOWER_SCALARS = MERGE(0,1,FLUX_LIMITER_MW_CORRECTION)   ! as in INITIALIZE_MESH_VARIABLES_1
M%IBAR=NI ; M%JBAR=NJ ; M%KBAR=NK ; M%IBM1=NI-1 ; M%JBM1=NJ-1 ; M%KBM1=NK-1 ; M%IBP1=NI+1 ; M%JBP1=NJ+1 ; M%KBP1=NK+1
IBP1=M%IBP1 ; JBP1=M%JBP1 ; KBP1=M%KBP1
M%XS=XS ; M%XF=XF ; M%YS=YS ; M%YF=YF ; M%ZS=ZS ; M%ZF=ZF
M%DXI=(XF-XS)/REAL(NI,EB) ; M%DETA=(YF-YS)/REAL(NJ,EB) ; M%DZETA=(ZF-ZS)/REAL(NK,EB)
M%RDXI=1._EB/M%DXI ; M%RDETA=1._EB/M%DETA ; M%RDZETA=1._EB/M%DZETA
ALLOCATE(M%X(0:NI),M%XC(0:NI+1),M%HX(0:NI+1),M%DX(0:NI+1),M%RDX(0:NI+1),M%DXN(0:NI),M%RDXN(0:NI),M%R(0:NI),M%RC(0:NI+1),M%RRN(0:NI+1))
ALLOCATE(M%Y(0:NJ),M%YC(0:NJ+1),M%HY(0:NJ+1),M%DY(0:NJ+1),M%RDY(0:NJ+1),M%DYN(0:NJ),M%RDYN(0:NJ))
ALLOCATE(M%Z(0:NK),M%ZC(0:NK+1),M%HZ(0:NK+1),M%DZ(0:NK+1),M%RDZ(0:NK+1),M%DZN(0:NK),M%RDZN(0:NK))
M%R=1._EB ; M%RC=1._EB ; M%RRN=1._EB
CALL AXIS(NI,XS,XF,M%DXI,M%X,M%XC,M%HX,M%DX,M%RDX,M%DXN,M%RDXN,M%DXMIN)
CALL AXIS(NJ,YS,YF,M%DETA,M%Y,M%YC,M%HY,M%DY,M%RDY,M%DYN,M%RDYN,M%DYMIN)
CALL AXIS(NK,ZS,ZF,M%DZETA,M%Z,M%ZC,M%HZ,M%DZ,M%RDZ,M%DZN,M%RDZN,M%DZMIN)

! cell tables: the ghost ring gets cell numbers (READ_OBST order), is SOLID and EXTERIOR; interior cells use index 0 (CELL(0), non-solid)
ALLOCATE(M%CELL_INDEX(0:IBP1,0:JBP1,0:KBP1)) ; M%CELL_INDEX = 0
NC = 0
DO K=0,KBP1
   DO J=0,JBP1
      DO I=0,IBP1
         IF (I<=1 .OR. I>=NI .OR. J<=1 .OR. J>=NJ .OR. K<=1 .OR. K>=NK) THEN ; NC = NC+1 ; ENDIF
      ENDDO
   ENDDO
ENDDO
CALL NUMBER_CELLS(M,NI,NJ,NK,NC)
ALLOCATE(M%CELL(0:NC))
DO K=0,KBP1
   DO J=0,JBP1
      DO I=0,IBP1
         IC = M%CELL_INDEX(I,J,K)
         IF (IC>0) THEN
            M%CELL(IC)%I=I ; M%CELL(IC)%J=J ; M%CELL(IC)%K=K
            IF (I==0 .OR. I==IBP1 .OR. J==0 .OR. J==JBP1 .OR. K==0 .OR. K==KBP1) THEN ; M%CELL(IC)%SOLID=.TRUE. ; M%CELL(IC)%EXTERIOR=.TRUE. ; ENDIF
         ENDIF
      ENDDO
   ENDDO
ENDDO
ALLOCATE(M%INTERPOLATED_MESH(1:NI,1:NJ,1:NK)) ; M%INTERPOLATED_MESH = 0     ! no cell of a fine box is covered by a finer mesh (yet)
ALLOCATE(M%EDGE(0:0)) ; ALLOCATE(M%WALL(0:0),M%EXTERNAL_WALL(0),M%THIN_WALL(0:10))
M%WALL(0)%BOUNDARY_TYPE = NULL_BOUNDARY ; M%WALL(0)%SURF_INDEX = DEFAULT_SURF_INDEX
M%N_WALL_CELLS=0 ; M%N_WALL_CELLS_DIM=0 ; M%N_INTERNAL_WALL_CELLS=0 ; M%N_EXTERNAL_WALL_CELLS=0
ALLOCATE(M%UVW_SAVE(0),M%U_GHOST(0),M%V_GHOST(0),M%W_GHOST(0),M%WALL_WORK1(0),M%WALL_WORK2(0))

! state, field and work arrays (init.f90, INITIALIZE_MESH_VARIABLES_1)
ALLOCATE(M%TMP(-1:IBP1+1,-1:JBP1+1,-1:KBP1+1)) ; M%TMP = TMPA
ALLOCATE(M%RHO(-1:IBP1+1,-1:JBP1+1,-1:KBP1+1)) ; M%RHO = RHOA
ALLOCATE(M%RHOS(-1:IBP1+1,-1:JBP1+1,-1:KBP1+1)) ; M%RHOS = RHOA
ALLOCATE(M%ZZ(-1:IBP1+1,-1:JBP1+1,-1:KBP1+1,N_TOTAL_SCALARS)) ; M%ZZ = 0._EB
ALLOCATE(M%ZZS(-1:IBP1+1,-1:JBP1+1,-1:KBP1+1,N_TOTAL_SCALARS)) ; M%ZZS = 0._EB
ALLOCATE(M%WORK_PAD(-1:IBP1+1,-1:JBP1+1,-1:KBP1+1)) ; M%WORK_PAD = 0._EB
ALLOCATE(M%U(-1:IBP1,0:JBP1,0:KBP1),M%US(-1:IBP1,0:JBP1,0:KBP1),M%WORK_U(-1:IBP1,0:JBP1,0:KBP1)) ; M%U=0._EB ; M%US=0._EB ; M%WORK_U=0._EB
ALLOCATE(M%V(0:IBP1,-1:JBP1,0:KBP1),M%VS(0:IBP1,-1:JBP1,0:KBP1),M%WORK_V(0:IBP1,-1:JBP1,0:KBP1)) ; M%V=0._EB ; M%VS=0._EB ; M%WORK_V=0._EB
ALLOCATE(M%W(0:IBP1,0:JBP1,-1:KBP1),M%WS(0:IBP1,0:JBP1,-1:KBP1),M%WORK_W(0:IBP1,0:JBP1,-1:KBP1)) ; M%W=0._EB ; M%WS=0._EB ; M%WORK_W=0._EB
ALLOCATE(M%FVX(0:IBP1,0:JBP1,0:KBP1),M%FVY(0:IBP1,0:JBP1,0:KBP1),M%FVZ(0:IBP1,0:JBP1,0:KBP1)) ; M%FVX=0._EB ; M%FVY=0._EB ; M%FVZ=0._EB
ALLOCATE(M%FVX_B(0:IBP1,0:JBP1,0:KBP1),M%FVY_B(0:IBP1,0:JBP1,0:KBP1),M%FVZ_B(0:IBP1,0:JBP1,0:KBP1)) ; M%FVX_B=0._EB ; M%FVY_B=0._EB ; M%FVZ_B=0._EB
IF (PARTICLE_DRAG) THEN
   ALLOCATE(M%FVX_D(0:IBP1,0:JBP1,0:KBP1),M%FVY_D(0:IBP1,0:JBP1,0:KBP1),M%FVZ_D(0:IBP1,0:JBP1,0:KBP1)) ; M%FVX_D=0._EB ; M%FVY_D=0._EB ; M%FVZ_D=0._EB
ENDIF
ALLOCATE(M%H(0:IBP1,0:JBP1,0:KBP1),M%HS(0:IBP1,0:JBP1,0:KBP1)) ; M%H=0.5_EB*(U0**2+V0**2+W0**2) ; M%HS=0.5_EB*(U0**2+V0**2+W0**2)
ALLOCATE(M%KRES(0:IBP1,0:JBP1,0:KBP1),M%DDDT(0:IBP1,0:JBP1,0:KBP1),M%D(0:IBP1,0:JBP1,0:KBP1),M%DS(0:IBP1,0:JBP1,0:KBP1)) ; M%KRES=0._EB ; M%DDDT=0._EB ; M%D=0._EB ; M%DS=0._EB
ALLOCATE(M%MU(0:IBP1,0:JBP1,0:KBP1),M%MU_DNS(0:IBP1,0:JBP1,0:KBP1)) ; M%MU=0._EB ; M%MU_DNS=0._EB
IF (CHECK_VN) THEN ; ALLOCATE(M%D_Z_MAX(0:IBP1,0:JBP1,0:KBP1)) ; M%D_Z_MAX=0._EB ; ENDIF
ALLOCATE(M%STRAIN_RATE(0:IBP1,0:JBP1,0:KBP1)) ; M%STRAIN_RATE=0._EB
ALLOCATE(M%CSD2(0:IBP1,0:JBP1,0:KBP1)) ; M%CSD2=0._EB
ALLOCATE(M%Q(0:IBP1,0:JBP1,0:KBP1)) ; M%Q=0._EB
ALLOCATE(M%MIX_TIME(0:IBP1,0:JBP1,0:KBP1)) ; M%MIX_TIME=0._EB
ALLOCATE(M%PRESSURE_ZONE(0:IBP1,0:JBP1,0:KBP1)) ; M%PRESSURE_ZONE=0   ! single (ambient) pressure zone; FDS_FINE_LEVEL_CREATE refuses cases with N_ZONE>0
ALLOCATE(M%DEL_RHO_D_DEL_Z(0:IBP1,0:JBP1,0:KBP1,N_TOTAL_SCALARS)) ; M%DEL_RHO_D_DEL_Z=0._EB
ALLOCATE(M%RSUM(0:IBP1,0:JBP1,0:KBP1)) ; M%RSUM=RSUM0
ALLOCATE(M%FX(0:IBP1,0:JBP1,0:KBP1,N_LOWER_SCALARS:N_TOTAL_SCALARS),M%FY(0:IBP1,0:JBP1,0:KBP1,N_LOWER_SCALARS:N_TOTAL_SCALARS),M%FZ(0:IBP1,0:JBP1,0:KBP1,N_LOWER_SCALARS:N_TOTAL_SCALARS))
M%FX=0._EB ; M%FY=0._EB ; M%FZ=0._EB
IF (STORE_SPECIES_FLUX) THEN
   ALLOCATE(M%ADV_FX(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS),M%ADV_FY(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS),M%ADV_FZ(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS))
   ALLOCATE(M%DIF_FX(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS),M%DIF_FY(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS),M%DIF_FZ(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS))
   ALLOCATE(M%DIF_FXS(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS),M%DIF_FYS(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS),M%DIF_FZS(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS))
   M%ADV_FX=0._EB ; M%ADV_FY=0._EB ; M%ADV_FZ=0._EB ; M%DIF_FX=0._EB ; M%DIF_FY=0._EB ; M%DIF_FZ=0._EB ; M%DIF_FXS=0._EB ; M%DIF_FYS=0._EB ; M%DIF_FZS=0._EB
ENDIF
IF (STORE_PRESSURE_POISSON_RESIDUAL) THEN ; ALLOCATE(M%PP_RESIDUAL(0:IBP1,0:JBP1,0:KBP1)) ; M%PP_RESIDUAL=0._EB ; ENDIF
IF (STORE_CUTCELL_DIVERGENCE) THEN ; ALLOCATE(M%CCVELDIV(0:IBP1,0:JBP1,0:KBP1)) ; M%CCVELDIV=0._EB ; ENDIF
IF (STORE_CARTESIAN_DIVERGENCE) THEN ; ALLOCATE(M%CARTVELDIV(0:IBP1,0:JBP1,0:KBP1)) ; M%CARTVELDIV=0._EB ; ENDIF
IF (N_REACTIONS>0) THEN
   ALLOCATE(M%D_SOURCE(0:IBP1,0:JBP1,0:KBP1)) ; M%D_SOURCE=0._EB
   ALLOCATE(M%M_DOT_PPP(0:IBP1,0:JBP1,0:KBP1,1:N_TRACKED_SPECIES)) ; M%M_DOT_PPP=0._EB
ENDIF
IF (REAC_SOURCE_CHECK) THEN
   ALLOCATE(M%REAC_SOURCE_TERM(0:IBP1,0:JBP1,0:KBP1,N_TRACKED_SPECIES),M%Q_REAC(0:IBP1,0:JBP1,0:KBP1,N_REACTIONS)) ; M%REAC_SOURCE_TERM=0._EB ; M%Q_REAC=0._EB
ENDIF
ALLOCATE(M%CHI_R(0:IBP1,0:JBP1,0:KBP1),M%QR(0:IBP1,0:JBP1,0:KBP1),M%KAPPA_GAS(0:IBP1,0:JBP1,0:KBP1),M%UII(0:IBP1,0:JBP1,0:KBP1)) ; M%CHI_R=0._EB ; M%QR=0._EB ; M%KAPPA_GAS=0._EB ; M%UII=0._EB
ALLOCATE(M%WORK1(0:IBP1,0:JBP1,0:KBP1),M%WORK2(0:IBP1,0:JBP1,0:KBP1),M%WORK3(0:IBP1,0:JBP1,0:KBP1),M%WORK4(0:IBP1,0:JBP1,0:KBP1),M%WORK5(0:IBP1,0:JBP1,0:KBP1))
ALLOCATE(M%WORK6(0:IBP1,0:JBP1,0:KBP1),M%WORK7(0:IBP1,0:JBP1,0:KBP1),M%WORK8(0:IBP1,0:JBP1,0:KBP1),M%WORK9(0:IBP1,0:JBP1,0:KBP1),M%IWORK1(0:IBP1,0:JBP1,0:KBP1))
ALLOCATE(M%SWORK1(0:IBP1,0:JBP1,0:KBP1,N_LOWER_SCALARS:N_TOTAL_SCALARS),M%SWORK2(0:IBP1,0:JBP1,0:KBP1,N_LOWER_SCALARS:N_TOTAL_SCALARS))
ALLOCATE(M%SWORK3(0:IBP1,0:JBP1,0:KBP1,N_LOWER_SCALARS:N_TOTAL_SCALARS),M%SWORK4(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS))
M%WORK1=0._EB ; M%WORK2=0._EB ; M%WORK3=0._EB ; M%WORK4=0._EB ; M%WORK5=0._EB ; M%WORK6=0._EB ; M%WORK7=0._EB ; M%WORK8=0._EB ; M%WORK9=0._EB ; M%IWORK1=0
M%SWORK1=0._EB ; M%SWORK2=0._EB ; M%SWORK3=0._EB ; M%SWORK4=0._EB
ALLOCATE(M%U_WIND(0:KBP1),M%V_WIND(0:KBP1),M%W_WIND(0:KBP1)) ; M%U_WIND=U0 ; M%V_WIND=V0 ; M%W_WIND=W0
ALLOCATE(M%LES_FILTER_WIDTH(0:IBP1,0:JBP1,0:KBP1)) ; M%LES_FILTER_WIDTH=0._EB
DO K=0,KBP1 ; DO J=0,JBP1 ; DO I=0,IBP1   ! as INITIALIZE_MESH_VARIABLES_1: filter width and the constant-Smagorinsky coefficient
   M%LES_FILTER_WIDTH(I,J,K) = LES_FILTER_WIDTH_FUNCTION(M%DX(I),M%DY(J),M%DZ(K))
   IF (TURB_MODEL==CONSMAG .OR. TURB_MODEL==DYNSMAG) M%CSD2(I,J,K) = (C_SMAGORINSKY*M%LES_FILTER_WIDTH(I,J,K))**2
ENDDO ; ENDDO ; ENDDO

! background atmosphere (INITIALIZE_ATMOSPHERE, cell-centred part) and background pressure (PBAR, PBAR_S, R_PBAR, D_PBAR_DT, D_PBAR_DT_S, U_LEAK)
ALLOCATE(M%P_0(0:KBP1),M%TMP_0(0:KBP1),M%RHO_0(0:KBP1))
IF (STRATIFICATION) THEN
   DO K=0,KBP1
      M%TMP_0(K) = TMPA*EVALUATE_RAMP(M%ZC(K),I_RAMP_TMP0_Z)
      M%P_0(K)   = EVALUATE_RAMP(M%ZC(K),I_RAMP_P0_Z)
      M%RHO_0(K) = M%P_0(K)/(M%TMP_0(K)*RSUM0)
   ENDDO
ELSE
   M%TMP_0(:) = TMPA ; M%P_0(:) = P_INF ; M%RHO_0(:) = M%P_0(:)/(M%TMP_0(:)*RSUM0)
ENDIF
ALLOCATE(M%PBAR(0:KBP1,0:N_ZONE),M%PBAR_S(0:KBP1,0:N_ZONE),M%R_PBAR(0:KBP1,0:N_ZONE),M%D_PBAR_DT(0:N_ZONE),M%D_PBAR_DT_S(0:N_ZONE),M%U_LEAK(0:N_ZONE))
M%D_PBAR_DT=0._EB ; M%D_PBAR_DT_S=0._EB ; M%U_LEAK=0._EB ; M%R_PBAR=0._EB
DO K=0,KBP1 ; M%PBAR(K,:)=M%P_0(K) ; M%PBAR_S(K,:)=M%P_0(K) ; ENDDO
ALLOCATE(M%BOUNDARY_COORD(0),M%BOUNDARY_PROP1(0),M%BOUNDARY_PROP2(0),M%BOUNDARY_RADIA(0))
M%CLIP_RHOMIN=.FALSE. ; M%CLIP_RHOMAX=.FALSE. ; M%DT_RESTRICT_COUNT=0

END SUBROUTINE BUILD_FINE_BOX

!> One axis of the grid exactly as READ_MESH makes it for an untransformed uniform mesh (G(X)=X).
SUBROUTINE AXIS(N,S,E,DXI,X,XC,HX,DX,RDX,DXN,RDXN,DXMIN)

INTEGER, INTENT(IN) :: N
REAL(EB), INTENT(IN) :: S,E,DXI
REAL(EB), INTENT(OUT) :: X(0:N),XC(0:N+1),HX(0:N+1),DX(0:N+1),RDX(0:N+1),DXN(0:N),RDXN(0:N),DXMIN
INTEGER :: I

DXMIN = 1000000._EB ; DX = 0._EB ; RDX = 0._EB ; HX = 1._EB ; XC = 0._EB
DO I=0,N
   X(I) = S + REAL(I,EB)*DXI
   IF (I>0) THEN
      DX(I) = X(I) - X(I-1)
      DXMIN = MIN(DXMIN,DX(I))
      RDX(I) = 1._EB/DX(I)
   ENDIF
ENDDO
X(0) = S ; X(N) = E
DX(0) = DX(1) ; DX(N+1) = DX(N) ; RDX(0) = 1._EB/DX(1) ; RDX(N+1) = 1._EB/DX(N)
DO I=0,N
   DXN(I) = 0.5_EB*(DX(I)+DX(I+1))
   RDXN(I) = 1._EB/DXN(I)
   IF (I>0) XC(I) = 0.5_EB*(X(I)+X(I-1))
ENDDO
XC(0) = S - 0.5_EB*DX(0) ; XC(N+1) = E + 0.5_EB*DX(N+1)

END SUBROUTINE AXIS

!> The cell numbering of the ghost ring in the order of READ_OBST (low/high x layers, then y, then z).
SUBROUTINE NUMBER_CELLS(M,NI,NJ,NK,NC)

TYPE(MESH_TYPE), INTENT(INOUT) :: M
INTEGER, INTENT(IN) :: NI,NJ,NK
INTEGER, INTENT(INOUT) :: NC
INTEGER :: I,J,K,CNT

CNT = 0
DO K=0,NK+1
   DO J=0,NJ+1
      DO I=0,1 ; CALL NUM(I,J,K) ; ENDDO
      DO I=NI,NI+1 ; CALL NUM(I,J,K) ; ENDDO
   ENDDO
ENDDO
DO K=0,NK+1
   DO I=0,NI+1
      DO J=0,1 ; CALL NUM(I,J,K) ; ENDDO
      DO J=NJ,NJ+1 ; CALL NUM(I,J,K) ; ENDDO
   ENDDO
ENDDO
DO J=0,NJ+1
   DO I=0,NI+1
      DO K=0,1 ; CALL NUM(I,J,K) ; ENDDO
      DO K=NK,NK+1 ; CALL NUM(I,J,K) ; ENDDO
   ENDDO
ENDDO
NC = CNT

CONTAINS
   SUBROUTINE NUM(I,J,K)
   INTEGER, INTENT(IN) :: I,J,K
   IF (M%CELL_INDEX(I,J,K)==0) THEN ; CNT = CNT+1 ; M%CELL_INDEX(I,J,K) = CNT ; ENDIF
   END SUBROUTINE NUM

END SUBROUTINE NUMBER_CELLS
END MODULE FDS_FINE_LEVEL
