!> Derived copy of the FDS subroutine DENSITY (mass.f90:365-768 and CLIP_PASSIVE_SCALARS 966-989), split at the CHECK_MASS_DENSITY call so that
!> the layout-independent gather clip (fds_clip_gather.f90, D-031) can run between the two halves. GENERATED by tools/gen_density_split.py;
!> the FDS file itself is NOT edited and stays the reference (the unmodified DENSITY is also callable from the shim for comparison).
!>  * DENSITY_PRE_CLIP  = mass.f90:365-513 (predictor, up to RHOS=SUM(ZZS)) + 584-695 (corrector, up to RHO=SUM(ZZ)).
!>  * DENSITY_POST_CLIP = mass.f90:365-397 (declarations, early returns, POINT_TO_MESH) + 522-582 + 704-764 + 768 + CLIP_PASSIVE_SCALARS.
!>  * the two CALL CHECK_MASS_DENSITY (mass.f90:518, 700) are removed; the driver runs the gather clip in between. !$OMP lines are dropped.
!>
!> Kernel-facing rules (M2a): (a) passive scalars (N_TOTAL_SCALARS beyond the tracked species) are handled by Fields.cpp (ZZ/ZZS carry
!> ncomp=N_TOTAL_SCALARS); the copied code loops over 1:N_TOTAL_SCALARS unchanged. (b) only uniform Cartesian metrics are used; R(I)/RRN(I)
!> stay as FDS set them (=1) and CYLINDRICAL or TRN* meshes are rejected at level-0 assembly.
MODULE FDS_DENSITY_SPLIT

USE PRECISION_PARAMETERS
USE GLOBAL_CONSTANTS
USE MESH_POINTERS
USE COMP_FUNCTIONS, ONLY: CURRENT_TIME

IMPLICIT NONE (TYPE,EXTERNAL)
PRIVATE
PUBLIC DENSITY_PRE_CLIP, DENSITY_POST_CLIP

CONTAINS

SUBROUTINE DENSITY_PRE_CLIP(T,DT,NM)

USE PHYSICAL_FUNCTIONS, ONLY : GET_SPECIFIC_GAS_CONSTANT
USE MANUFACTURED_SOLUTIONS, ONLY: VD2D_MMS_Z_OF_RHO,VD2D_MMS_Z_SRC,UF_MMS,WF_MMS,VD2D_MMS_RHO_OF_Z,VD2D_MMS_Z_SRC
USE SOOT_ROUTINES, ONLY: SETTLING_VELOCITY
USE CC_SCALARS, ONLY : SET_EXIMADVFLX_3D,ROTATED_CUBE_RHS_ZZ

INTEGER, INTENT(IN) :: NM
REAL(EB), INTENT(IN) :: T,DT
REAL(EB) :: TNOW,RHS,Q_Z,XHAT,ZHAT
REAL(EB), ALLOCATABLE, DIMENSION(:) :: ZZ_GET
INTEGER :: I,J,K,N,IW
REAL(EB), POINTER, DIMENSION(:,:,:,:) :: DEL_RHO_D_DEL_Z__0
REAL(EB), POINTER, DIMENSION(:,:,:) :: UU,VV,WW
TYPE(WALL_TYPE), POINTER :: WC
TYPE(EXTERNAL_WALL_TYPE), POINTER :: EWC
TYPE(BOUNDARY_COORD_TYPE), POINTER :: BC

IF (SOLID_PHASE_ONLY) RETURN

! If the RHS of the continuity equation does not yet satisfy the divergence constraint, return.
! This is typical of the case where an initial velocity field is specified by the user.

SELECT CASE (PERIODIC_TEST)
   CASE DEFAULT
      IF (ICYC<=1) RETURN
   CASE (5,8)
      RETURN
   CASE (4,7,11,21,22)
END SELECT

TNOW=CURRENT_TIME()
CALL POINT_TO_MESH(NM)

UU=>WORK_U
VV=>WORK_V
WW=>WORK_W
DEL_RHO_D_DEL_Z__0=>SWORK4

PREDICTOR_STEP: SELECT CASE (PREDICTOR)

CASE(.TRUE.) PREDICTOR_STEP

   IF (FIRST_PASS) THEN
      ! This IF is required because DEL_RHO_D_DEL_Z is updated to the next time level in divg within
      ! the CHANGE_TIME_STEP loop in main while we are determining the appropriate stable DT.
      IF (ANY(SPECIES_MIXTURE%DEPOSITING) .AND. (GRAVITATIONAL_SETTLING .OR. THERMOPHORETIC_SETTLING)) CALL SETTLING_VELOCITY(NM)
      DEL_RHO_D_DEL_Z__0 = DEL_RHO_D_DEL_Z
   ENDIF

   ! Correct boundary velocity at wall cells

   UU=U
   VV=V
   WW=W


   WALL_LOOP: DO IW=1,N_EXTERNAL_WALL_CELLS
      WC=>WALL(IW)
      IF (WC%BOUNDARY_TYPE/=INTERPOLATED_BOUNDARY) CYCLE WALL_LOOP
      BC=>BOUNDARY_COORD(WC%BC_INDEX)
      SELECT CASE(BC%IOR)
         CASE( 1); UU(BC%IIG-1,BC%JJG  ,BC%KKG  ) = UVW_SAVE(IW)
         CASE(-1); UU(BC%IIG  ,BC%JJG  ,BC%KKG  ) = UVW_SAVE(IW)
         CASE( 2); VV(BC%IIG  ,BC%JJG-1,BC%KKG  ) = UVW_SAVE(IW)
         CASE(-2); VV(BC%IIG  ,BC%JJG  ,BC%KKG  ) = UVW_SAVE(IW)
         CASE( 3); WW(BC%IIG  ,BC%JJG  ,BC%KKG-1) = UVW_SAVE(IW)
         CASE(-3); WW(BC%IIG  ,BC%JJG  ,BC%KKG  ) = UVW_SAVE(IW)
      END SELECT
   ENDDO WALL_LOOP

   ! Predictor step for mass density

   DO N=1,N_TOTAL_SCALARS
      DO K=1,KBAR
         DO J=1,JBAR
            DO I=1,IBAR
               IF (CELL(CELL_INDEX(I,J,K))%SOLID) CYCLE
               RHS = - DEL_RHO_D_DEL_Z__0(I,J,K,N) &
                   + (FX(I,J,K,N)*UU(I,J,K)*R(I) - FX(I-1,J,K,N)*UU(I-1,J,K)*R(I-1))*RDX(I)*RRN(I) &
                   + (FY(I,J,K,N)*VV(I,J,K)      - FY(I,J-1,K,N)*VV(I,J-1,K)       )*RDY(J)        &
                   + (FZ(I,J,K,N)*WW(I,J,K)      - FZ(I,J,K-1,N)*WW(I,J,K-1)       )*RDZ(K)
               ZZS(I,J,K,N) = RHO(I,J,K)*ZZ(I,J,K,N) - DT*RHS
            ENDDO
         ENDDO
      ENDDO
   ENDDO


   IF (CC_IBM) CALL SET_EXIMADVFLX_3D(NM,UU,VV,WW)
   IF (STORE_SPECIES_FLUX) THEN
      DO N=1,N_TOTAL_SCALARS
         DO K=0,KBAR
            DO J=0,JBAR
               DO I=0,IBAR
                  ADV_FX(I,J,K,N) = FX(I,J,K,N)*UU(I,J,K)
                  ADV_FY(I,J,K,N) = FY(I,J,K,N)*VV(I,J,K)
                  ADV_FZ(I,J,K,N) = FZ(I,J,K,N)*WW(I,J,K)
               ENDDO
            ENDDO
         ENDDO
      ENDDO
   ENDIF

   ! Add gas production source term

   IF (ALLOCATED(MESHES(NM)%M_DOT_PPP)) ZZS(0:IBP1,0:JBP1,0:KBP1,1:N_TRACKED_SPECIES) = &
                                        ZZS(0:IBP1,0:JBP1,0:KBP1,1:N_TRACKED_SPECIES) + &
                                        DT*M_DOT_PPP(0:IBP1,0:JBP1,0:KBP1,1:N_TRACKED_SPECIES)

   ! Manufactured solution

   IF (PERIODIC_TEST==7) THEN
      DO K=1,KBAR
         DO J=1,JBAR
            DO I=1,IBAR
               ! divergence from EOS
               XHAT = XC(I) - UF_MMS*T
               ZHAT = ZC(K) - WF_MMS*T
               Q_Z = VD2D_MMS_Z_SRC(XHAT,ZHAT,T)
               ZZS(I,J,K,1) = ZZS(I,J,K,1) - DT*Q_Z
               ZZS(I,J,K,2) = ZZS(I,J,K,2) + DT*Q_Z
            ENDDO
         ENDDO
      ENDDO
   ELSEIF(PERIODIC_TEST==21 .OR. PERIODIC_TEST==22 .OR. PERIODIC_TEST==23) THEN
      CALL ROTATED_CUBE_RHS_ZZ(T,DT,NM)
   ENDIF


   ! Get rho = sum(rho*Y_alpha)

   DO K=1,KBAR
      DO J=1,JBAR
         DO I=1,IBAR
            IF (CELL(CELL_INDEX(I,J,K))%SOLID) CYCLE
            RHOS(I,J,K) = SUM(ZZS(I,J,K,1:N_TRACKED_SPECIES))
         ENDDO
      ENDDO
   ENDDO
   ! ---- mass.f90:515-520 CALL CHECK_MASS_DENSITY removed (gather clip in the driver); continues in DENSITY_POST_CLIP ----

CASE(.FALSE.) PREDICTOR_STEP  ! CORRECTOR step

   ! Correct boundary velocity at wall cells

   UU=US
   VV=VS
   WW=WS


   WALL_LOOP_2: DO IW=1,N_EXTERNAL_WALL_CELLS
      WC => WALL(IW)
      EWC => EXTERNAL_WALL(IW)
      IF (EWC%BOUNDARY_TYPE_PREVIOUS/=INTERPOLATED_BOUNDARY) CYCLE WALL_LOOP_2
      BC => BOUNDARY_COORD(WC%BC_INDEX)
      SELECT CASE(BC%IOR)
         CASE( 1); UU(BC%IIG-1,BC%JJG  ,BC%KKG  ) = UVW_SAVE(IW)
         CASE(-1); UU(BC%IIG  ,BC%JJG  ,BC%KKG  ) = UVW_SAVE(IW)
         CASE( 2); VV(BC%IIG  ,BC%JJG-1,BC%KKG  ) = UVW_SAVE(IW)
         CASE(-2); VV(BC%IIG  ,BC%JJG  ,BC%KKG  ) = UVW_SAVE(IW)
         CASE( 3); WW(BC%IIG  ,BC%JJG  ,BC%KKG-1) = UVW_SAVE(IW)
         CASE(-3); WW(BC%IIG  ,BC%JJG  ,BC%KKG  ) = UVW_SAVE(IW)
      END SELECT
   ENDDO WALL_LOOP_2

   IF (ANY(SPECIES_MIXTURE%DEPOSITING) .AND. (GRAVITATIONAL_SETTLING .OR. THERMOPHORETIC_SETTLING)) CALL SETTLING_VELOCITY(NM)

   ! Compute species mass density at the next time step

   DO N=1,N_TOTAL_SCALARS
      DO K=1,KBAR
         DO J=1,JBAR
            DO I=1,IBAR
               IF (CELL(CELL_INDEX(I,J,K))%SOLID) CYCLE
               RHS = - DEL_RHO_D_DEL_Z(I,J,K,N) &
                   + (FX(I,J,K,N)*UU(I,J,K)*R(I) - FX(I-1,J,K,N)*UU(I-1,J,K)*R(I-1))*RDX(I)*RRN(I) &
                   + (FY(I,J,K,N)*VV(I,J,K)      - FY(I,J-1,K,N)*VV(I,J-1,K)       )*RDY(J)        &
                   + (FZ(I,J,K,N)*WW(I,J,K)      - FZ(I,J,K-1,N)*WW(I,J,K-1)       )*RDZ(K)
               ZZ(I,J,K,N) = .5_EB*( RHO(I,J,K)*ZZ(I,J,K,N) + RHOS(I,J,K)*ZZS(I,J,K,N) - DT*RHS )
            ENDDO
         ENDDO
      ENDDO
   ENDDO


   ! Add gas production source term

   IF (ALLOCATED(MESHES(NM)%M_DOT_PPP)) THEN
      ZZ(0:IBP1,0:JBP1,0:KBP1,1:N_TRACKED_SPECIES) = ZZ(0:IBP1,0:JBP1,0:KBP1,1:N_TRACKED_SPECIES) + &
                                                     0.5_EB*DT*M_DOT_PPP(0:IBP1,0:JBP1,0:KBP1,1:N_TRACKED_SPECIES)
      IF (.NOT. CC_IBM) THEN ! We will use these for Regular cells in cut-cell region in CC_DENSITY.
         M_DOT_PPP = 0._EB
         D_SOURCE  = 0._EB
      ENDIF
   ENDIF

   IF (CC_IBM) CALL SET_EXIMADVFLX_3D(NM,UU,VV,WW)
   IF (STORE_SPECIES_FLUX) THEN
      DO N=1,N_TOTAL_SCALARS
         DO K=0,KBAR
            DO J=0,JBAR
               DO I=0,IBAR
                  ADV_FX(I,J,K,N) = 0.5_EB*( ADV_FX(I,J,K,N) + FX(I,J,K,N)*UU(I,J,K) )
                  ADV_FY(I,J,K,N) = 0.5_EB*( ADV_FY(I,J,K,N) + FY(I,J,K,N)*VV(I,J,K) )
                  ADV_FZ(I,J,K,N) = 0.5_EB*( ADV_FZ(I,J,K,N) + FZ(I,J,K,N)*WW(I,J,K) )
               ENDDO
            ENDDO
         ENDDO
      ENDDO
   ENDIF

   ! Manufactured solution

   IF (PERIODIC_TEST==7) THEN
      DO K=1,KBAR
         DO J=1,JBAR
            DO I=1,IBAR
               ! divergence from EOS
               XHAT = XC(I) - UF_MMS*T
               ZHAT = ZC(K) - WF_MMS*T
               Q_Z = VD2D_MMS_Z_SRC(XHAT,ZHAT,T)
               ZZ(I,J,K,1) = ZZ(I,J,K,1) - .5_EB*DT*Q_Z
               ZZ(I,J,K,2) = ZZ(I,J,K,2) + .5_EB*DT*Q_Z
            ENDDO
         ENDDO
      ENDDO
   ELSEIF(PERIODIC_TEST==21 .OR. PERIODIC_TEST==22 .OR. PERIODIC_TEST==23) THEN
      CALL ROTATED_CUBE_RHS_ZZ(T,DT,NM)
   ENDIF

   ! Get rho = sum(rho*Y_alpha)


   DO K=1,KBAR
      DO J=1,JBAR
         DO I=1,IBAR
            IF (CELL(CELL_INDEX(I,J,K))%SOLID) CYCLE
            RHO(I,J,K) = SUM(ZZ(I,J,K,1:N_TRACKED_SPECIES))
         ENDDO
      ENDDO
   ENDDO
   ! ---- mass.f90:697-702 CALL CHECK_MASS_DENSITY removed; continues in DENSITY_POST_CLIP ----
END SELECT PREDICTOR_STEP

END SUBROUTINE DENSITY_PRE_CLIP


SUBROUTINE DENSITY_POST_CLIP(T,DT,NM)

USE PHYSICAL_FUNCTIONS, ONLY : GET_SPECIFIC_GAS_CONSTANT
USE MANUFACTURED_SOLUTIONS, ONLY: VD2D_MMS_Z_OF_RHO,VD2D_MMS_Z_SRC,UF_MMS,WF_MMS,VD2D_MMS_RHO_OF_Z,VD2D_MMS_Z_SRC
USE SOOT_ROUTINES, ONLY: SETTLING_VELOCITY
USE CC_SCALARS, ONLY : SET_EXIMADVFLX_3D,ROTATED_CUBE_RHS_ZZ

INTEGER, INTENT(IN) :: NM
REAL(EB), INTENT(IN) :: T,DT
REAL(EB) :: TNOW,RHS,Q_Z,XHAT,ZHAT
REAL(EB), ALLOCATABLE, DIMENSION(:) :: ZZ_GET
INTEGER :: I,J,K,N,IW
REAL(EB), POINTER, DIMENSION(:,:,:,:) :: DEL_RHO_D_DEL_Z__0
REAL(EB), POINTER, DIMENSION(:,:,:) :: UU,VV,WW
TYPE(WALL_TYPE), POINTER :: WC
TYPE(EXTERNAL_WALL_TYPE), POINTER :: EWC
TYPE(BOUNDARY_COORD_TYPE), POINTER :: BC

IF (SOLID_PHASE_ONLY) RETURN

! If the RHS of the continuity equation does not yet satisfy the divergence constraint, return.
! This is typical of the case where an initial velocity field is specified by the user.

SELECT CASE (PERIODIC_TEST)
   CASE DEFAULT
      IF (ICYC<=1) RETURN
   CASE (5,8)
      RETURN
   CASE (4,7,11,21,22)
END SELECT

TNOW=CURRENT_TIME()
CALL POINT_TO_MESH(NM)

PREDICTOR_STEP: SELECT CASE (PREDICTOR)

CASE(.TRUE.) PREDICTOR_STEP

   ALLOCATE(ZZ_GET(1:N_TOTAL_SCALARS))

   ! Extract mass fraction from RHO * ZZ

   DO K=1,KBAR
      DO J=1,JBAR
         DO I=1,IBAR
            IF (CELL(CELL_INDEX(I,J,K))%SOLID) CYCLE
            ZZS(I,J,K,1:N_TOTAL_SCALARS) = ZZS(I,J,K,1:N_TOTAL_SCALARS)/RHOS(I,J,K)
         ENDDO
      ENDDO
   ENDDO

   ! Passive scalars

   CALL CLIP_PASSIVE_SCALARS

   ! Predict background pressure at next time step

   DO I=1,N_ZONE
      PBAR_S(:,I) = PBAR(:,I) + D_PBAR_DT(I)*DT
   ENDDO

   ! Compute molecular weight term RSUM=R0*SUM(Y_i/W_i)

   DO K=1,KBAR
      DO J=1,JBAR
         DO I=1,IBAR
            IF (CELL(CELL_INDEX(I,J,K))%SOLID) CYCLE
            ZZ_GET(1:N_TRACKED_SPECIES) = ZZS(I,J,K,1:N_TRACKED_SPECIES)
            CALL GET_SPECIFIC_GAS_CONSTANT(ZZ_GET,RSUM(I,J,K))
         ENDDO
      ENDDO
   ENDDO

   ! Extract predicted temperature at next time step from Equation of State

   DO K=1,KBAR
      DO J=1,JBAR
         DO I=1,IBAR
            IF (CELL(CELL_INDEX(I,J,K))%SOLID) CYCLE
            TMP(I,J,K) = PBAR_S(K,PRESSURE_ZONE(I,J,K))/(RSUM(I,J,K)*RHOS(I,J,K))
         ENDDO
      ENDDO
   ENDDO

   DEALLOCATE(ZZ_GET)


CASE(.FALSE.) PREDICTOR_STEP  ! CORRECTOR step

   ALLOCATE(ZZ_GET(1:N_TOTAL_SCALARS))

   ! Extract Y_n from rho*Y_n

   DO K=1,KBAR
      DO J=1,JBAR
         DO I=1,IBAR
            IF (CELL(CELL_INDEX(I,J,K))%SOLID) CYCLE
            ZZ(I,J,K,1:N_TOTAL_SCALARS) = ZZ(I,J,K,1:N_TOTAL_SCALARS)/RHO(I,J,K)
         ENDDO
      ENDDO
   ENDDO

   ! Passive scalars

   CALL CLIP_PASSIVE_SCALARS

   ! Correct background pressure

   DO I=1,N_ZONE
      PBAR(:,I) = 0.5_EB*(PBAR(:,I) + PBAR_S(:,I) + D_PBAR_DT_S(I)*DT)
   ENDDO

   ! Compute molecular weight term RSUM=R0*SUM(Y_i/W_i)

   DO K=1,KBAR
      DO J=1,JBAR
         DO I=1,IBAR
            IF (CELL(CELL_INDEX(I,J,K))%SOLID) CYCLE
            ZZ_GET(1:N_TRACKED_SPECIES) = ZZ(I,J,K,1:N_TRACKED_SPECIES)
            CALL GET_SPECIFIC_GAS_CONSTANT(ZZ_GET,RSUM(I,J,K))
         ENDDO
      ENDDO
   ENDDO

   ! Extract predicted temperature at next time step from Equation of State

   DO K=1,KBAR
      DO J=1,JBAR
         DO I=1,IBAR
            IF (CELL(CELL_INDEX(I,J,K))%SOLID) CYCLE
            TMP(I,J,K) = PBAR(K,PRESSURE_ZONE(I,J,K))/(RSUM(I,J,K)*RHO(I,J,K))
         ENDDO
      ENDDO
   ENDDO

   DEALLOCATE(ZZ_GET)


END SELECT PREDICTOR_STEP

T_USED(3)=T_USED(3)+CURRENT_TIME()-TNOW

CONTAINS

SUBROUTINE CLIP_PASSIVE_SCALARS

! Currently only set up for unmixed fraction, zeta

REAL(EB), POINTER, DIMENSION(:,:,:,:) :: ZZP

IF (N_PASSIVE_SCALARS==0) RETURN

IF (PREDICTOR) THEN
   ZZP=>ZZS
ELSE
   ZZP=>ZZ
ENDIF

DO K=1,KBAR
   DO J=1,JBAR
      DO I=1,IBAR
         IF (CELL(CELL_INDEX(I,J,K))%SOLID) CYCLE
         ZZP(I,J,K,ZETA_INDEX) = MAX(0._EB,MIN(1._EB,ZZP(I,J,K,ZETA_INDEX)))
      ENDDO
   ENDDO
ENDDO

END SUBROUTINE CLIP_PASSIVE_SCALARS

END SUBROUTINE DENSITY_POST_CLIP

END MODULE FDS_DENSITY_SPLIT
