#!/bin/bash
# Regression cases for the three periodic-only driver bugs (S8.3), on the periodic csmag_32 variant (FISHPAK_BC=0,0,0) of the official baseline.
# usage: run_periodic_regression.sh <driver-build> <work>
#   periodic_face_match   the periodic domain-face velocity match (FDS MATCH_VELOCITY, GhostExchange match_periodic_faces) is applied
#   mu_edge_corner        MU in the domain edge and corner cells is FDS's clamped copy, not a periodic image
#   kres_edge_corner      the same for KRES
# Run on 1 rank (leg A: the official single-box baseline, end-to-end check included) and on 4 ranks (leg B: the same 32^3 periodic LES problem as 2x2x1 boxes,
# generated by make_periodic_case.py; box-layout aware invariants, no reference-binary comparison because the reference with four meshes is a different discretisation).
# Each case has a positive and a negative leg:
#   positive: the driver as built passes the invariant of tests/check_periodic_raw.py (read from the FDSTL_STAGEG dump of cycle 2), and the whole run still matches the
#             reference-binary restart file (m2a_compare.py csmag, the gates of the M2a report).
#   negative: the driver run with the fix switched off (env FDSTL_SKIP_FIX=match|mu|kres, a fault-injection switch of GhostExchange.cpp, default off) must VIOLATE the
#             invariant. This proves the test can see the bug. For match and mu the end-to-end comparison must FAIL as well. KRES in the edge cells does not reach any
#             field of this case (no model here reads it), so only the stage invariant is the test for kres_edge_corner.
set -u
HERE=$(cd "$(dirname "$0")" && pwd); source "$HERE/env.sh" > /dev/null 2>&1
B=$1; W=$2; BL=$BASELINE; REF=${REFBIN:-$(dirname "$BL")/../refbin/gnu_ompi_firex-36975d7/fds}; REF=$(readlink -f "$REF"); rc=0
CASE=csmag_32__fishpak_bc000; SRC=$BL/$CASE
[ -x "$REF" ] || { echo "reference binary not found: $REF"; exit 2; }
[ -d "$SRC" ] || { echo "baseline not found: $SRC"; exit 2; }
mkdir -p "$W"
d=$W/ref; rm -rf "$d"; mkdir -p "$d"; cp "$SRC/csmag_32.fds" "$SRC/cbc32_uvw.csv" "$d/"
(cd "$d" && mpirun --bind-to none -np 1 "$REF" csmag_32.fds > stdout.txt 2> stderr.txt) || { echo "REFERENCE RUN FAILED"; exit 2; }
cmp -s "$d/csmag_32_devc.csv" "$SRC/csmag_32_devc.csv" || { echo "reference rerun differs from the baseline devc"; exit 2; }
drv() { # label skip
  local out=$W/$1; rm -rf "$out"; mkdir -p "$out"; cp "$SRC/csmag_32.fds" "$SRC/cbc32_uvw.csv" "$out/"
  (cd "$out" && FDSTL_SKIP_FIX=$2 FDSTL_STAGEG=2 mpirun --bind-to none -np 1 "$B/fds_amr" csmag_32.fds --run --outdir . --chid csmag_32 --quiet > stdout.txt 2> stderr.txt) || { echo "DRIVER RUN FAILED $1"; rc=1; }
}
e2e() { python3 "$HERE/m2a_compare.py" csmag "$W/$1" "$SRC" csmag_32 --restart "$W/ref/csmag_32_1.restart" > "$W/$1/compare.txt" 2>&1; }
drv base ""; e2e base
if grep -q "M2A COMPARE csmag PASS" "$W/base/compare.txt"; then echo "[base] end-to-end vs reference restart: PASS"; else echo "[base] end-to-end vs reference restart: FAIL"; rc=1; fi
for c in periodic_face_match:match mu_edge_corner:mu kres_edge_corner:kres; do
  name=${c%%:*}; sk=${c##*:}; chk=$name; [ $name = periodic_face_match ] && chk=face_match
  if python3 "$HERE/check_periodic_raw.py" "$W/base" $chk > "$W/base/$name.txt" 2>&1; then echo "[$name] positive leg (fix on): PASS"; else echo "[$name] positive leg (fix on): FAIL"; cat "$W/base/$name.txt"; rc=1; fi
  drv "skip_$sk" $sk
  if python3 "$HERE/check_periodic_raw.py" "$W/skip_$sk" $chk > "$W/skip_$sk/$name.txt" 2>&1; then echo "[$name] negative leg (fix off): NOT DETECTED -> FAIL"; rc=1; else echo "[$name] negative leg (fix off): invariant violated as it must be: PASS ($(grep -o 'VIOLATED ([0-9]*)' "$W/skip_$sk/$name.txt"))"; fi
  if [ $sk != kres ]; then
    e2e "skip_$sk"
    if grep -q "M2A COMPARE csmag PASS" "$W/skip_$sk/compare.txt"; then echo "[$name] end-to-end with fix off: NOT DETECTED -> FAIL"; rc=1; else echo "[$name] end-to-end with fix off: differs from the reference restart as it must: PASS"; fi
  fi
done
# ---- leg B: 4 ranks, 2x2x1 boxes
python3 "$HERE/make_periodic_case.py" 32 "$W/case4" 0.1 2 2 1 > /dev/null
drv4() { # label skip
  local out=$W/$1; rm -rf "$out"; mkdir -p "$out"; cp "$W"/case4/tg32* "$out/"
  (cd "$out" && FDSTL_SKIP_FIX=$2 FDSTL_STAGEG=2 mpirun --bind-to none --oversubscribe -np 4 "$B/fds_amr" tg32.fds --run --outdir . --chid tg32 --quiet --steps 3 > stdout.txt 2> stderr.txt) || { echo "DRIVER RUN FAILED $1"; rc=1; }
}
drv4 base4 ""
for c in periodic_face_match:match mu_edge_corner:mu kres_edge_corner:kres; do
  name=${c%%:*}; sk=${c##*:}; chk=$name; [ $name = periodic_face_match ] && chk=face_match
  if python3 "$HERE/check_periodic_raw.py" "$W/base4" $chk > "$W/base4/$name.txt" 2>&1; then echo "[$name np=4, 4 boxes] positive leg (fix on): PASS"; else echo "[$name np=4] positive leg (fix on): FAIL"; cat "$W/base4/$name.txt"; rc=1; fi
  drv4 "skip4_$sk" $sk
  if python3 "$HERE/check_periodic_raw.py" "$W/skip4_$sk" $chk > "$W/skip4_$sk/$name.txt" 2>&1; then echo "[$name np=4] negative leg (fix off): NOT DETECTED -> FAIL"; rc=1; else echo "[$name np=4] negative leg (fix off): invariant violated as it must be: PASS ($(grep -o 'VIOLATED ([0-9]*)' "$W/skip4_$sk/$name.txt"))"; fi
done
[ $rc = 0 ] && echo "PERIODIC REGRESSION PASS" || echo "PERIODIC REGRESSION FAIL"
exit $rc
