!> \brief DRAFT (D-056 option B), compiled only with -DFDS_AMR_FINE_B_DRAFT=ON on a tree with patches 0007 and 0008 applied; never part of the default build and not used for physics.
!> Shadow test of the fine-level stage functions: with the shadow switched on, every level-0 kernel call (visc, dens, dens_pre, dens_post, vflux, div1, div2, vpred, vcorr) is repeated on
!> a fine-level box FINE_LEVEL(1)%BOX(1) reached through POINT_TO_BOX (mesh number NMESHES+1, patch 0008), started from a deep copy of the level-0 mesh object taken before the kernel
!> (so the metrics, wall/edge tables and all state arrays are bitwise those of the level-0 box, which covers the whole domain), and the results are compared bit by bit.
!> This exercises the routing of the kernels to level > 0 (POINT_TO_BOX, per-mesh-number arrays, M_DOT_PPP lookup), not the build of the fine-box contents (FDS_FINE_BOX_B_BUILD, below).
MODULE FDS_FINE_BOX_B

USE ISO_C_BINDING
USE PRECISION_PARAMETERS, ONLY: EB
USE GLOBAL_CONSTANTS, ONLY: NMESHES,CHANGE_TIME_STEP_INDEX,N_TOTAL_SCALARS,FLUX_LIMITER_MW_CORRECTION,N_TRACKED_SPECIES,TMPA,RHOA,RSUM0,U0,V0,W0,PARTICLE_DRAG,CHECK_VN,REAC_SOURCE_CHECK, &
   STORE_SPECIES_FLUX,N_ZONE,STRATIFICATION,I_RAMP_TMP0_Z,I_RAMP_P0_Z,P_INF,DSUM,USUM,PSUM,STORE_PRESSURE_POISSON_RESIDUAL,STORE_CUTCELL_DIVERGENCE,STORE_CARTESIAN_DIVERGENCE,N_LP_ARRAY_INDICES,N_REACTIONS,RADIATION,N_LAGRANGIAN_CLASSES,NULL_BOUNDARY,DEFAULT_SURF_INDEX
USE MESH_VARIABLES, ONLY: MESHES,MESH_TYPE
USE GLOBAL_CONSTANTS, ONLY: TURB_MODEL,C_SMAGORINSKY,CONSMAG,DYNSMAG
USE PHYSICAL_FUNCTIONS, ONLY: LES_FILTER_WIDTH_FUNCTION
USE TYPES, ONLY: P_ZONE,P_ZONE_TYPE
USE MATH_FUNCTIONS, ONLY: EVALUATE_RAMP
USE MESH_POINTERS, ONLY: FINE_LEVEL,FINE_LEVEL_TYPE
USE FDS_AMREX_HOOKS, ONLY: SHADOW_PROC,FDS_HOOK_SET_FINE_READY
USE FDS_KERNELS, ONLY: FDS_K_RESERVE_BOXES
USE FDS_BOX_OBJ, ONLY: FDS_FINE_B_SET_VIEW
USE VELO, ONLY: NO_FLUX,BAROCLINIC_CORRECTION,COMPUTE_VISCOSITY,VELOCITY_FLUX,VELOCITY_PREDICTOR,VELOCITY_CORRECTOR
USE MASS, ONLY: MASS_FINITE_DIFFERENCES,DENSITY
USE DIVG, ONLY: DIVERGENCE_PART_1,DIVERGENCE_PART_2
USE FDS_DENSITY_SPLIT, ONLY: DENSITY_PRE_CLIP,DENSITY_POST_CLIP

IMPLICIT NONE (TYPE,EXTERNAL)
PRIVATE
PUBLIC :: FDS_FINE_B_SHADOW_ENABLE,FDS_FINE_B_SHADOW_REPORT,BUILD_FINE_BOX

INTEGER, PARAMETER :: NK=14
CHARACTER(10), PARAMETER :: KNAME(NK) = [CHARACTER(10) :: 'visc','dens','dens_pre','dens_post','vflux','div1','div2','vpred','vcorr','p_mfd','p_dens','p_dens_pre','baroclinic','noflux']
REAL(EB), SAVE :: MAXREL(NK)=0._EB
INTEGER, SAVE :: NGHOST(NK)=0,NBAD_G(NK)=0,NCALL(NK)=0,NBAD(NK)=0,NCMP(NK)=0,NSKIP=0,NMF=0
REAL(EB), ALLOCATABLE, SAVE :: DT_NEW_SH(:)
TYPE GLOBALS_T   !< module-level FDS state that the kernels update (divergence integrals, pressure-zone DPSTAR); a repeated kernel call needs the state from before the first call
   REAL(EB), ALLOCATABLE :: DSUM(:),USUM(:),PSUM(:)
   TYPE(P_ZONE_TYPE), ALLOCATABLE :: PZ(:)
END TYPE GLOBALS_T
TYPE(GLOBALS_T), SAVE :: G0,G1
LOGICAL, SAVE :: DEBUG_LOC=.FALSE.
LOGICAL, SAVE :: ON=.FALSE.,BUILD=.FALSE.   !< BUILD: the fine box is made by BUILD_FINE_BOX (contents only from the tables below), not copied from the level-0 box

CONTAINS

!> Switch the shadow on: one fine level with one box (the whole-domain copy), mesh number NMESHES+1; needs a single level-0 mesh.
FUNCTION FDS_FINE_B_SHADOW_ENABLE(MODE) RESULT(IERR) BIND(C,NAME='fds_fine_b_shadow_enable')

INTEGER(C_INT), VALUE :: MODE   !< 0: the fine box is a deep copy of the level-0 box (routing test); 1: the fine box is built by BUILD_FINE_BOX and only the state arrays are copied
INTEGER(C_INT) :: IERR
TYPE(MESH_TYPE), POINTER :: R

IERR = 0
IF (NMESHES/=1) THEN ; IERR = 1 ; RETURN ; ENDIF
IF (.NOT.ALLOCATED(FINE_LEVEL)) ALLOCATE(FINE_LEVEL(1))
NMF = NMESHES+1
FINE_LEVEL(1)%NM0 = NMESHES ; FINE_LEVEL(1)%N_BOXES = 1
IF (.NOT.ALLOCATED(FINE_LEVEL(1)%BOX)) ALLOCATE(FINE_LEVEL(1)%BOX(1),FINE_LEVEL(1)%VIEW(1))
CALL FDS_K_RESERVE_BOXES(INT(NMF,C_INT))
ALLOCATE(DT_NEW_SH(NMF)) ; DT_NEW_SH = 0._EB
CALL FDS_HOOK_SET_FINE_READY(1_C_INT)
SHADOW_PROC => SHADOW
BUILD = (MODE==1)
IF (BUILD) THEN
   R => MESHES(1)
   CALL BUILD_FINE_BOX(FINE_LEVEL(1)%BOX(1),R%IBAR,R%JBAR,R%KBAR,R%XS,R%XF,R%YS,R%YF,R%ZS,R%ZF)
   CALL AUDIT_BUILT_BOX(R,FINE_LEVEL(1)%BOX(1))
   CALL BIND_OWN_VIEWS(FINE_LEVEL(1)%BOX(1))   ! the kernels then run through the second array's views, as they will on AMReX data (FDS_FINE_B_SET_VIEW)
ENDIF
ON = .TRUE.

END FUNCTION FDS_FINE_B_SHADOW_ENABLE

!> Bind the views of fine box 1 to the box's own state arrays through the C-callable FDS_FINE_B_SET_VIEW (exercises that entry point and the POINT_TO_BOX view path).
SUBROUTINE BIND_OWN_VIEWS(F)

TYPE(MESH_TYPE), INTENT(INOUT), TARGET :: F

CALL BIND3(1,F%U,LBOUND(F%U),SHAPE(F%U)) ; CALL BIND3(2,F%V,LBOUND(F%V),SHAPE(F%V)) ; CALL BIND3(3,F%W,LBOUND(F%W),SHAPE(F%W))
CALL BIND3(4,F%US,LBOUND(F%US),SHAPE(F%US)) ; CALL BIND3(5,F%VS,LBOUND(F%VS),SHAPE(F%VS)) ; CALL BIND3(6,F%WS,LBOUND(F%WS),SHAPE(F%WS))
CALL BIND3(7,F%D,LBOUND(F%D),SHAPE(F%D)) ; CALL BIND3(8,F%DS,LBOUND(F%DS),SHAPE(F%DS)) ; CALL BIND3(9,F%H,LBOUND(F%H),SHAPE(F%H)) ; CALL BIND3(10,F%HS,LBOUND(F%HS),SHAPE(F%HS)) ; CALL BIND3(11,F%KRES,LBOUND(F%KRES),SHAPE(F%KRES))
CALL BIND3(12,F%FVX,LBOUND(F%FVX),SHAPE(F%FVX)) ; CALL BIND3(13,F%FVY,LBOUND(F%FVY),SHAPE(F%FVY)) ; CALL BIND3(14,F%FVZ,LBOUND(F%FVZ),SHAPE(F%FVZ))
CALL BIND3(15,F%RHO,LBOUND(F%RHO),SHAPE(F%RHO)) ; CALL BIND3(16,F%RHOS,LBOUND(F%RHOS),SHAPE(F%RHOS)) ; CALL BIND3(17,F%MU,LBOUND(F%MU),SHAPE(F%MU)) ; CALL BIND3(18,F%TMP,LBOUND(F%TMP),SHAPE(F%TMP))
CALL BIND3(19,F%Q,LBOUND(F%Q),SHAPE(F%Q)) ; CALL BIND3(20,F%RSUM,LBOUND(F%RSUM),SHAPE(F%RSUM))

END SUBROUTINE BIND_OWN_VIEWS

SUBROUTINE BIND3(WHICH,A,LB,SH)
INTEGER, INTENT(IN) :: WHICH,LB(3),SH(3)
REAL(EB), INTENT(IN), TARGET :: A(LB(1):LB(1)+SH(1)-1,LB(2):LB(2)+SH(2)-1,LB(3):LB(3)+SH(3)-1)   ! explicit shape: the address of the box's own array, no copy
INTEGER(C_INT) :: LB4(4),EXT4(4),IERR
LB4 = [INT(LB(1),C_INT),INT(LB(2),C_INT),INT(LB(3),C_INT),1_C_INT]
EXT4 = [INT(SIZE(A,1),C_INT),INT(SIZE(A,2),C_INT),INT(SIZE(A,3),C_INT),1_C_INT]
IERR = FDS_FINE_B_SET_VIEW(1_C_INT,1_C_INT,INT(WHICH,C_INT),LB4,EXT4,C_LOC(A))
IF (IERR/=0) THEN ; WRITE(0,'(A,I0,A,I0)') 'fine-b shadow: FDS_FINE_B_SET_VIEW failed for WHICH=',WHICH,' ierr=',IERR ; ERROR STOP 1 ; ENDIF
END SUBROUTINE BIND3

SUBROUTINE SHADOW(PHASE,KIND,NM,T,DT,EST,DTNEW,ICHG)

INTEGER, INTENT(IN) :: PHASE,KIND,NM,EST,ICHG
REAL(EB), INTENT(IN) :: T,DT,DTNEW
TYPE(MESH_TYPE), POINTER :: R,F

IF (.NOT.ON) RETURN
IF (NM/=1) THEN
   IF (PHASE==0) NSKIP = NSKIP+1
   RETURN
ENDIF
R => MESHES(1) ; F => FINE_LEVEL(1)%BOX(1)
IF (PHASE==0) THEN
   IF (BUILD) THEN
      CALL COPY_STATE(R,F)               ! built box: only the state arrays (incl. ghost layers) and the scalars the kernels carry between calls
   ELSE
      F = R                              ! deep copy of the level-0 mesh object (state arrays incl. ghost layers, metrics, tables, scalars)
   ENDIF
   CHANGE_TIME_STEP_INDEX(NMF) = CHANGE_TIME_STEP_INDEX(1)
   CALL SAVE_GLOBALS(G0)
   RETURN
ENDIF
CALL SAVE_GLOBALS(G1) ; CALL RESTORE_GLOBALS(G0)       ! the level-0 kernel has run: keep its global effects, run the fine kernel from the same global state
NCALL(KIND) = NCALL(KIND)+1
SELECT CASE(KIND)
   CASE(1) ; CALL COMPUTE_VISCOSITY(NMF,APPLY_TO_ESTIMATED_VARIABLES=(EST/=0))
   CASE(2) ; CALL MASS_FINITE_DIFFERENCES(NMF) ; CALL DENSITY(T,DT,NMF)
   CASE(3) ; CALL MASS_FINITE_DIFFERENCES(NMF) ; CALL DENSITY_PRE_CLIP(T,DT,NMF)
   CASE(4) ; CALL DENSITY_POST_CLIP(T,DT,NMF)
   CASE(5) ; CALL VELOCITY_FLUX(T,DT,NMF,APPLY_TO_ESTIMATED_VARIABLES=(EST/=0))
   CASE(6) ; CALL DIVERGENCE_PART_1(T,DT,NMF)
   CASE(7) ; CALL DIVERGENCE_PART_2(DT,NMF)
   CASE(8)
      DT_NEW_SH = DT ; CHANGE_TIME_STEP_INDEX(NMF) = 0
      CALL VELOCITY_PREDICTOR(T,DT,DT_NEW_SH,NMF)
      IF (DT_NEW_SH(NMF)/=DTNEW) CALL BAD(KIND,'DT_NEW')
      IF (CHANGE_TIME_STEP_INDEX(NMF)/=ICHG) CALL BAD(KIND,'CHANGE_TIME_STEP_INDEX')
      IF (F%CFL/=R%CFL .OR. F%VN/=R%VN) CALL BAD(KIND,'CFL/VN')
   CASE(9) ; CALL VELOCITY_CORRECTOR(T,DT,NMF)
   CASE(10) ; CALL MASS_FINITE_DIFFERENCES(NMF)
   CASE(11) ; CALL DENSITY(T,DT,NMF)
   CASE(12) ; CALL DENSITY_PRE_CLIP(T,DT,NMF)
   CASE(13) ; CALL BAROCLINIC_CORRECTION(T,NMF)
   CASE(14) ; CALL NO_FLUX(DT,NMF)
END SELECT
IF (F%CLIP_RHOMIN.NEQV.R%CLIP_RHOMIN .OR. F%CLIP_RHOMAX.NEQV.R%CLIP_RHOMAX) CALL BAD(KIND,'CLIP flags')
IF (F%DT_RESTRICT_COUNT/=R%DT_RESTRICT_COUNT) CALL BAD(KIND,'DT_RESTRICT_COUNT')
CALL CMP3(KIND,'U',R%U,F%U,LBOUND(R%U),LBOUND(F%U))   ; CALL CMP3(KIND,'V',R%V,F%V,LBOUND(R%V),LBOUND(F%V))   ; CALL CMP3(KIND,'W',R%W,F%W,LBOUND(R%W),LBOUND(F%W))
CALL CMP3(KIND,'US',R%US,F%US,LBOUND(R%US),LBOUND(F%US)) ; CALL CMP3(KIND,'VS',R%VS,F%VS,LBOUND(R%VS),LBOUND(F%VS)) ; CALL CMP3(KIND,'WS',R%WS,F%WS,LBOUND(R%WS),LBOUND(F%WS))
CALL CMP3(KIND,'FVX',R%FVX,F%FVX,LBOUND(R%FVX),LBOUND(F%FVX)) ; CALL CMP3(KIND,'FVY',R%FVY,F%FVY,LBOUND(R%FVY),LBOUND(F%FVY)) ; CALL CMP3(KIND,'FVZ',R%FVZ,F%FVZ,LBOUND(R%FVZ),LBOUND(F%FVZ))
CALL CMP3(KIND,'H',R%H,F%H,LBOUND(R%H),LBOUND(F%H)) ; CALL CMP3(KIND,'HS',R%HS,F%HS,LBOUND(R%HS),LBOUND(F%HS)) ; CALL CMP3(KIND,'KRES',R%KRES,F%KRES,LBOUND(R%KRES),LBOUND(F%KRES))
CALL CMP3(KIND,'D',R%D,F%D,LBOUND(R%D),LBOUND(F%D)) ; CALL CMP3(KIND,'DS',R%DS,F%DS,LBOUND(R%DS),LBOUND(F%DS)) ; CALL CMP3(KIND,'DDDT',R%DDDT,F%DDDT,LBOUND(R%DDDT),LBOUND(F%DDDT))
CALL CMP3(KIND,'MU',R%MU,F%MU,LBOUND(R%MU),LBOUND(F%MU)) ; CALL CMP3(KIND,'STRAIN_RATE',R%STRAIN_RATE,F%STRAIN_RATE,LBOUND(R%STRAIN_RATE),LBOUND(F%STRAIN_RATE)) ; CALL CMP3(KIND,'Q',R%Q,F%Q,LBOUND(R%Q),LBOUND(F%Q))
CALL CMP3(KIND,'RHO',R%RHO,F%RHO,LBOUND(R%RHO),LBOUND(F%RHO)) ; CALL CMP3(KIND,'RHOS',R%RHOS,F%RHOS,LBOUND(R%RHOS),LBOUND(F%RHOS)) ; CALL CMP3(KIND,'TMP',R%TMP,F%TMP,LBOUND(R%TMP),LBOUND(F%TMP)) ; CALL CMP3(KIND,'RSUM',R%RSUM,F%RSUM,LBOUND(R%RSUM),LBOUND(F%RSUM))
CALL CMP4(KIND,'ZZ',R%ZZ,F%ZZ,LBOUND(R%ZZ),LBOUND(F%ZZ)) ; CALL CMP4(KIND,'ZZS',R%ZZS,F%ZZS,LBOUND(R%ZZS),LBOUND(F%ZZS))
CALL CMP4(KIND,'DEL_RHO_D_DEL_Z',R%DEL_RHO_D_DEL_Z,F%DEL_RHO_D_DEL_Z,LBOUND(R%DEL_RHO_D_DEL_Z),LBOUND(F%DEL_RHO_D_DEL_Z))
CALL SAVE_GLOBALS(G0)                                 ! effects of the fine kernel on the globals
IF (ALLOCATED(G1%DSUM)) THEN
   IF (ANY(TRANSFER(G0%DSUM,[0_C_INT64_T])/=TRANSFER(G1%DSUM,[0_C_INT64_T])) .OR. ANY(TRANSFER(G0%USUM,[0_C_INT64_T])/=TRANSFER(G1%USUM,[0_C_INT64_T])) .OR. &
       ANY(TRANSFER(G0%PSUM,[0_C_INT64_T])/=TRANSFER(G1%PSUM,[0_C_INT64_T]))) CALL BAD(KIND,'DSUM/USUM/PSUM (sums over all cells, shell cells included)',GHOST_ONLY=BUILD)
ENDIF
IF (ALLOCATED(G1%PZ)) THEN
   IF (ANY(G0%PZ%DPSTAR/=G1%PZ%DPSTAR)) CALL BAD(KIND,'P_ZONE%DPSTAR (sum over all cells)',GHOST_ONLY=BUILD)
ENDIF
CALL RESTORE_GLOBALS(G1)
CALL CMP4(KIND,'FX',R%FX,F%FX,LBOUND(R%FX),LBOUND(F%FX)) ; CALL CMP4(KIND,'FY',R%FY,F%FY,LBOUND(R%FY),LBOUND(F%FY)) ; CALL CMP4(KIND,'FZ',R%FZ,F%FZ,LBOUND(R%FZ),LBOUND(F%FZ))

END SUBROUTINE SHADOW

!> Allocate the arrays of a fine-level mesh object of NI x NJ x NK cells on [XS,XF]x[YS,YF]x[ZS,ZF] (axis-aligned, uniform, Cartesian, no obstructions) with the contents the kernels read
!> (level-interface.md section 3): metrics (the arithmetic of READ_MESH for an untransformed grid), cell tables (ghost ring SOLID/EXTERIOR as READ_OBST sets it), empty edge and wall tables
!> (a fine box has no WALL cells: its non-domain faces are interface faces whose ghost values the driver fills, and there is no OMESH neighbour), and the state, field and work arrays of
!> INITIALIZE_MESH_VARIABLES_1 (initial values as there). Models with particles or radiation are not supported on fine levels yet.
SUBROUTINE BUILD_FINE_BOX(M,NI,NJ,NK,XS,XF,YS,YF,ZS,ZF)

TYPE(MESH_TYPE), INTENT(INOUT) :: M
INTEGER, INTENT(IN) :: NI,NJ,NK
REAL(EB), INTENT(IN) :: XS,XF,YS,YF,ZS,ZF
INTEGER :: I,J,K,IC,NC,IBP1,JBP1,KBP1,N_LOWER_SCALARS

IF (RADIATION .OR. N_LAGRANGIAN_CLASSES>0 .OR. N_LP_ARRAY_INDICES>0) THEN
   WRITE(0,'(A)') 'fds_amr ERROR in BUILD_FINE_BOX: fine-level boxes do not support particles or radiation yet.' ; ERROR STOP 1
ENDIF
N_LOWER_SCALARS = MERGE(0,1,FLUX_LIMITER_MW_CORRECTION)   ! as in INITIALIZE_MESH_VARIABLES_1
M%IBAR=NI ; M%JBAR=NJ ; M%KBAR=NK ; M%IBM1=NI-1 ; M%JBM1=NJ-1 ; M%KBM1=NK-1 ; M%IBP1=NI+1 ; M%JBP1=NJ+1 ; M%KBP1=NK+1
IBP1=M%IBP1 ; JBP1=M%JBP1 ; KBP1=M%KBP1
M%XS=XS ; M%XF=XF ; M%YS=YS ; M%YF=YF ; M%ZS=ZS ; M%ZF=ZF
M%DXI=(XF-XS)/REAL(NI,EB) ; M%DETA=(YF-YS)/REAL(NJ,EB) ; M%DZETA=(ZF-ZS)/REAL(NK,EB)
M%RDXI=1._EB/M%DXI ; M%RDETA=1._EB/M%DETA ; M%RDZETA=1._EB/M%DZETA
ALLOCATE(M%X(0:NI),M%XC(0:NI+1),M%HX(0:NI+1),M%DX(0:NI+1),M%RDX(0:NI+1),M%DXN(0:NI),M%RDXN(0:NI),M%R(0:NI),M%RC(0:NI+1),M%RRN(0:NI+1))
ALLOCATE(M%Y(0:NJ),M%YC(0:NJ+1),M%HY(0:NJ+1),M%DY(0:NJ+1),M%RDY(0:NJ+1),M%DYN(0:NJ),M%RDYN(0:NJ))
ALLOCATE(M%Z(0:NK),M%ZC(0:NK+1),M%HZ(0:NK+1),M%DZ(0:NK+1),M%RDZ(0:NK+1),M%DZN(0:NK),M%RDZN(0:NK))
M%R=1._EB ; M%RC=1._EB ; M%RRN=1._EB
CALL AXIS(NI,XS,XF,M%DXI,M%X,M%XC,M%HX,M%DX,M%RDX,M%DXN,M%RDXN,M%DXMIN)
CALL AXIS(NJ,YS,YF,M%DETA,M%Y,M%YC,M%HY,M%DY,M%RDY,M%DYN,M%RDYN,M%DYMIN)
CALL AXIS(NK,ZS,ZF,M%DZETA,M%Z,M%ZC,M%HZ,M%DZ,M%RDZ,M%DZN,M%RDZN,M%DZMIN)

! cell tables: the ghost ring gets cell numbers (READ_OBST order), is SOLID and EXTERIOR; interior cells use index 0 (CELL(0), non-solid)
ALLOCATE(M%CELL_INDEX(0:IBP1,0:JBP1,0:KBP1)) ; M%CELL_INDEX = 0
NC = 0
DO K=0,KBP1
   DO J=0,JBP1
      DO I=0,IBP1
         IF (I<=1 .OR. I>=NI .OR. J<=1 .OR. J>=NJ .OR. K<=1 .OR. K>=NK) THEN ; NC = NC+1 ; ENDIF
      ENDDO
   ENDDO
ENDDO
CALL NUMBER_CELLS(M,NI,NJ,NK,NC)
ALLOCATE(M%CELL(0:NC))
DO K=0,KBP1
   DO J=0,JBP1
      DO I=0,IBP1
         IC = M%CELL_INDEX(I,J,K)
         IF (IC>0) THEN
            M%CELL(IC)%I=I ; M%CELL(IC)%J=J ; M%CELL(IC)%K=K
            IF (I==0 .OR. I==IBP1 .OR. J==0 .OR. J==JBP1 .OR. K==0 .OR. K==KBP1) THEN ; M%CELL(IC)%SOLID=.TRUE. ; M%CELL(IC)%EXTERIOR=.TRUE. ; ENDIF
         ENDIF
      ENDDO
   ENDDO
ENDDO
ALLOCATE(M%INTERPOLATED_MESH(1:NI,1:NJ,1:NK)) ; M%INTERPOLATED_MESH = 0     ! no cell of a fine box is covered by a finer mesh (yet)
ALLOCATE(M%EDGE(0:0)) ; ALLOCATE(M%WALL(0:0),M%EXTERNAL_WALL(0),M%THIN_WALL(0:10))
M%WALL(0)%BOUNDARY_TYPE = NULL_BOUNDARY ; M%WALL(0)%SURF_INDEX = DEFAULT_SURF_INDEX
M%N_WALL_CELLS=0 ; M%N_WALL_CELLS_DIM=0 ; M%N_INTERNAL_WALL_CELLS=0 ; M%N_EXTERNAL_WALL_CELLS=0
ALLOCATE(M%UVW_SAVE(0),M%U_GHOST(0),M%V_GHOST(0),M%W_GHOST(0),M%WALL_WORK1(0),M%WALL_WORK2(0))

! state, field and work arrays (init.f90, INITIALIZE_MESH_VARIABLES_1)
ALLOCATE(M%TMP(-1:IBP1+1,-1:JBP1+1,-1:KBP1+1)) ; M%TMP = TMPA
ALLOCATE(M%RHO(-1:IBP1+1,-1:JBP1+1,-1:KBP1+1)) ; M%RHO = RHOA
ALLOCATE(M%RHOS(-1:IBP1+1,-1:JBP1+1,-1:KBP1+1)) ; M%RHOS = RHOA
ALLOCATE(M%ZZ(-1:IBP1+1,-1:JBP1+1,-1:KBP1+1,N_TOTAL_SCALARS)) ; M%ZZ = 0._EB
ALLOCATE(M%ZZS(-1:IBP1+1,-1:JBP1+1,-1:KBP1+1,N_TOTAL_SCALARS)) ; M%ZZS = 0._EB
ALLOCATE(M%WORK_PAD(-1:IBP1+1,-1:JBP1+1,-1:KBP1+1)) ; M%WORK_PAD = 0._EB
ALLOCATE(M%U(-1:IBP1,0:JBP1,0:KBP1),M%US(-1:IBP1,0:JBP1,0:KBP1),M%WORK_U(-1:IBP1,0:JBP1,0:KBP1)) ; M%U=0._EB ; M%US=0._EB ; M%WORK_U=0._EB
ALLOCATE(M%V(0:IBP1,-1:JBP1,0:KBP1),M%VS(0:IBP1,-1:JBP1,0:KBP1),M%WORK_V(0:IBP1,-1:JBP1,0:KBP1)) ; M%V=0._EB ; M%VS=0._EB ; M%WORK_V=0._EB
ALLOCATE(M%W(0:IBP1,0:JBP1,-1:KBP1),M%WS(0:IBP1,0:JBP1,-1:KBP1),M%WORK_W(0:IBP1,0:JBP1,-1:KBP1)) ; M%W=0._EB ; M%WS=0._EB ; M%WORK_W=0._EB
ALLOCATE(M%FVX(0:IBP1,0:JBP1,0:KBP1),M%FVY(0:IBP1,0:JBP1,0:KBP1),M%FVZ(0:IBP1,0:JBP1,0:KBP1)) ; M%FVX=0._EB ; M%FVY=0._EB ; M%FVZ=0._EB
ALLOCATE(M%FVX_B(0:IBP1,0:JBP1,0:KBP1),M%FVY_B(0:IBP1,0:JBP1,0:KBP1),M%FVZ_B(0:IBP1,0:JBP1,0:KBP1)) ; M%FVX_B=0._EB ; M%FVY_B=0._EB ; M%FVZ_B=0._EB
IF (PARTICLE_DRAG) THEN
   ALLOCATE(M%FVX_D(0:IBP1,0:JBP1,0:KBP1),M%FVY_D(0:IBP1,0:JBP1,0:KBP1),M%FVZ_D(0:IBP1,0:JBP1,0:KBP1)) ; M%FVX_D=0._EB ; M%FVY_D=0._EB ; M%FVZ_D=0._EB
ENDIF
ALLOCATE(M%H(0:IBP1,0:JBP1,0:KBP1),M%HS(0:IBP1,0:JBP1,0:KBP1)) ; M%H=0.5_EB*(U0**2+V0**2+W0**2) ; M%HS=0.5_EB*(U0**2+V0**2+W0**2)
ALLOCATE(M%KRES(0:IBP1,0:JBP1,0:KBP1),M%DDDT(0:IBP1,0:JBP1,0:KBP1),M%D(0:IBP1,0:JBP1,0:KBP1),M%DS(0:IBP1,0:JBP1,0:KBP1)) ; M%KRES=0._EB ; M%DDDT=0._EB ; M%D=0._EB ; M%DS=0._EB
ALLOCATE(M%MU(0:IBP1,0:JBP1,0:KBP1),M%MU_DNS(0:IBP1,0:JBP1,0:KBP1)) ; M%MU=0._EB ; M%MU_DNS=0._EB
IF (CHECK_VN) THEN ; ALLOCATE(M%D_Z_MAX(0:IBP1,0:JBP1,0:KBP1)) ; M%D_Z_MAX=0._EB ; ENDIF
ALLOCATE(M%STRAIN_RATE(0:IBP1,0:JBP1,0:KBP1)) ; M%STRAIN_RATE=0._EB
ALLOCATE(M%CSD2(0:IBP1,0:JBP1,0:KBP1)) ; M%CSD2=0._EB
ALLOCATE(M%Q(0:IBP1,0:JBP1,0:KBP1)) ; M%Q=0._EB
ALLOCATE(M%MIX_TIME(0:IBP1,0:JBP1,0:KBP1)) ; M%MIX_TIME=0._EB
ALLOCATE(M%PRESSURE_ZONE(0:IBP1,0:JBP1,0:KBP1)) ; M%PRESSURE_ZONE=-1
ALLOCATE(M%DEL_RHO_D_DEL_Z(0:IBP1,0:JBP1,0:KBP1,N_TOTAL_SCALARS)) ; M%DEL_RHO_D_DEL_Z=0._EB
ALLOCATE(M%RSUM(0:IBP1,0:JBP1,0:KBP1)) ; M%RSUM=RSUM0
ALLOCATE(M%FX(0:IBP1,0:JBP1,0:KBP1,N_LOWER_SCALARS:N_TOTAL_SCALARS),M%FY(0:IBP1,0:JBP1,0:KBP1,N_LOWER_SCALARS:N_TOTAL_SCALARS),M%FZ(0:IBP1,0:JBP1,0:KBP1,N_LOWER_SCALARS:N_TOTAL_SCALARS))
M%FX=0._EB ; M%FY=0._EB ; M%FZ=0._EB
IF (STORE_SPECIES_FLUX) THEN
   ALLOCATE(M%ADV_FX(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS),M%ADV_FY(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS),M%ADV_FZ(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS))
   ALLOCATE(M%DIF_FX(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS),M%DIF_FY(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS),M%DIF_FZ(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS))
   ALLOCATE(M%DIF_FXS(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS),M%DIF_FYS(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS),M%DIF_FZS(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS))
   M%ADV_FX=0._EB ; M%ADV_FY=0._EB ; M%ADV_FZ=0._EB ; M%DIF_FX=0._EB ; M%DIF_FY=0._EB ; M%DIF_FZ=0._EB ; M%DIF_FXS=0._EB ; M%DIF_FYS=0._EB ; M%DIF_FZS=0._EB
ENDIF
IF (STORE_PRESSURE_POISSON_RESIDUAL) THEN ; ALLOCATE(M%PP_RESIDUAL(0:IBP1,0:JBP1,0:KBP1)) ; M%PP_RESIDUAL=0._EB ; ENDIF
IF (STORE_CUTCELL_DIVERGENCE) THEN ; ALLOCATE(M%CCVELDIV(0:IBP1,0:JBP1,0:KBP1)) ; M%CCVELDIV=0._EB ; ENDIF
IF (STORE_CARTESIAN_DIVERGENCE) THEN ; ALLOCATE(M%CARTVELDIV(0:IBP1,0:JBP1,0:KBP1)) ; M%CARTVELDIV=0._EB ; ENDIF
IF (N_REACTIONS>0) THEN
   ALLOCATE(M%D_SOURCE(0:IBP1,0:JBP1,0:KBP1)) ; M%D_SOURCE=0._EB
   ALLOCATE(M%M_DOT_PPP(0:IBP1,0:JBP1,0:KBP1,1:N_TRACKED_SPECIES)) ; M%M_DOT_PPP=0._EB
ENDIF
IF (REAC_SOURCE_CHECK) THEN
   ALLOCATE(M%REAC_SOURCE_TERM(0:IBP1,0:JBP1,0:KBP1,N_TRACKED_SPECIES),M%Q_REAC(0:IBP1,0:JBP1,0:KBP1,N_REACTIONS)) ; M%REAC_SOURCE_TERM=0._EB ; M%Q_REAC=0._EB
ENDIF
ALLOCATE(M%CHI_R(0:IBP1,0:JBP1,0:KBP1),M%QR(0:IBP1,0:JBP1,0:KBP1),M%KAPPA_GAS(0:IBP1,0:JBP1,0:KBP1),M%UII(0:IBP1,0:JBP1,0:KBP1)) ; M%CHI_R=0._EB ; M%QR=0._EB ; M%KAPPA_GAS=0._EB ; M%UII=0._EB
ALLOCATE(M%WORK1(0:IBP1,0:JBP1,0:KBP1),M%WORK2(0:IBP1,0:JBP1,0:KBP1),M%WORK3(0:IBP1,0:JBP1,0:KBP1),M%WORK4(0:IBP1,0:JBP1,0:KBP1),M%WORK5(0:IBP1,0:JBP1,0:KBP1))
ALLOCATE(M%WORK6(0:IBP1,0:JBP1,0:KBP1),M%WORK7(0:IBP1,0:JBP1,0:KBP1),M%WORK8(0:IBP1,0:JBP1,0:KBP1),M%WORK9(0:IBP1,0:JBP1,0:KBP1),M%IWORK1(0:IBP1,0:JBP1,0:KBP1))
ALLOCATE(M%SWORK1(0:IBP1,0:JBP1,0:KBP1,N_LOWER_SCALARS:N_TOTAL_SCALARS),M%SWORK2(0:IBP1,0:JBP1,0:KBP1,N_LOWER_SCALARS:N_TOTAL_SCALARS))
ALLOCATE(M%SWORK3(0:IBP1,0:JBP1,0:KBP1,N_LOWER_SCALARS:N_TOTAL_SCALARS),M%SWORK4(0:IBP1,0:JBP1,0:KBP1,1:N_TOTAL_SCALARS))
M%WORK1=0._EB ; M%WORK2=0._EB ; M%WORK3=0._EB ; M%WORK4=0._EB ; M%WORK5=0._EB ; M%WORK6=0._EB ; M%WORK7=0._EB ; M%WORK8=0._EB ; M%WORK9=0._EB ; M%IWORK1=0
M%SWORK1=0._EB ; M%SWORK2=0._EB ; M%SWORK3=0._EB ; M%SWORK4=0._EB
ALLOCATE(M%U_WIND(0:KBP1),M%V_WIND(0:KBP1),M%W_WIND(0:KBP1)) ; M%U_WIND=U0 ; M%V_WIND=V0 ; M%W_WIND=W0
ALLOCATE(M%LES_FILTER_WIDTH(0:IBP1,0:JBP1,0:KBP1)) ; M%LES_FILTER_WIDTH=0._EB
DO K=0,KBP1 ; DO J=0,JBP1 ; DO I=0,IBP1   ! as INITIALIZE_MESH_VARIABLES_1: filter width and the constant-Smagorinsky coefficient
   M%LES_FILTER_WIDTH(I,J,K) = LES_FILTER_WIDTH_FUNCTION(M%DX(I),M%DY(J),M%DZ(K))
   IF (TURB_MODEL==CONSMAG .OR. TURB_MODEL==DYNSMAG) M%CSD2(I,J,K) = (C_SMAGORINSKY*M%LES_FILTER_WIDTH(I,J,K))**2
ENDDO ; ENDDO ; ENDDO

! background atmosphere (INITIALIZE_ATMOSPHERE, cell-centred part) and background pressure (PBAR, PBAR_S, R_PBAR, D_PBAR_DT, D_PBAR_DT_S, U_LEAK)
ALLOCATE(M%P_0(0:KBP1),M%TMP_0(0:KBP1),M%RHO_0(0:KBP1))
IF (STRATIFICATION) THEN
   DO K=0,KBP1
      M%TMP_0(K) = TMPA*EVALUATE_RAMP(M%ZC(K),I_RAMP_TMP0_Z)
      M%P_0(K)   = EVALUATE_RAMP(M%ZC(K),I_RAMP_P0_Z)
      M%RHO_0(K) = M%P_0(K)/(M%TMP_0(K)*RSUM0)
   ENDDO
ELSE
   M%TMP_0(:) = TMPA ; M%P_0(:) = P_INF ; M%RHO_0(:) = M%P_0(:)/(M%TMP_0(:)*RSUM0)
ENDIF
ALLOCATE(M%PBAR(0:KBP1,0:N_ZONE),M%PBAR_S(0:KBP1,0:N_ZONE),M%R_PBAR(0:KBP1,0:N_ZONE),M%D_PBAR_DT(0:N_ZONE),M%D_PBAR_DT_S(0:N_ZONE),M%U_LEAK(0:N_ZONE))
M%D_PBAR_DT=0._EB ; M%D_PBAR_DT_S=0._EB ; M%U_LEAK=0._EB ; M%R_PBAR=0._EB
DO K=0,KBP1 ; M%PBAR(K,:)=M%P_0(K) ; M%PBAR_S(K,:)=M%P_0(K) ; ENDDO
ALLOCATE(M%BOUNDARY_COORD(0),M%BOUNDARY_PROP1(0),M%BOUNDARY_PROP2(0),M%BOUNDARY_RADIA(0))
M%CLIP_RHOMIN=.FALSE. ; M%CLIP_RHOMAX=.FALSE. ; M%DT_RESTRICT_COUNT=0

END SUBROUTINE BUILD_FINE_BOX

!> One axis of the grid exactly as READ_MESH makes it for an untransformed uniform mesh (G(X)=X).
SUBROUTINE AXIS(N,S,E,DXI,X,XC,HX,DX,RDX,DXN,RDXN,DXMIN)

INTEGER, INTENT(IN) :: N
REAL(EB), INTENT(IN) :: S,E,DXI
REAL(EB), INTENT(OUT) :: X(0:N),XC(0:N+1),HX(0:N+1),DX(0:N+1),RDX(0:N+1),DXN(0:N),RDXN(0:N),DXMIN
INTEGER :: I

DXMIN = 1000000._EB ; DX = 0._EB ; RDX = 0._EB ; HX = 1._EB ; XC = 0._EB
DO I=0,N
   X(I) = S + REAL(I,EB)*DXI
   IF (I>0) THEN
      DX(I) = X(I) - X(I-1)
      DXMIN = MIN(DXMIN,DX(I))
      RDX(I) = 1._EB/DX(I)
   ENDIF
ENDDO
X(0) = S ; X(N) = E
DX(0) = DX(1) ; DX(N+1) = DX(N) ; RDX(0) = 1._EB/DX(1) ; RDX(N+1) = 1._EB/DX(N)
DO I=0,N
   DXN(I) = 0.5_EB*(DX(I)+DX(I+1))
   RDXN(I) = 1._EB/DXN(I)
   IF (I>0) XC(I) = 0.5_EB*(X(I)+X(I-1))
ENDDO
XC(0) = S - 0.5_EB*DX(0) ; XC(N+1) = E + 0.5_EB*DX(N+1)

END SUBROUTINE AXIS

!> The cell numbering of the ghost ring in the order of READ_OBST (low/high x layers, then y, then z).
SUBROUTINE NUMBER_CELLS(M,NI,NJ,NK,NC)

TYPE(MESH_TYPE), INTENT(INOUT) :: M
INTEGER, INTENT(IN) :: NI,NJ,NK
INTEGER, INTENT(INOUT) :: NC
INTEGER :: I,J,K,CNT

CNT = 0
DO K=0,NK+1
   DO J=0,NJ+1
      DO I=0,1 ; CALL NUM(I,J,K) ; ENDDO
      DO I=NI,NI+1 ; CALL NUM(I,J,K) ; ENDDO
   ENDDO
ENDDO
DO K=0,NK+1
   DO I=0,NI+1
      DO J=0,1 ; CALL NUM(I,J,K) ; ENDDO
      DO J=NJ,NJ+1 ; CALL NUM(I,J,K) ; ENDDO
   ENDDO
ENDDO
DO J=0,NJ+1
   DO I=0,NI+1
      DO K=0,1 ; CALL NUM(I,J,K) ; ENDDO
      DO K=NK,NK+1 ; CALL NUM(I,J,K) ; ENDDO
   ENDDO
ENDDO
NC = CNT

CONTAINS
   SUBROUTINE NUM(I,J,K)
   INTEGER, INTENT(IN) :: I,J,K
   IF (M%CELL_INDEX(I,J,K)==0) THEN ; CNT = CNT+1 ; M%CELL_INDEX(I,J,K) = CNT ; ENDIF
   END SUBROUTINE NUM

END SUBROUTINE NUMBER_CELLS

!> Copy the state of the level-0 box R into the built fine box F: all arrays the kernels read or write that are not tables, with their ghost layers, plus the carried scalars.
SUBROUTINE COPY_STATE(R,F)

TYPE(MESH_TYPE), INTENT(IN) :: R
TYPE(MESH_TYPE), INTENT(INOUT) :: F

CALL CP3(F%TMP,LBOUND(F%TMP),R%TMP,LBOUND(R%TMP)) ; CALL CP3(F%RHO,LBOUND(F%RHO),R%RHO,LBOUND(R%RHO)) ; CALL CP3(F%RHOS,LBOUND(F%RHOS),R%RHOS,LBOUND(R%RHOS)) ; CALL CP4(F%ZZ,LBOUND(F%ZZ),R%ZZ,LBOUND(R%ZZ)) ; CALL CP4(F%ZZS,LBOUND(F%ZZS),R%ZZS,LBOUND(R%ZZS))
CALL CP3(F%U,LBOUND(F%U),R%U,LBOUND(R%U)) ; CALL CP3(F%V,LBOUND(F%V),R%V,LBOUND(R%V)) ; CALL CP3(F%W,LBOUND(F%W),R%W,LBOUND(R%W)) ; CALL CP3(F%US,LBOUND(F%US),R%US,LBOUND(R%US)) ; CALL CP3(F%VS,LBOUND(F%VS),R%VS,LBOUND(R%VS)) ; CALL CP3(F%WS,LBOUND(F%WS),R%WS,LBOUND(R%WS))
CALL CP3(F%FVX,LBOUND(F%FVX),R%FVX,LBOUND(R%FVX)) ; CALL CP3(F%FVY,LBOUND(F%FVY),R%FVY,LBOUND(R%FVY)) ; CALL CP3(F%FVZ,LBOUND(F%FVZ),R%FVZ,LBOUND(R%FVZ)) ; CALL CP3(F%FVX_B,LBOUND(F%FVX_B),R%FVX_B,LBOUND(R%FVX_B)) ; CALL CP3(F%FVY_B,LBOUND(F%FVY_B),R%FVY_B,LBOUND(R%FVY_B)) ; CALL CP3(F%FVZ_B,LBOUND(F%FVZ_B),R%FVZ_B,LBOUND(R%FVZ_B))
CALL CP3(F%H,LBOUND(F%H),R%H,LBOUND(R%H)) ; CALL CP3(F%HS,LBOUND(F%HS),R%HS,LBOUND(R%HS)) ; CALL CP3(F%KRES,LBOUND(F%KRES),R%KRES,LBOUND(R%KRES)) ; CALL CP3(F%DDDT,LBOUND(F%DDDT),R%DDDT,LBOUND(R%DDDT)) ; CALL CP3(F%D,LBOUND(F%D),R%D,LBOUND(R%D)) ; CALL CP3(F%DS,LBOUND(F%DS),R%DS,LBOUND(R%DS)) ; CALL CP3(F%MU,LBOUND(F%MU),R%MU,LBOUND(R%MU)) ; CALL CP3(F%MU_DNS,LBOUND(F%MU_DNS),R%MU_DNS,LBOUND(R%MU_DNS)) ; CALL CP3(F%STRAIN_RATE,LBOUND(F%STRAIN_RATE),R%STRAIN_RATE,LBOUND(R%STRAIN_RATE)) ; CALL CP3(F%Q,LBOUND(F%Q),R%Q,LBOUND(R%Q))
CALL CP3(F%RSUM,LBOUND(F%RSUM),R%RSUM,LBOUND(R%RSUM)) ; CALL CP4(F%DEL_RHO_D_DEL_Z,LBOUND(F%DEL_RHO_D_DEL_Z),R%DEL_RHO_D_DEL_Z,LBOUND(R%DEL_RHO_D_DEL_Z)) ; CALL CP4(F%FX,LBOUND(F%FX),R%FX,LBOUND(R%FX)) ; CALL CP4(F%FY,LBOUND(F%FY),R%FY,LBOUND(R%FY)) ; CALL CP4(F%FZ,LBOUND(F%FZ),R%FZ,LBOUND(R%FZ))
F%PRESSURE_ZONE=R%PRESSURE_ZONE ; F%U_WIND=R%U_WIND ; F%V_WIND=R%V_WIND ; F%W_WIND=R%W_WIND
IF (ALLOCATED(R%M_DOT_PPP)) CALL CP4(F%M_DOT_PPP,LBOUND(F%M_DOT_PPP),R%M_DOT_PPP,LBOUND(R%M_DOT_PPP))
IF (ALLOCATED(R%D_SOURCE)) CALL CP3(F%D_SOURCE,LBOUND(F%D_SOURCE),R%D_SOURCE,LBOUND(R%D_SOURCE))
IF (ALLOCATED(R%D_Z_MAX)) CALL CP3(F%D_Z_MAX,LBOUND(F%D_Z_MAX),R%D_Z_MAX,LBOUND(R%D_Z_MAX))
F%CLIP_RHOMIN=R%CLIP_RHOMIN ; F%CLIP_RHOMAX=R%CLIP_RHOMAX ; F%DT_RESTRICT_COUNT=R%DT_RESTRICT_COUNT
F%CFL=R%CFL ; F%VN=R%VN ; F%POIS_ERR=R%POIS_ERR ; F%BAROCLINIC_TERMS_ATTACHED=R%BAROCLINIC_TERMS_ATTACHED
F%PBAR=R%PBAR ; F%PBAR_S=R%PBAR_S ; F%R_PBAR=R%R_PBAR ; F%D_PBAR_DT=R%D_PBAR_DT ; F%D_PBAR_DT_S=R%D_PBAR_DT_S ; F%U_LEAK=R%U_LEAK

END SUBROUTINE COPY_STATE

!> Copy the index range common to D and S. Assignment would reallocate D when the level-0 array has another extent (the driver's level-0 boxes carry more ghost layers than FDS
!> gives a box); the built fine box keeps its own allocation, so that views bound to it stay valid. Cells of D outside the range of S keep their value.
SUBROUTINE CP3(D,LD,S,LS)
INTEGER, INTENT(IN) :: LD(3),LS(3)
REAL(EB), INTENT(INOUT) :: D(LD(1):,LD(2):,LD(3):)
REAL(EB), INTENT(IN) :: S(LS(1):,LS(2):,LS(3):)
INTEGER :: LO(3),HI(3)
LO = MAX(LD,LS) ; HI = MIN(UBOUND(D),UBOUND(S))
IF (ANY(HI<LO)) RETURN
D(LO(1):HI(1),LO(2):HI(2),LO(3):HI(3)) = S(LO(1):HI(1),LO(2):HI(2),LO(3):HI(3))
END SUBROUTINE CP3

SUBROUTINE CP4(D,LD,S,LS)
INTEGER, INTENT(IN) :: LD(4),LS(4)
REAL(EB), INTENT(INOUT) :: D(LD(1):,LD(2):,LD(3):,LD(4):)
REAL(EB), INTENT(IN) :: S(LS(1):,LS(2):,LS(3):,LS(4):)
INTEGER :: LO(4),HI(4)
LO = MAX(LD,LS) ; HI = MIN(UBOUND(D),UBOUND(S))
IF (ANY(HI<LO)) RETURN
D(LO(1):HI(1),LO(2):HI(2),LO(3):HI(3),LO(4):HI(4)) = S(LO(1):HI(1),LO(2):HI(2),LO(3):HI(3),LO(4):HI(4))
END SUBROUTINE CP4

SUBROUTINE SAVE_GLOBALS(G)
TYPE(GLOBALS_T), INTENT(INOUT) :: G
IF (ALLOCATED(DSUM)) G%DSUM = DSUM
IF (ALLOCATED(USUM)) G%USUM = USUM
IF (ALLOCATED(PSUM)) G%PSUM = PSUM
IF (ALLOCATED(P_ZONE)) G%PZ = P_ZONE
END SUBROUTINE SAVE_GLOBALS

SUBROUTINE RESTORE_GLOBALS(G)
TYPE(GLOBALS_T), INTENT(IN) :: G
IF (ALLOCATED(G%DSUM)) DSUM = G%DSUM
IF (ALLOCATED(G%USUM)) USUM = G%USUM
IF (ALLOCATED(G%PSUM)) PSUM = G%PSUM
IF (ALLOCATED(G%PZ)) P_ZONE = G%PZ
END SUBROUTINE RESTORE_GLOBALS

!> List of the allocatable components of the level-0 mesh object R that are allocated there but not in the built fine box F (information for the contents list of level-interface.md section 3).
SUBROUTINE AUDIT_BUILT_BOX(R,F)

TYPE(MESH_TYPE), INTENT(IN) :: R,F

WRITE(6,'(A)') 'FINE-B BUILD AUDIT: components allocated in the level-0 mesh object and not in the built fine box:'
IF (ALLOCATED(R%U) .AND. .NOT.ALLOCATED(F%U)) CALL NOTE('U')
IF (ALLOCATED(R%V) .AND. .NOT.ALLOCATED(F%V)) CALL NOTE('V')
IF (ALLOCATED(R%W) .AND. .NOT.ALLOCATED(F%W)) CALL NOTE('W')
IF (ALLOCATED(R%US) .AND. .NOT.ALLOCATED(F%US)) CALL NOTE('US')
IF (ALLOCATED(R%VS) .AND. .NOT.ALLOCATED(F%VS)) CALL NOTE('VS')
IF (ALLOCATED(R%WS) .AND. .NOT.ALLOCATED(F%WS)) CALL NOTE('WS')
IF (ALLOCATED(R%DDDT) .AND. .NOT.ALLOCATED(F%DDDT)) CALL NOTE('DDDT')
IF (ALLOCATED(R%D) .AND. .NOT.ALLOCATED(F%D)) CALL NOTE('D')
IF (ALLOCATED(R%DS) .AND. .NOT.ALLOCATED(F%DS)) CALL NOTE('DS')
IF (ALLOCATED(R%H) .AND. .NOT.ALLOCATED(F%H)) CALL NOTE('H')
IF (ALLOCATED(R%HS) .AND. .NOT.ALLOCATED(F%HS)) CALL NOTE('HS')
IF (ALLOCATED(R%KRES) .AND. .NOT.ALLOCATED(F%KRES)) CALL NOTE('KRES')
IF (ALLOCATED(R%FVX) .AND. .NOT.ALLOCATED(F%FVX)) CALL NOTE('FVX')
IF (ALLOCATED(R%FVY) .AND. .NOT.ALLOCATED(F%FVY)) CALL NOTE('FVY')
IF (ALLOCATED(R%FVZ) .AND. .NOT.ALLOCATED(F%FVZ)) CALL NOTE('FVZ')
IF (ALLOCATED(R%FVX_B) .AND. .NOT.ALLOCATED(F%FVX_B)) CALL NOTE('FVX_B')
IF (ALLOCATED(R%FVY_B) .AND. .NOT.ALLOCATED(F%FVY_B)) CALL NOTE('FVY_B')
IF (ALLOCATED(R%FVZ_B) .AND. .NOT.ALLOCATED(F%FVZ_B)) CALL NOTE('FVZ_B')
IF (ALLOCATED(R%FVX_D) .AND. .NOT.ALLOCATED(F%FVX_D)) CALL NOTE('FVX_D')
IF (ALLOCATED(R%FVY_D) .AND. .NOT.ALLOCATED(F%FVY_D)) CALL NOTE('FVY_D')
IF (ALLOCATED(R%FVZ_D) .AND. .NOT.ALLOCATED(F%FVZ_D)) CALL NOTE('FVZ_D')
IF (ALLOCATED(R%RHO) .AND. .NOT.ALLOCATED(F%RHO)) CALL NOTE('RHO')
IF (ALLOCATED(R%RHOS) .AND. .NOT.ALLOCATED(F%RHOS)) CALL NOTE('RHOS')
IF (ALLOCATED(R%MU) .AND. .NOT.ALLOCATED(F%MU)) CALL NOTE('MU')
IF (ALLOCATED(R%MU_DNS) .AND. .NOT.ALLOCATED(F%MU_DNS)) CALL NOTE('MU_DNS')
IF (ALLOCATED(R%TMP) .AND. .NOT.ALLOCATED(F%TMP)) CALL NOTE('TMP')
IF (ALLOCATED(R%Q) .AND. .NOT.ALLOCATED(F%Q)) CALL NOTE('Q')
IF (ALLOCATED(R%KAPPA_GAS) .AND. .NOT.ALLOCATED(F%KAPPA_GAS)) CALL NOTE('KAPPA_GAS')
IF (ALLOCATED(R%CHI_R) .AND. .NOT.ALLOCATED(F%CHI_R)) CALL NOTE('CHI_R')
IF (ALLOCATED(R%QR) .AND. .NOT.ALLOCATED(F%QR)) CALL NOTE('QR')
IF (ALLOCATED(R%QR_W) .AND. .NOT.ALLOCATED(F%QR_W)) CALL NOTE('QR_W')
IF (ALLOCATED(R%RADIATION_EMISSION) .AND. .NOT.ALLOCATED(F%RADIATION_EMISSION)) CALL NOTE('RADIATION_EMISSION')
IF (ALLOCATED(R%RADIATION_ABSORPTION) .AND. .NOT.ALLOCATED(F%RADIATION_ABSORPTION)) CALL NOTE('RADIATION_ABSORPTION')
IF (ALLOCATED(R%UII) .AND. .NOT.ALLOCATED(F%UII)) CALL NOTE('UII')
IF (ALLOCATED(R%RSUM) .AND. .NOT.ALLOCATED(F%RSUM)) CALL NOTE('RSUM')
IF (ALLOCATED(R%D_SOURCE) .AND. .NOT.ALLOCATED(F%D_SOURCE)) CALL NOTE('D_SOURCE')
IF (ALLOCATED(R%CSD2) .AND. .NOT.ALLOCATED(F%CSD2)) CALL NOTE('CSD2')
IF (ALLOCATED(R%CHEM_SUBIT) .AND. .NOT.ALLOCATED(F%CHEM_SUBIT)) CALL NOTE('CHEM_SUBIT')
IF (ALLOCATED(R%CHEM_ACTIVE_CELLS) .AND. .NOT.ALLOCATED(F%CHEM_ACTIVE_CELLS)) CALL NOTE('CHEM_ACTIVE_CELLS')
IF (ALLOCATED(R%CHEM_ACTIVE_CC) .AND. .NOT.ALLOCATED(F%CHEM_ACTIVE_CC)) CALL NOTE('CHEM_ACTIVE_CC')
IF (ALLOCATED(R%MIX_TIME) .AND. .NOT.ALLOCATED(F%MIX_TIME)) CALL NOTE('MIX_TIME')
IF (ALLOCATED(R%STRAIN_RATE) .AND. .NOT.ALLOCATED(F%STRAIN_RATE)) CALL NOTE('STRAIN_RATE')
IF (ALLOCATED(R%D_Z_MAX) .AND. .NOT.ALLOCATED(F%D_Z_MAX)) CALL NOTE('D_Z_MAX')
IF (ALLOCATED(R%PP_RESIDUAL) .AND. .NOT.ALLOCATED(F%PP_RESIDUAL)) CALL NOTE('PP_RESIDUAL')
IF (ALLOCATED(R%LES_FILTER_WIDTH) .AND. .NOT.ALLOCATED(F%LES_FILTER_WIDTH)) CALL NOTE('LES_FILTER_WIDTH')
IF (ALLOCATED(R%ZZ) .AND. .NOT.ALLOCATED(F%ZZ)) CALL NOTE('ZZ')
IF (ALLOCATED(R%ZZS) .AND. .NOT.ALLOCATED(F%ZZS)) CALL NOTE('ZZS')
IF (ALLOCATED(R%REAC_SOURCE_TERM) .AND. .NOT.ALLOCATED(F%REAC_SOURCE_TERM)) CALL NOTE('REAC_SOURCE_TERM')
IF (ALLOCATED(R%DEL_RHO_D_DEL_Z) .AND. .NOT.ALLOCATED(F%DEL_RHO_D_DEL_Z)) CALL NOTE('DEL_RHO_D_DEL_Z')
IF (ALLOCATED(R%FX) .AND. .NOT.ALLOCATED(F%FX)) CALL NOTE('FX')
IF (ALLOCATED(R%FY) .AND. .NOT.ALLOCATED(F%FY)) CALL NOTE('FY')
IF (ALLOCATED(R%FZ) .AND. .NOT.ALLOCATED(F%FZ)) CALL NOTE('FZ')
IF (ALLOCATED(R%Q_REAC) .AND. .NOT.ALLOCATED(F%Q_REAC)) CALL NOTE('Q_REAC')
IF (ALLOCATED(R%AVG_DROP_DEN) .AND. .NOT.ALLOCATED(F%AVG_DROP_DEN)) CALL NOTE('AVG_DROP_DEN')
IF (ALLOCATED(R%AVG_DROP_TMP) .AND. .NOT.ALLOCATED(F%AVG_DROP_TMP)) CALL NOTE('AVG_DROP_TMP')
IF (ALLOCATED(R%AVG_DROP_RAD) .AND. .NOT.ALLOCATED(F%AVG_DROP_RAD)) CALL NOTE('AVG_DROP_RAD')
IF (ALLOCATED(R%AVG_DROP_AREA) .AND. .NOT.ALLOCATED(F%AVG_DROP_AREA)) CALL NOTE('AVG_DROP_AREA')
IF (ALLOCATED(R%M_DOT_PPP) .AND. .NOT.ALLOCATED(F%M_DOT_PPP)) CALL NOTE('M_DOT_PPP')
IF (ALLOCATED(R%ADV_FX) .AND. .NOT.ALLOCATED(F%ADV_FX)) CALL NOTE('ADV_FX')
IF (ALLOCATED(R%ADV_FY) .AND. .NOT.ALLOCATED(F%ADV_FY)) CALL NOTE('ADV_FY')
IF (ALLOCATED(R%ADV_FZ) .AND. .NOT.ALLOCATED(F%ADV_FZ)) CALL NOTE('ADV_FZ')
IF (ALLOCATED(R%DIF_FX) .AND. .NOT.ALLOCATED(F%DIF_FX)) CALL NOTE('DIF_FX')
IF (ALLOCATED(R%DIF_FY) .AND. .NOT.ALLOCATED(F%DIF_FY)) CALL NOTE('DIF_FY')
IF (ALLOCATED(R%DIF_FZ) .AND. .NOT.ALLOCATED(F%DIF_FZ)) CALL NOTE('DIF_FZ')
IF (ALLOCATED(R%DIF_FXS) .AND. .NOT.ALLOCATED(F%DIF_FXS)) CALL NOTE('DIF_FXS')
IF (ALLOCATED(R%DIF_FYS) .AND. .NOT.ALLOCATED(F%DIF_FYS)) CALL NOTE('DIF_FYS')
IF (ALLOCATED(R%DIF_FZS) .AND. .NOT.ALLOCATED(F%DIF_FZS)) CALL NOTE('DIF_FZS')
IF (ALLOCATED(R%SAVE1) .AND. .NOT.ALLOCATED(F%SAVE1)) CALL NOTE('SAVE1')
IF (ALLOCATED(R%SAVE2) .AND. .NOT.ALLOCATED(F%SAVE2)) CALL NOTE('SAVE2')
IF (ALLOCATED(R%WORK) .AND. .NOT.ALLOCATED(F%WORK)) CALL NOTE('WORK')
IF (ALLOCATED(R%PRHS) .AND. .NOT.ALLOCATED(F%PRHS)) CALL NOTE('PRHS')
IF (ALLOCATED(R%BXS) .AND. .NOT.ALLOCATED(F%BXS)) CALL NOTE('BXS')
IF (ALLOCATED(R%BXF) .AND. .NOT.ALLOCATED(F%BXF)) CALL NOTE('BXF')
IF (ALLOCATED(R%BYS) .AND. .NOT.ALLOCATED(F%BYS)) CALL NOTE('BYS')
IF (ALLOCATED(R%BYF) .AND. .NOT.ALLOCATED(F%BYF)) CALL NOTE('BYF')
IF (ALLOCATED(R%BZS) .AND. .NOT.ALLOCATED(F%BZS)) CALL NOTE('BZS')
IF (ALLOCATED(R%BZF) .AND. .NOT.ALLOCATED(F%BZF)) CALL NOTE('BZF')
IF (ALLOCATED(R%BXST) .AND. .NOT.ALLOCATED(F%BXST)) CALL NOTE('BXST')
IF (ALLOCATED(R%BXFT) .AND. .NOT.ALLOCATED(F%BXFT)) CALL NOTE('BXFT')
IF (ALLOCATED(R%BYST) .AND. .NOT.ALLOCATED(F%BYST)) CALL NOTE('BYST')
IF (ALLOCATED(R%BYFT) .AND. .NOT.ALLOCATED(F%BYFT)) CALL NOTE('BYFT')
IF (ALLOCATED(R%BZST) .AND. .NOT.ALLOCATED(F%BZST)) CALL NOTE('BZST')
IF (ALLOCATED(R%BZFT) .AND. .NOT.ALLOCATED(F%BZFT)) CALL NOTE('BZFT')
IF (ALLOCATED(R%P_0) .AND. .NOT.ALLOCATED(F%P_0)) CALL NOTE('P_0')
IF (ALLOCATED(R%RHO_0) .AND. .NOT.ALLOCATED(F%RHO_0)) CALL NOTE('RHO_0')
IF (ALLOCATED(R%TMP_0) .AND. .NOT.ALLOCATED(F%TMP_0)) CALL NOTE('TMP_0')
IF (ALLOCATED(R%D_PBAR_DT) .AND. .NOT.ALLOCATED(F%D_PBAR_DT)) CALL NOTE('D_PBAR_DT')
IF (ALLOCATED(R%D_PBAR_DT_S) .AND. .NOT.ALLOCATED(F%D_PBAR_DT_S)) CALL NOTE('D_PBAR_DT_S')
IF (ALLOCATED(R%U_LEAK) .AND. .NOT.ALLOCATED(F%U_LEAK)) CALL NOTE('U_LEAK')
IF (ALLOCATED(R%U_WIND) .AND. .NOT.ALLOCATED(F%U_WIND)) CALL NOTE('U_WIND')
IF (ALLOCATED(R%V_WIND) .AND. .NOT.ALLOCATED(F%V_WIND)) CALL NOTE('V_WIND')
IF (ALLOCATED(R%W_WIND) .AND. .NOT.ALLOCATED(F%W_WIND)) CALL NOTE('W_WIND')
IF (ALLOCATED(R%PBAR) .AND. .NOT.ALLOCATED(F%PBAR)) CALL NOTE('PBAR')
IF (ALLOCATED(R%PBAR_S) .AND. .NOT.ALLOCATED(F%PBAR_S)) CALL NOTE('PBAR_S')
IF (ALLOCATED(R%R_PBAR) .AND. .NOT.ALLOCATED(F%R_PBAR)) CALL NOTE('R_PBAR')
IF (ALLOCATED(R%PRESSURE_ZONE) .AND. .NOT.ALLOCATED(F%PRESSURE_ZONE)) CALL NOTE('PRESSURE_ZONE')
IF (ALLOCATED(R%ZONE_MESH) .AND. .NOT.ALLOCATED(F%ZONE_MESH)) CALL NOTE('ZONE_MESH')
IF (ALLOCATED(R%MUNKH) .AND. .NOT.ALLOCATED(F%MUNKH)) CALL NOTE('MUNKH')
IF (ALLOCATED(R%SWORK1) .AND. .NOT.ALLOCATED(F%SWORK1)) CALL NOTE('SWORK1')
IF (ALLOCATED(R%SWORK2) .AND. .NOT.ALLOCATED(F%SWORK2)) CALL NOTE('SWORK2')
IF (ALLOCATED(R%SWORK3) .AND. .NOT.ALLOCATED(F%SWORK3)) CALL NOTE('SWORK3')
IF (ALLOCATED(R%SWORK4) .AND. .NOT.ALLOCATED(F%SWORK4)) CALL NOTE('SWORK4')
IF (ALLOCATED(R%WORK1) .AND. .NOT.ALLOCATED(F%WORK1)) CALL NOTE('WORK1')
IF (ALLOCATED(R%WORK2) .AND. .NOT.ALLOCATED(F%WORK2)) CALL NOTE('WORK2')
IF (ALLOCATED(R%WORK3) .AND. .NOT.ALLOCATED(F%WORK3)) CALL NOTE('WORK3')
IF (ALLOCATED(R%WORK4) .AND. .NOT.ALLOCATED(F%WORK4)) CALL NOTE('WORK4')
IF (ALLOCATED(R%WORK5) .AND. .NOT.ALLOCATED(F%WORK5)) CALL NOTE('WORK5')
IF (ALLOCATED(R%WORK6) .AND. .NOT.ALLOCATED(F%WORK6)) CALL NOTE('WORK6')
IF (ALLOCATED(R%WORK7) .AND. .NOT.ALLOCATED(F%WORK7)) CALL NOTE('WORK7')
IF (ALLOCATED(R%WORK8) .AND. .NOT.ALLOCATED(F%WORK8)) CALL NOTE('WORK8')
IF (ALLOCATED(R%WORK9) .AND. .NOT.ALLOCATED(F%WORK9)) CALL NOTE('WORK9')
IF (ALLOCATED(R%IWORK1) .AND. .NOT.ALLOCATED(F%IWORK1)) CALL NOTE('IWORK1')
IF (ALLOCATED(R%WORK_PAD) .AND. .NOT.ALLOCATED(F%WORK_PAD)) CALL NOTE('WORK_PAD')
IF (ALLOCATED(R%WORK_U) .AND. .NOT.ALLOCATED(F%WORK_U)) CALL NOTE('WORK_U')
IF (ALLOCATED(R%WORK_V) .AND. .NOT.ALLOCATED(F%WORK_V)) CALL NOTE('WORK_V')
IF (ALLOCATED(R%WORK_W) .AND. .NOT.ALLOCATED(F%WORK_W)) CALL NOTE('WORK_W')
IF (ALLOCATED(R%PWORK1) .AND. .NOT.ALLOCATED(F%PWORK1)) CALL NOTE('PWORK1')
IF (ALLOCATED(R%PWORK2) .AND. .NOT.ALLOCATED(F%PWORK2)) CALL NOTE('PWORK2')
IF (ALLOCATED(R%PWORK3) .AND. .NOT.ALLOCATED(F%PWORK3)) CALL NOTE('PWORK3')
IF (ALLOCATED(R%PWORK4) .AND. .NOT.ALLOCATED(F%PWORK4)) CALL NOTE('PWORK4')
IF (ALLOCATED(R%PWORK5) .AND. .NOT.ALLOCATED(F%PWORK5)) CALL NOTE('PWORK5')
IF (ALLOCATED(R%PWORK6) .AND. .NOT.ALLOCATED(F%PWORK6)) CALL NOTE('PWORK6')
IF (ALLOCATED(R%PWORK7) .AND. .NOT.ALLOCATED(F%PWORK7)) CALL NOTE('PWORK7')
IF (ALLOCATED(R%PWORK8) .AND. .NOT.ALLOCATED(F%PWORK8)) CALL NOTE('PWORK8')
IF (ALLOCATED(R%TURB_WORK1) .AND. .NOT.ALLOCATED(F%TURB_WORK1)) CALL NOTE('TURB_WORK1')
IF (ALLOCATED(R%TURB_WORK2) .AND. .NOT.ALLOCATED(F%TURB_WORK2)) CALL NOTE('TURB_WORK2')
IF (ALLOCATED(R%TURB_WORK3) .AND. .NOT.ALLOCATED(F%TURB_WORK3)) CALL NOTE('TURB_WORK3')
IF (ALLOCATED(R%TURB_WORK4) .AND. .NOT.ALLOCATED(F%TURB_WORK4)) CALL NOTE('TURB_WORK4')
IF (ALLOCATED(R%TURB_WORK5) .AND. .NOT.ALLOCATED(F%TURB_WORK5)) CALL NOTE('TURB_WORK5')
IF (ALLOCATED(R%TURB_WORK6) .AND. .NOT.ALLOCATED(F%TURB_WORK6)) CALL NOTE('TURB_WORK6')
IF (ALLOCATED(R%TURB_WORK7) .AND. .NOT.ALLOCATED(F%TURB_WORK7)) CALL NOTE('TURB_WORK7')
IF (ALLOCATED(R%TURB_WORK8) .AND. .NOT.ALLOCATED(F%TURB_WORK8)) CALL NOTE('TURB_WORK8')
IF (ALLOCATED(R%TURB_WORK9) .AND. .NOT.ALLOCATED(F%TURB_WORK9)) CALL NOTE('TURB_WORK9')
IF (ALLOCATED(R%TURB_WORK10) .AND. .NOT.ALLOCATED(F%TURB_WORK10)) CALL NOTE('TURB_WORK10')
IF (ALLOCATED(R%CCVELDIV) .AND. .NOT.ALLOCATED(F%CCVELDIV)) CALL NOTE('CCVELDIV')
IF (ALLOCATED(R%CARTVELDIV) .AND. .NOT.ALLOCATED(F%CARTVELDIV)) CALL NOTE('CARTVELDIV')
IF (ALLOCATED(R%WALL_WORK1) .AND. .NOT.ALLOCATED(F%WALL_WORK1)) CALL NOTE('WALL_WORK1')
IF (ALLOCATED(R%WALL_WORK2) .AND. .NOT.ALLOCATED(F%WALL_WORK2)) CALL NOTE('WALL_WORK2')
IF (ALLOCATED(R%FACE_WORK1) .AND. .NOT.ALLOCATED(F%FACE_WORK1)) CALL NOTE('FACE_WORK1')
IF (ALLOCATED(R%FACE_WORK2) .AND. .NOT.ALLOCATED(F%FACE_WORK2)) CALL NOTE('FACE_WORK2')
IF (ALLOCATED(R%FACE_WORK3) .AND. .NOT.ALLOCATED(F%FACE_WORK3)) CALL NOTE('FACE_WORK3')
IF (ALLOCATED(R%FIRE_ARRIVAL_TIME) .AND. .NOT.ALLOCATED(F%FIRE_ARRIVAL_TIME)) CALL NOTE('FIRE_ARRIVAL_TIME')
IF (ALLOCATED(R%FIRE_RESIDENCE_TIME) .AND. .NOT.ALLOCATED(F%FIRE_RESIDENCE_TIME)) CALL NOTE('FIRE_RESIDENCE_TIME')
IF (ALLOCATED(R%LS_SPREAD_RATE) .AND. .NOT.ALLOCATED(F%LS_SPREAD_RATE)) CALL NOTE('LS_SPREAD_RATE')
IF (ALLOCATED(R%QQ) .AND. .NOT.ALLOCATED(F%QQ)) CALL NOTE('QQ')
IF (ALLOCATED(R%QQ2) .AND. .NOT.ALLOCATED(F%QQ2)) CALL NOTE('QQ2')
IF (ALLOCATED(R%PP) .AND. .NOT.ALLOCATED(F%PP)) CALL NOTE('PP')
IF (ALLOCATED(R%PPN) .AND. .NOT.ALLOCATED(F%PPN)) CALL NOTE('PPN')
IF (ALLOCATED(R%BNDF_TIME_INTEGRAL) .AND. .NOT.ALLOCATED(F%BNDF_TIME_INTEGRAL)) CALL NOTE('BNDF_TIME_INTEGRAL')
IF (ALLOCATED(R%IBK) .AND. .NOT.ALLOCATED(F%IBK)) CALL NOTE('IBK')
IF (ALLOCATED(R%IBLK) .AND. .NOT.ALLOCATED(F%IBLK)) CALL NOTE('IBLK')
IF (ALLOCATED(R%EDGE) .AND. .NOT.ALLOCATED(F%EDGE)) CALL NOTE('EDGE')
IF (ALLOCATED(R%NEIGHBORING_MESH) .AND. .NOT.ALLOCATED(F%NEIGHBORING_MESH)) CALL NOTE('NEIGHBORING_MESH')
IF (ALLOCATED(R%RGB) .AND. .NOT.ALLOCATED(F%RGB)) CALL NOTE('RGB')
IF (ALLOCATED(R%R) .AND. .NOT.ALLOCATED(F%R)) CALL NOTE('R')
IF (ALLOCATED(R%RC) .AND. .NOT.ALLOCATED(F%RC)) CALL NOTE('RC')
IF (ALLOCATED(R%RRN) .AND. .NOT.ALLOCATED(F%RRN)) CALL NOTE('RRN')
IF (ALLOCATED(R%X) .AND. .NOT.ALLOCATED(F%X)) CALL NOTE('X')
IF (ALLOCATED(R%Y) .AND. .NOT.ALLOCATED(F%Y)) CALL NOTE('Y')
IF (ALLOCATED(R%Z) .AND. .NOT.ALLOCATED(F%Z)) CALL NOTE('Z')
IF (ALLOCATED(R%XC) .AND. .NOT.ALLOCATED(F%XC)) CALL NOTE('XC')
IF (ALLOCATED(R%YC) .AND. .NOT.ALLOCATED(F%YC)) CALL NOTE('YC')
IF (ALLOCATED(R%ZC) .AND. .NOT.ALLOCATED(F%ZC)) CALL NOTE('ZC')
IF (ALLOCATED(R%HX) .AND. .NOT.ALLOCATED(F%HX)) CALL NOTE('HX')
IF (ALLOCATED(R%HY) .AND. .NOT.ALLOCATED(F%HY)) CALL NOTE('HY')
IF (ALLOCATED(R%HZ) .AND. .NOT.ALLOCATED(F%HZ)) CALL NOTE('HZ')
IF (ALLOCATED(R%DX) .AND. .NOT.ALLOCATED(F%DX)) CALL NOTE('DX')
IF (ALLOCATED(R%DY) .AND. .NOT.ALLOCATED(F%DY)) CALL NOTE('DY')
IF (ALLOCATED(R%DZ) .AND. .NOT.ALLOCATED(F%DZ)) CALL NOTE('DZ')
IF (ALLOCATED(R%RDX) .AND. .NOT.ALLOCATED(F%RDX)) CALL NOTE('RDX')
IF (ALLOCATED(R%RDY) .AND. .NOT.ALLOCATED(F%RDY)) CALL NOTE('RDY')
IF (ALLOCATED(R%RDZ) .AND. .NOT.ALLOCATED(F%RDZ)) CALL NOTE('RDZ')
IF (ALLOCATED(R%DXN) .AND. .NOT.ALLOCATED(F%DXN)) CALL NOTE('DXN')
IF (ALLOCATED(R%DYN) .AND. .NOT.ALLOCATED(F%DYN)) CALL NOTE('DYN')
IF (ALLOCATED(R%DZN) .AND. .NOT.ALLOCATED(F%DZN)) CALL NOTE('DZN')
IF (ALLOCATED(R%RDXN) .AND. .NOT.ALLOCATED(F%RDXN)) CALL NOTE('RDXN')
IF (ALLOCATED(R%RDYN) .AND. .NOT.ALLOCATED(F%RDYN)) CALL NOTE('RDYN')
IF (ALLOCATED(R%RDZN) .AND. .NOT.ALLOCATED(F%RDZN)) CALL NOTE('RDZN')
IF (ALLOCATED(R%CELLSI) .AND. .NOT.ALLOCATED(F%CELLSI)) CALL NOTE('CELLSI')
IF (ALLOCATED(R%CELLSJ) .AND. .NOT.ALLOCATED(F%CELLSJ)) CALL NOTE('CELLSJ')
IF (ALLOCATED(R%CELLSK) .AND. .NOT.ALLOCATED(F%CELLSK)) CALL NOTE('CELLSK')
IF (ALLOCATED(R%XPLT) .AND. .NOT.ALLOCATED(F%XPLT)) CALL NOTE('XPLT')
IF (ALLOCATED(R%YPLT) .AND. .NOT.ALLOCATED(F%YPLT)) CALL NOTE('YPLT')
IF (ALLOCATED(R%ZPLT) .AND. .NOT.ALLOCATED(F%ZPLT)) CALL NOTE('ZPLT')
IF (ALLOCATED(R%OBSTRUCTION) .AND. .NOT.ALLOCATED(F%OBSTRUCTION)) CALL NOTE('OBSTRUCTION')
IF (ALLOCATED(R%VENTS) .AND. .NOT.ALLOCATED(F%VENTS)) CALL NOTE('VENTS')
IF (ALLOCATED(R%CELL_INDEX) .AND. .NOT.ALLOCATED(F%CELL_INDEX)) CALL NOTE('CELL_INDEX')
IF (ALLOCATED(R%CELL) .AND. .NOT.ALLOCATED(F%CELL)) CALL NOTE('CELL')
IF (ALLOCATED(R%CELL_ILW) .AND. .NOT.ALLOCATED(F%CELL_ILW)) CALL NOTE('CELL_ILW')
IF (ALLOCATED(R%CELL_INTEGERS) .AND. .NOT.ALLOCATED(F%CELL_INTEGERS)) CALL NOTE('CELL_INTEGERS')
IF (ALLOCATED(R%CELL_LOGICALS) .AND. .NOT.ALLOCATED(F%CELL_LOGICALS)) CALL NOTE('CELL_LOGICALS')
IF (ALLOCATED(R%CONNECTED_MESH) .AND. .NOT.ALLOCATED(F%CONNECTED_MESH)) CALL NOTE('CONNECTED_MESH')
IF (ALLOCATED(R%REGFACE_IAXIS_H) .AND. .NOT.ALLOCATED(F%REGFACE_IAXIS_H)) CALL NOTE('REGFACE_IAXIS_H')
IF (ALLOCATED(R%VERTVAR) .AND. .NOT.ALLOCATED(F%VERTVAR)) CALL NOTE('VERTVAR')
IF (ALLOCATED(R%CCVAR) .AND. .NOT.ALLOCATED(F%CCVAR)) CALL NOTE('CCVAR')
IF (ALLOCATED(R%ECVAR) .AND. .NOT.ALLOCATED(F%ECVAR)) CALL NOTE('ECVAR')
IF (ALLOCATED(R%FCVAR) .AND. .NOT.ALLOCATED(F%FCVAR)) CALL NOTE('FCVAR')
IF (ALLOCATED(R%EDGE_CROSS) .AND. .NOT.ALLOCATED(F%EDGE_CROSS)) CALL NOTE('EDGE_CROSS')
IF (ALLOCATED(R%CUT_EDGE) .AND. .NOT.ALLOCATED(F%CUT_EDGE)) CALL NOTE('CUT_EDGE')
IF (ALLOCATED(R%CUT_FACE) .AND. .NOT.ALLOCATED(F%CUT_FACE)) CALL NOTE('CUT_FACE')
IF (ALLOCATED(R%CUT_CELL) .AND. .NOT.ALLOCATED(F%CUT_CELL)) CALL NOTE('CUT_CELL')
IF (ALLOCATED(R%CC_REGFACE_IAXIS_Z) .AND. .NOT.ALLOCATED(F%CC_REGFACE_IAXIS_Z)) CALL NOTE('CC_REGFACE_IAXIS_Z')
IF (ALLOCATED(R%CC_REGFACE_JAXIS_Z) .AND. .NOT.ALLOCATED(F%CC_REGFACE_JAXIS_Z)) CALL NOTE('CC_REGFACE_JAXIS_Z')
IF (ALLOCATED(R%CC_REGFACE_KAXIS_Z) .AND. .NOT.ALLOCATED(F%CC_REGFACE_KAXIS_Z)) CALL NOTE('CC_REGFACE_KAXIS_Z')
IF (ALLOCATED(R%RCF_H) .AND. .NOT.ALLOCATED(F%RCF_H)) CALL NOTE('RCF_H')
IF (ALLOCATED(R%RC_FACE) .AND. .NOT.ALLOCATED(F%RC_FACE)) CALL NOTE('RC_FACE')
IF (ALLOCATED(R%RHO_ZZN) .AND. .NOT.ALLOCATED(F%RHO_ZZN)) CALL NOTE('RHO_ZZN')
IF (ALLOCATED(R%CFACE) .AND. .NOT.ALLOCATED(F%CFACE)) CALL NOTE('CFACE')
IF (ALLOCATED(R%CC_RCEDGE) .AND. .NOT.ALLOCATED(F%CC_RCEDGE)) CALL NOTE('CC_RCEDGE')
IF (ALLOCATED(R%CC_IBEDGE) .AND. .NOT.ALLOCATED(F%CC_IBEDGE)) CALL NOTE('CC_IBEDGE')
IF (ALLOCATED(R%GEOM_ZMAX) .AND. .NOT.ALLOCATED(F%GEOM_ZMAX)) CALL NOTE('GEOM_ZMAX')
IF (ALLOCATED(R%SPCELL_LIST) .AND. .NOT.ALLOCATED(F%SPCELL_LIST)) CALL NOTE('SPCELL_LIST')
IF (ALLOCATED(R%SPCELLS_TO_BLOCK) .AND. .NOT.ALLOCATED(F%SPCELLS_TO_BLOCK)) CALL NOTE('SPCELLS_TO_BLOCK')
IF (ALLOCATED(R%EWC_UN_LNK) .AND. .NOT.ALLOCATED(F%EWC_UN_LNK)) CALL NOTE('EWC_UN_LNK')
IF (ALLOCATED(R%UN_LNK) .AND. .NOT.ALLOCATED(F%UN_LNK)) CALL NOTE('UN_LNK')
IF (ALLOCATED(R%UN_ULNK) .AND. .NOT.ALLOCATED(F%UN_ULNK)) CALL NOTE('UN_ULNK')
IF (ALLOCATED(R%INBCF_AREA) .AND. .NOT.ALLOCATED(F%INBCF_AREA)) CALL NOTE('INBCF_AREA')
IF (ALLOCATED(R%JBT_CC_BLOCKED) .AND. .NOT.ALLOCATED(F%JBT_CC_BLOCKED)) CALL NOTE('JBT_CC_BLOCKED')
IF (ALLOCATED(R%XYZ_CC_BLOCKED) .AND. .NOT.ALLOCATED(F%XYZ_CC_BLOCKED)) CALL NOTE('XYZ_CC_BLOCKED')
IF (ALLOCATED(R%JBT_CC_ELIMINATED) .AND. .NOT.ALLOCATED(F%JBT_CC_ELIMINATED)) CALL NOTE('JBT_CC_ELIMINATED')
IF (ALLOCATED(R%XYZ_CC_ELIMINATED) .AND. .NOT.ALLOCATED(F%XYZ_CC_ELIMINATED)) CALL NOTE('XYZ_CC_ELIMINATED')
IF (ALLOCATED(R%UVW_SAVE) .AND. .NOT.ALLOCATED(F%UVW_SAVE)) CALL NOTE('UVW_SAVE')
IF (ALLOCATED(R%U_GHOST) .AND. .NOT.ALLOCATED(F%U_GHOST)) CALL NOTE('U_GHOST')
IF (ALLOCATED(R%V_GHOST) .AND. .NOT.ALLOCATED(F%V_GHOST)) CALL NOTE('V_GHOST')
IF (ALLOCATED(R%W_GHOST) .AND. .NOT.ALLOCATED(F%W_GHOST)) CALL NOTE('W_GHOST')
IF (ALLOCATED(R%WALL) .AND. .NOT.ALLOCATED(F%WALL)) CALL NOTE('WALL')
IF (ALLOCATED(R%THIN_WALL) .AND. .NOT.ALLOCATED(F%THIN_WALL)) CALL NOTE('THIN_WALL')
IF (ALLOCATED(R%EXTERNAL_WALL) .AND. .NOT.ALLOCATED(F%EXTERNAL_WALL)) CALL NOTE('EXTERNAL_WALL')
IF (ALLOCATED(R%OMESH) .AND. .NOT.ALLOCATED(F%OMESH)) CALL NOTE('OMESH')
IF (ALLOCATED(R%LAGRANGIAN_PARTICLE) .AND. .NOT.ALLOCATED(F%LAGRANGIAN_PARTICLE)) CALL NOTE('LAGRANGIAN_PARTICLE')
IF (ALLOCATED(R%BOUNDARY_ONE_D) .AND. .NOT.ALLOCATED(F%BOUNDARY_ONE_D)) CALL NOTE('BOUNDARY_ONE_D')
IF (ALLOCATED(R%BOUNDARY_THR_D) .AND. .NOT.ALLOCATED(F%BOUNDARY_THR_D)) CALL NOTE('BOUNDARY_THR_D')
IF (ALLOCATED(R%BOUNDARY_COORD) .AND. .NOT.ALLOCATED(F%BOUNDARY_COORD)) CALL NOTE('BOUNDARY_COORD')
IF (ALLOCATED(R%BOUNDARY_PROP1) .AND. .NOT.ALLOCATED(F%BOUNDARY_PROP1)) CALL NOTE('BOUNDARY_PROP1')
IF (ALLOCATED(R%BOUNDARY_PROP2) .AND. .NOT.ALLOCATED(F%BOUNDARY_PROP2)) CALL NOTE('BOUNDARY_PROP2')
IF (ALLOCATED(R%BOUNDARY_RADIA) .AND. .NOT.ALLOCATED(F%BOUNDARY_RADIA)) CALL NOTE('BOUNDARY_RADIA')
IF (ALLOCATED(R%BOUNDARY_COORD_OCCUPANCY) .AND. .NOT.ALLOCATED(F%BOUNDARY_COORD_OCCUPANCY)) CALL NOTE('BOUNDARY_COORD_OCCUPANCY')
IF (ALLOCATED(R%BOUNDARY_ONE_D_OCCUPANCY) .AND. .NOT.ALLOCATED(F%BOUNDARY_ONE_D_OCCUPANCY)) CALL NOTE('BOUNDARY_ONE_D_OCCUPANCY')
IF (ALLOCATED(R%BOUNDARY_THR_D_OCCUPANCY) .AND. .NOT.ALLOCATED(F%BOUNDARY_THR_D_OCCUPANCY)) CALL NOTE('BOUNDARY_THR_D_OCCUPANCY')
IF (ALLOCATED(R%SLICE) .AND. .NOT.ALLOCATED(F%SLICE)) CALL NOTE('SLICE')
IF (ALLOCATED(R%UNIQUE_SLICE_NAMES) .AND. .NOT.ALLOCATED(F%UNIQUE_SLICE_NAMES)) CALL NOTE('UNIQUE_SLICE_NAMES')
IF (ALLOCATED(R%ALL_SLICE_NAMES) .AND. .NOT.ALLOCATED(F%ALL_SLICE_NAMES)) CALL NOTE('ALL_SLICE_NAMES')
IF (ALLOCATED(R%ALL_SLICE_QUANTITIES) .AND. .NOT.ALLOCATED(F%ALL_SLICE_QUANTITIES)) CALL NOTE('ALL_SLICE_QUANTITIES')
IF (ALLOCATED(R%ALL_SLICE_TOPOLOGIES) .AND. .NOT.ALLOCATED(F%ALL_SLICE_TOPOLOGIES)) CALL NOTE('ALL_SLICE_TOPOLOGIES')
IF (ALLOCATED(R%EMPTY_UNIQUE_SLICE) .AND. .NOT.ALLOCATED(F%EMPTY_UNIQUE_SLICE)) CALL NOTE('EMPTY_UNIQUE_SLICE')
IF (ALLOCATED(R%UNIQUE_SLICE_IS_SL3D) .AND. .NOT.ALLOCATED(F%UNIQUE_SLICE_IS_SL3D)) CALL NOTE('UNIQUE_SLICE_IS_SL3D')
IF (ALLOCATED(R%UNIQUE_SLICE_IN_DOMAIN) .AND. .NOT.ALLOCATED(F%UNIQUE_SLICE_IN_DOMAIN)) CALL NOTE('UNIQUE_SLICE_IN_DOMAIN')
IF (ALLOCATED(R%UNIQUE_SLCF_AGL) .AND. .NOT.ALLOCATED(F%UNIQUE_SLCF_AGL)) CALL NOTE('UNIQUE_SLCF_AGL')
IF (ALLOCATED(R%RAD_FILE) .AND. .NOT.ALLOCATED(F%RAD_FILE)) CALL NOTE('RAD_FILE')
IF (ALLOCATED(R%PATCH) .AND. .NOT.ALLOCATED(F%PATCH)) CALL NOTE('PATCH')
IF (ALLOCATED(R%EXTERIOR_PATCH) .AND. .NOT.ALLOCATED(F%EXTERIOR_PATCH)) CALL NOTE('EXTERIOR_PATCH')
IF (ALLOCATED(R%UIID) .AND. .NOT.ALLOCATED(F%UIID)) CALL NOTE('UIID')
IF (ALLOCATED(R%INTERPOLATED_MESH) .AND. .NOT.ALLOCATED(F%INTERPOLATED_MESH)) CALL NOTE('INTERPOLATED_MESH')
IF (ALLOCATED(R%STRING) .AND. .NOT.ALLOCATED(F%STRING)) CALL NOTE('STRING')
IF (ALLOCATED(R%K_AGL_SLICE) .AND. .NOT.ALLOCATED(F%K_AGL_SLICE)) CALL NOTE('K_AGL_SLICE')
IF (ALLOCATED(R%LS_KLO_TERRAIN) .AND. .NOT.ALLOCATED(F%LS_KLO_TERRAIN)) CALL NOTE('LS_KLO_TERRAIN')
IF (ALLOCATED(R%LS_KHI_TERRAIN) .AND. .NOT.ALLOCATED(F%LS_KHI_TERRAIN)) CALL NOTE('LS_KHI_TERRAIN')
IF (ALLOCATED(R%K_LS) .AND. .NOT.ALLOCATED(F%K_LS)) CALL NOTE('K_LS')
IF (ALLOCATED(R%LS_SURF_INDEX) .AND. .NOT.ALLOCATED(F%LS_SURF_INDEX)) CALL NOTE('LS_SURF_INDEX')
IF (ALLOCATED(R%FLUX0_LS) .AND. .NOT.ALLOCATED(F%FLUX0_LS)) CALL NOTE('FLUX0_LS')
IF (ALLOCATED(R%FLUX1_LS) .AND. .NOT.ALLOCATED(F%FLUX1_LS)) CALL NOTE('FLUX1_LS')
IF (ALLOCATED(R%PHI_LS) .AND. .NOT.ALLOCATED(F%PHI_LS)) CALL NOTE('PHI_LS')
IF (ALLOCATED(R%PHI1_LS) .AND. .NOT.ALLOCATED(F%PHI1_LS)) CALL NOTE('PHI1_LS')
IF (ALLOCATED(R%ROS_HEAD) .AND. .NOT.ALLOCATED(F%ROS_HEAD)) CALL NOTE('ROS_HEAD')
WRITE(6,'(A)') 'FINE-B BUILD AUDIT end'

CONTAINS
   SUBROUTINE NOTE(NAME)
   CHARACTER(*), INTENT(IN) :: NAME
   WRITE(6,'(A,A)') '   ',NAME
   END SUBROUTINE NOTE

END SUBROUTINE AUDIT_BUILT_BOX

SUBROUTINE BAD(KIND,TXT,GHOST_ONLY)
INTEGER, INTENT(IN) :: KIND
CHARACTER(*), INTENT(IN) :: TXT
LOGICAL, INTENT(IN), OPTIONAL :: GHOST_ONLY
IF (PRESENT(GHOST_ONLY)) THEN ; IF (GHOST_ONLY) THEN ; NBAD_G(KIND) = NBAD_G(KIND)+1 ; IF (NBAD_G(KIND)<=40) WRITE(0,'(A,A,A,A)') 'fine-b shadow ghost-layer difference in ',TRIM(KNAME(KIND)),': ',TXT ; RETURN ; ENDIF ; ENDIF
NBAD(KIND) = NBAD(KIND)+1
IF (NBAD(KIND)<=3) WRITE(0,'(A,A,A,A)') 'fine-b shadow MISMATCH in ',TRIM(KNAME(KIND)),': ',TXT
END SUBROUTINE BAD

SUBROUTINE CMP3(KIND,TXT,A,B,LA,LB)
INTEGER, INTENT(IN) :: KIND,LA(3),LB(3)
CHARACTER(*), INTENT(IN) :: TXT
REAL(EB), INTENT(IN) :: A(:,:,:),B(:,:,:)
INTEGER :: I,J,K,NG,NI_,LO(3),HI(3)
NCMP(KIND) = NCMP(KIND)+1
LO = MAX(LA,LB) ; HI = MIN(LA+SHAPE(A)-1,LB+SHAPE(B)-1)   ! the index range both arrays have (the driver's level-0 boxes may carry more ghost layers than a built box)
IF (ANY(HI<LO)) THEN ; CALL BAD(KIND,TXT//' (no common range)') ; RETURN ; ENDIF
NG = 0 ; NI_ = 0
DO K=LO(3),HI(3) ; DO J=LO(2),HI(2) ; DO I=LO(1),HI(1)
   IF (TRANSFER(A(I-LA(1)+1,J-LA(2)+1,K-LA(3)+1),0_C_INT64_T)/=TRANSFER(B(I-LB(1)+1,J-LB(2)+1,K-LB(3)+1),0_C_INT64_T)) THEN
      IF (IS_INTERIOR(I,J,K)) THEN ; NI_ = NI_+1 ; CALL LOC(KIND,TXT,I,J,K,A(I-LA(1)+1,J-LA(2)+1,K-LA(3)+1),B(I-LB(1)+1,J-LB(2)+1,K-LB(3)+1))
      ELSE ; NG = NG+1 ; CALL REL(KIND,A(I-LA(1)+1,J-LA(2)+1,K-LA(3)+1),B(I-LB(1)+1,J-LB(2)+1,K-LB(3)+1)) ; ENDIF
   ENDIF
ENDDO ; ENDDO ; ENDDO
IF (NI_>0) CALL BAD(KIND,TXT//' (core cells)')
IF (NG>0) THEN ; NGHOST(KIND) = NGHOST(KIND)+1 ; CALL BAD(KIND,TXT//' (shell/ghost cells)',.TRUE.) ; ENDIF
END SUBROUTINE CMP3

SUBROUTINE CMP4(KIND,TXT,A,B,LA,LB)
INTEGER, INTENT(IN) :: KIND,LA(4),LB(4)
CHARACTER(*), INTENT(IN) :: TXT
REAL(EB), INTENT(IN) :: A(:,:,:,:),B(:,:,:,:)
INTEGER :: I,J,K,N,NG,NI_,LO(4),HI(4)
NCMP(KIND) = NCMP(KIND)+1
LO = MAX(LA,LB) ; HI = MIN(LA+SHAPE(A)-1,LB+SHAPE(B)-1)
IF (ANY(HI<LO)) THEN ; CALL BAD(KIND,TXT//' (no common range)') ; RETURN ; ENDIF
NG = 0 ; NI_ = 0
DO N=LO(4),HI(4) ; DO K=LO(3),HI(3) ; DO J=LO(2),HI(2) ; DO I=LO(1),HI(1)
   IF (TRANSFER(A(I-LA(1)+1,J-LA(2)+1,K-LA(3)+1,N-LA(4)+1),0_C_INT64_T)/=TRANSFER(B(I-LB(1)+1,J-LB(2)+1,K-LB(3)+1,N-LB(4)+1),0_C_INT64_T)) THEN
      IF (IS_INTERIOR(I,J,K)) THEN ; NI_ = NI_+1
      ELSE ; NG = NG+1 ; CALL REL(KIND,A(I-LA(1)+1,J-LA(2)+1,K-LA(3)+1,N-LA(4)+1),B(I-LB(1)+1,J-LB(2)+1,K-LB(3)+1,N-LB(4)+1)) ; ENDIF
   ENDIF
ENDDO ; ENDDO ; ENDDO ; ENDDO
IF (NI_>0) CALL BAD(KIND,TXT//' (core cells)')
IF (NG>0) THEN ; NGHOST(KIND) = NGHOST(KIND)+1 ; CALL BAD(KIND,TXT//' (shell/ghost cells)',.TRUE.) ; ENDIF
END SUBROUTINE CMP4

!> Cells whose results must be bitwise those of the level-0 run: with the clone (BUILD false) every cell; with the built box (no walls) the cells at least two cells away from every box face
!> (the level-0 box has walls at its periodic faces, the fine box has ghost cells instead: the cells next to a face are compared for information only).
LOGICAL FUNCTION IS_INTERIOR(I,J,K)
INTEGER, INTENT(IN) :: I,J,K
INTEGER :: NI_,NJ_,NK_
IF (.NOT.BUILD) THEN ; IS_INTERIOR = .TRUE. ; RETURN ; ENDIF
NI_ = MESHES(1)%IBAR ; NJ_ = MESHES(1)%JBAR ; NK_ = MESHES(1)%KBAR
IS_INTERIOR = (NI_<5 .OR. (I>=3 .AND. I<=NI_-2)) .AND. (NJ_<5 .OR. (J>=3 .AND. J<=NJ_-2)) .AND. (NK_<5 .OR. (K>=3 .AND. K<=NK_-2)) .AND. &
              I>=1 .AND. I<=NI_ .AND. J>=1 .AND. J<=NJ_ .AND. K>=1 .AND. K<=NK_
IF (NI_<5 .AND. NJ_<5 .AND. NK_<5) IS_INTERIOR = .FALSE.
END FUNCTION IS_INTERIOR

SUBROUTINE REL(KIND,A,B)
INTEGER, INTENT(IN) :: KIND
REAL(EB), INTENT(IN) :: A,B
REAL(EB) :: R
R = ABS(A-B)/MAX(ABS(A),ABS(B),TINY(1._EB))
IF (R>MAXREL(KIND)) MAXREL(KIND) = R
END SUBROUTINE REL

SUBROUTINE LOC(KIND,TXT,I,J,K,A,B)
INTEGER, INTENT(IN) :: KIND,I,J,K
CHARACTER(*), INTENT(IN) :: TXT
REAL(EB), INTENT(IN) :: A,B
IF (NBAD(KIND)<3 .OR. DEBUG_LOC .AND. NBAD(KIND)<400) WRITE(0,'(A,A,A,A,I4,3I4,2ES24.16)') 'fine-b shadow interior difference in ',TRIM(KNAME(KIND)),' ',TXT,NCALL(KIND),I,J,K,A,B
END SUBROUTINE LOC

!> Print the per-kernel statistics; returns the number of mismatching array comparisons (0 = every shadowed kernel result is bitwise that of the level-0 run).
FUNCTION FDS_FINE_B_SHADOW_REPORT() RESULT(NFAIL) BIND(C,NAME='fds_fine_b_shadow_report')

INTEGER(C_INT) :: NFAIL
INTEGER :: K

NFAIL = SUM(NBAD)
DO K=1,NK
   WRITE(6,'(A,A10,A,I8,A,I8,A,I6,A,I6,A,ES9.2)') 'FINE-B SHADOW ',KNAME(K),' calls ',NCALL(K),' array comparisons ',NCMP(K),' core mismatches ',NBAD(K),' shell/ghost arrays differing ',NBAD_G(K),' max rel ',MAXREL(K)
ENDDO
WRITE(6,'(A,I0,A)') 'FINE-B SHADOW calls on other level-0 meshes skipped: ',NSKIP,' (needs a single level-0 mesh)'
IF (NFAIL==0 .AND. SUM(NCALL)>0) THEN ; WRITE(6,'(A)') 'FINE-B SHADOW PASS' ; ELSE ; WRITE(6,'(A)') 'FINE-B SHADOW FAIL' ; IF (SUM(NCALL)==0) NFAIL = 1 ; ENDIF
FLUSH(6)

END FUNCTION FDS_FINE_B_SHADOW_REPORT

END MODULE FDS_FINE_BOX_B
