!> \brief DRAFT (D-056 option B), compiled only with -DFDS_AMR_FINE_B_DRAFT=ON on a tree with patch 0007 applied; never part of the default build and not used for physics.
!> Builds fine-level mesh objects in FINE_LEVEL(:) (module MESH_POINTERS, patch 0007) with the metrics of an axis-aligned uniform box, reachable through POINT_TO_BOX, and tests the
!> pointer routing. The rest of the contents of level-interface.md section 3 (CELL/WALL tables, interface walls without OMESH neighbour, box state views from the FABs) follows
!> when the Architect has validated patch 0007 with the oneAPI compilers.
MODULE FDS_FINE_MESH_B

USE ISO_C_BINDING
USE PRECISION_PARAMETERS, ONLY: EB
USE MESH_VARIABLES, ONLY: MESHES,MESH_TYPE
USE MESH_POINTERS
USE FDS_AMREX_HOOKS, ONLY: BOX_VIEW_TYPE

IMPLICIT NONE (TYPE,EXTERNAL)
PRIVATE
PUBLIC :: FDS_FINE_B_MAKE,FDS_FINE_B_SELFTEST,FDS_FINE_B_ABORT_TEST

REAL(EB), TARGET, SAVE :: WTEST(0:9,0:5,0:9)

CONTAINS

!> Level LEV (>=1) with NBOX boxes of IBAR x JBAR x KBAR cells of size DXF, box IB with lower corner (X0+(IB-1)*IBAR*DXF, Y0, Z0). The mesh number of box IB is SIZE(MESHES)+(boxes of the levels below)+IB.
SUBROUTINE FDS_FINE_B_MAKE(LEV,NBOX,IBAR_,JBAR_,KBAR_,DXF,X0,Y0,Z0) BIND(C,NAME='fds_fine_b_make')

INTEGER(C_INT), VALUE :: LEV,NBOX,IBAR_,JBAR_,KBAR_
REAL(C_DOUBLE), VALUE :: DXF,X0,Y0,Z0
TYPE(FINE_LEVEL_TYPE), ALLOCATABLE :: TMP(:)
INTEGER :: L,IB,NM0

IF (.NOT.ALLOCATED(FINE_LEVEL)) ALLOCATE(FINE_LEVEL(0))
IF (LEV>SIZE(FINE_LEVEL)) THEN
   ALLOCATE(TMP(LEV))
   DO L=1,SIZE(FINE_LEVEL)
      CALL MOVE_ALLOC(FINE_LEVEL(L)%BOX,TMP(L)%BOX) ; CALL MOVE_ALLOC(FINE_LEVEL(L)%VIEW,TMP(L)%VIEW)
      TMP(L)%NM0 = FINE_LEVEL(L)%NM0 ; TMP(L)%N_BOXES = FINE_LEVEL(L)%N_BOXES
   ENDDO
   CALL MOVE_ALLOC(TMP,FINE_LEVEL)
ENDIF
NM0 = SIZE(MESHES)
DO L=1,LEV-1
   NM0 = NM0 + FINE_LEVEL(L)%N_BOXES
ENDDO
FINE_LEVEL(LEV)%NM0 = NM0 ; FINE_LEVEL(LEV)%N_BOXES = NBOX
IF (ALLOCATED(FINE_LEVEL(LEV)%BOX)) DEALLOCATE(FINE_LEVEL(LEV)%BOX)
IF (ALLOCATED(FINE_LEVEL(LEV)%VIEW)) DEALLOCATE(FINE_LEVEL(LEV)%VIEW)
ALLOCATE(FINE_LEVEL(LEV)%BOX(NBOX),FINE_LEVEL(LEV)%VIEW(NBOX))
DO IB=1,NBOX
   CALL SET_METRICS(FINE_LEVEL(LEV)%BOX(IB),NM0+IB,IBAR_,JBAR_,KBAR_,DXF,X0+(IB-1)*IBAR_*DXF,Y0,Z0)
ENDDO

END SUBROUTINE FDS_FINE_B_MAKE

SUBROUTINE SET_METRICS(M,NM,NI,NJ,NK,DXF,XS_,YS_,ZS_)

TYPE(MESH_TYPE), INTENT(INOUT) :: M
INTEGER, INTENT(IN) :: NM,NI,NJ,NK
REAL(EB), INTENT(IN) :: DXF,XS_,YS_,ZS_
INTEGER :: I

M%IBAR=NI ; M%JBAR=NJ ; M%KBAR=NK ; M%IBM1=NI-1 ; M%JBM1=NJ-1 ; M%KBM1=NK-1 ; M%IBP1=NI+1 ; M%JBP1=NJ+1 ; M%KBP1=NK+1
M%XS=XS_ ; M%YS=YS_ ; M%ZS=ZS_ ; M%XF=XS_+NI*DXF ; M%YF=YS_+NJ*DXF ; M%ZF=ZS_+NK*DXF
ALLOCATE(M%X(0:NI),M%XC(0:NI+1),M%DX(0:NI+1),M%RDX(0:NI+1),M%DXN(0:NI),M%RDXN(0:NI),M%R(0:NI),M%RRN(0:NI+1))
ALLOCATE(M%Y(0:NJ),M%YC(0:NJ+1),M%DY(0:NJ+1),M%RDY(0:NJ+1),M%DYN(0:NJ),M%RDYN(0:NJ))
ALLOCATE(M%Z(0:NK),M%ZC(0:NK+1),M%DZ(0:NK+1),M%RDZ(0:NK+1),M%DZN(0:NK),M%RDZN(0:NK))
DO I=0,NI   ; M%X(I)=XS_+I*DXF ; ENDDO
DO I=0,NJ   ; M%Y(I)=YS_+I*DXF ; ENDDO
DO I=0,NK   ; M%Z(I)=ZS_+I*DXF ; ENDDO
DO I=0,NI+1 ; M%XC(I)=XS_+(I-0.5_EB)*DXF ; ENDDO
DO I=0,NJ+1 ; M%YC(I)=YS_+(I-0.5_EB)*DXF ; ENDDO
DO I=0,NK+1 ; M%ZC(I)=ZS_+(I-0.5_EB)*DXF ; ENDDO
M%DX=DXF ; M%DY=DXF ; M%DZ=DXF ; M%RDX=1._EB/DXF ; M%RDY=1._EB/DXF ; M%RDZ=1._EB/DXF
M%DXN=DXF ; M%DYN=DXF ; M%DZN=DXF ; M%RDXN=1._EB/DXF ; M%RDYN=1._EB/DXF ; M%RDZN=1._EB/DXF
M%R=1._EB ; M%RRN=1._EB
ALLOCATE(M%U(0:NI+1,0:NJ+1,0:NK+1),M%W(0:NI+1,0:NJ+1,0:NK+1)) ; M%U=REAL(NM,EB) ; M%W=0._EB

END SUBROUTINE SET_METRICS

!> Pointer routing test (returns the number of failed checks): needs a level-0 mesh set-up (MESHES) and a level of fine boxes made by FDS_FINE_B_MAKE.
FUNCTION FDS_FINE_B_SELFTEST() RESULT(NFAIL) BIND(C,NAME='fds_fine_b_selftest')

INTEGER(C_INT) :: NFAIL
INTEGER :: IB,NM,N0
LOGICAL :: OK

NFAIL = 0 ; N0 = SIZE(MESHES)
CALL FDS_FINE_B_MAKE(1,2,8,4,8,0.0125_C_DOUBLE,0._C_DOUBLE,0._C_DOUBLE,0._C_DOUBLE)
FINE_LEVEL(1)%VIEW(2)%W(0:9,0:5,0:9) => WTEST
DO IB=1,2
   NM = N0+IB
   CALL POINT_TO_BOX(NM)
   OK = IBAR==8 .AND. JBAR==4 .AND. KBAR==8 .AND. ABS(DX(1)-0.0125_EB)<1.E-15_EB .AND. ABS(RDXN(3)*0.0125_EB-1._EB)<1.E-14_EB
   OK = OK .AND. ABS(XC(1)-(REAL(IB-1,EB)*8*0.0125_EB+0.5_EB*0.0125_EB))<1.E-14_EB
   OK = OK .AND. ASSOCIATED(U,FINE_LEVEL(1)%BOX(IB)%U) .AND. U(2,2,2)==REAL(NM,EB)
   CALL CHK(OK,'metrics and U of fine box',NFAIL)
   IF (IB==1) THEN
      OK = .NOT.ASSOCIATED(W,WTEST)
   ELSE
      OK = ASSOCIATED(W,WTEST) .AND. LBOUND(W,1)==0 .AND. UBOUND(W,3)==9     ! the view of box 2 replaces the (unallocated) FDS array
   ENDIF
   CALL CHK(OK,'view routing of W',NFAIL)
ENDDO
! level 0 is unchanged: POINT_TO_BOX(1) = POINT_TO_MESH(1) (no BOX_VIEW here), then POINT_TO_MESH(1) again
CALL POINT_TO_BOX(1)
OK = IBAR==MESHES(1)%IBAR .AND. ASSOCIATED(DX,MESHES(1)%DX)
CALL CHK(OK,'level-0 box unchanged',NFAIL)
CALL POINT_TO_MESH(1)
OK = ASSOCIATED(U,MESHES(1)%U)
CALL CHK(OK,'POINT_TO_MESH(1) unchanged',NFAIL)

END FUNCTION FDS_FINE_B_SELFTEST

SUBROUTINE CHK(OK,TXT,NFAIL)
LOGICAL, INTENT(IN) :: OK
CHARACTER(*), INTENT(IN) :: TXT
INTEGER(C_INT), INTENT(INOUT) :: NFAIL
IF (.NOT.OK) THEN ; NFAIL = NFAIL+1 ; WRITE(0,'(A,A)') 'fine-b selftest FAIL: ',TXT ; ENDIF
END SUBROUTINE CHK

!> KIND=1: POINT_TO_MESH on a fine mesh number (must stop with the clear message), 2: POINT_TO_BOX on a number that belongs to no level, 3: POINT_TO_BOX on a fine box (must work).
SUBROUTINE FDS_FINE_B_ABORT_TEST(KIND) BIND(C,NAME='fds_fine_b_abort_test')

INTEGER(C_INT), VALUE :: KIND

CALL FDS_FINE_B_MAKE(1,1,4,4,4,0.1_C_DOUBLE,0._C_DOUBLE,0._C_DOUBLE,0._C_DOUBLE)
SELECT CASE(KIND)
   CASE(1) ; CALL POINT_TO_MESH(SIZE(MESHES)+1)
   CASE(2) ; CALL POINT_TO_BOX(SIZE(MESHES)+7)
   CASE(3) ; CALL POINT_TO_BOX(SIZE(MESHES)+1)
END SELECT

END SUBROUTINE FDS_FINE_B_ABORT_TEST

END MODULE FDS_FINE_MESH_B
