# Runs the host and the offload build of tag_kernel_check and requires identical output (every case prints its tag count and checksum).
# Negative control: the comparison itself is checked on a deliberately altered copy of the output.
foreach(which HOST OFFLOAD)
    execute_process(COMMAND ${${which}} OUTPUT_VARIABLE out_${which} RESULT_VARIABLE rc_${which})
    if (NOT rc_${which} EQUAL 0)
        message(FATAL_ERROR "${which} build failed (exit ${rc_${which}}):\n${out_${which}}")
    endif()
endforeach()
string(REGEX MATCHALL "TK [^\n]*" lines_h "${out_HOST}")
string(REGEX MATCHALL "TK [^\n]*" lines_o "${out_OFFLOAD}")
list(LENGTH lines_h nh)
list(LENGTH lines_o no)
if (nh EQUAL 0 OR NOT nh EQUAL no)
    message(FATAL_ERROR "case count differs or is zero: host ${nh}, offload ${no}")
endif()
if (NOT "${lines_h}" STREQUAL "${lines_o}")
    message(FATAL_ERROR "host and offload outputs differ:\n${out_HOST}\n---\n${out_OFFLOAD}")
endif()
# control: one changed checksum digit must be seen as a difference
string(REPLACE "sum=" "sum=9" altered "${lines_o}")
if ("${lines_h}" STREQUAL "${altered}")
    message(FATAL_ERROR "comparison control failed: an altered output was not detected")
endif()
message(STATUS "host and offload tag kernels: ${nh} cases bitwise identical")
